/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/opt/nim/lib -o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_oids.o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_oids.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <time.h>
#include <stdlib.h>
#undef linux
typedef struct Oid_v0fX7UzOqz7toHgI0d87SA Oid_v0fX7UzOqz7toHgI0d87SA;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct  Oid_v0fX7UzOqz7toHgI0d87SA  {
NI32 time;
NI32 fuzz;
NI32 count;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NIM_BOOL, HEX3DHEX3D_64QI4g9auky303LA9bv0oaXQ)(Oid_v0fX7UzOqz7toHgI0d87SA oid10, Oid_v0fX7UzOqz7toHgI0d87SA oid20);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, hexbyte_QCPx9abgIgtvQ39aT8xIuEJw)(NIM_CHAR hex0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NIMCALL(Oid_v0fX7UzOqz7toHgI0d87SA, parseoid_ZKKq9c1E1NLXB9aa1kqgNwXQ)(NCSTRING str0);
N_NIMCALL(NI, mulInt)(NI a0, NI b0);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
N_NIMCALL(void, oidtostring_khwHESMMJSplBOOFbhAnFQ)(Oid_v0fX7UzOqz7toHgI0d87SA oid0, NCSTRING str_ddF9czGvnAErpuzppGp40eg);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, HEX24_XZmIDj6b72IIMfJvOft31Q)(Oid_v0fX7UzOqz7toHgI0d87SA oid0);
N_NIMCALL(NimStringDesc*, mnewString)(NI len0);
N_NIMCALL(NimStringDesc*, mnewString)(NI len0);
N_NIMCALL(Oid_v0fX7UzOqz7toHgI0d87SA, genoid_CiwhU4LwBy9bUOUutq9cQYOQ)(void);
static N_INLINE(NI, atomicinc_4E9cxwuunx9aiL7vj9bdy8WvAsystem)(NI* memloc0, NI x0);
static N_INLINE(void, bigendian32_IzdisrH4sYnsItUtxSkomA_8endians)(void* outp0, void* inp0);
static N_INLINE(void, swapendian32_IzdisrH4sYnsItUtxSkomA_2endians)(void* outp0, void* inp0);
N_NIMCALL(time_t, generatedtime_M1ZAR9c5o7yGRtr8tvZy1KA)(Oid_v0fX7UzOqz7toHgI0d87SA oid0);
extern NIM_THREADVAR TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NI incr_uxzATGLVK9aAfCz88FkdO0g;
NI32 fuzz_8VX8F8ZpvRGTMF7N4xU39cg;
STRING_LITERAL(T_UTnk8gn1Oi9cBJSIU9cQGLMA_12, "0123456789abcdef", 16);

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(NIM_BOOL, HEX3DHEX3D_64QI4g9auky303LA9bv0oaXQ)(Oid_v0fX7UzOqz7toHgI0d87SA oid10, Oid_v0fX7UzOqz7toHgI0d87SA oid20) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	NIM_BOOL LOC2;
	nimfr("==", "oids.nim")
{	result0 = (NIM_BOOL)0;
	nimln(30, "oids.nim");
	LOC1 = (NIM_BOOL)0;
	LOC2 = (NIM_BOOL)0;
	LOC2 = (oid10.time == oid20.time);
	if (!(LOC2)) goto LA3;
	LOC2 = (oid10.fuzz == oid20.fuzz);
	LA3: ;
	LOC1 = LOC2;
	if (!(LOC1)) goto LA4;
	LOC1 = (oid10.count == oid20.count);
	LA4: ;
	result0 = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NI, hexbyte_QCPx9abgIgtvQ39aT8xIuEJw)(NIM_CHAR hex0) {
	NI result0;
	nimfr("hexbyte", "oids.nim")
	result0 = (NI)0;
	nimln(33, "oids.nim");
	switch (((NU8)(hex0))) {
	case 48 ... 57:
	{
		NI T_UTnk8gn1Oi9cBJSIU9cQGLMA_2;
		nimln(34, "oids.nim");
		T_UTnk8gn1Oi9cBJSIU9cQGLMA_2 = subInt(((NI) (((NU8)(hex0)))), ((NI) 48));
		result0 = ((NI) ((NI)(T_UTnk8gn1Oi9cBJSIU9cQGLMA_2)));
	}
	break;
	case 97 ... 102:
	{
		NI T_UTnk8gn1Oi9cBJSIU9cQGLMA_3;
		NI T_UTnk8gn1Oi9cBJSIU9cQGLMA_4;
		nimln(35, "oids.nim");
		T_UTnk8gn1Oi9cBJSIU9cQGLMA_3 = subInt(((NI) (((NU8)(hex0)))), ((NI) 97));
		T_UTnk8gn1Oi9cBJSIU9cQGLMA_4 = addInt(((NI) ((NI)(T_UTnk8gn1Oi9cBJSIU9cQGLMA_3))), ((NI) 10));
		result0 = ((NI) ((NI)(T_UTnk8gn1Oi9cBJSIU9cQGLMA_4)));
	}
	break;
	case 65 ... 70:
	{
		NI T_UTnk8gn1Oi9cBJSIU9cQGLMA_5;
		NI T_UTnk8gn1Oi9cBJSIU9cQGLMA_6;
		nimln(36, "oids.nim");
		T_UTnk8gn1Oi9cBJSIU9cQGLMA_5 = subInt(((NI) (((NU8)(hex0)))), ((NI) 65));
		T_UTnk8gn1Oi9cBJSIU9cQGLMA_6 = addInt(((NI) ((NI)(T_UTnk8gn1Oi9cBJSIU9cQGLMA_5))), ((NI) 10));
		result0 = ((NI) ((NI)(T_UTnk8gn1Oi9cBJSIU9cQGLMA_6)));
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result0;
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(Oid_v0fX7UzOqz7toHgI0d87SA, parseoid_ZKKq9c1E1NLXB9aa1kqgNwXQ)(NCSTRING str0) {
	Oid_v0fX7UzOqz7toHgI0d87SA result0;
	NCSTRING bytes0;
	NI i0;
	nimfr("parseOid", "oids.nim")
	memset((void*)(&result0), 0, sizeof(result0));
	nimln(41, "oids.nim");
	bytes0 = ((NCSTRING) ((&result0.time)));
	nimln(42, "oids.nim");
	i0 = ((NI) 0);
	{
		nimln(43, "oids.nim");
		while (1) {
			NI T_UTnk8gn1Oi9cBJSIU9cQGLMA_7;
			NI LOC3;
			NI T_UTnk8gn1Oi9cBJSIU9cQGLMA_8;
			NI T_UTnk8gn1Oi9cBJSIU9cQGLMA_9;
			NI LOC4;
			NI T_UTnk8gn1Oi9cBJSIU9cQGLMA_10;
			if (!(i0 < ((NI) 12))) goto LA2;
			nimln(44, "oids.nim");
			T_UTnk8gn1Oi9cBJSIU9cQGLMA_7 = mulInt(((NI) 2), i0);
			LOC3 = (NI)0;
			LOC3 = hexbyte_QCPx9abgIgtvQ39aT8xIuEJw(str0[(NI)(T_UTnk8gn1Oi9cBJSIU9cQGLMA_7)]);
			T_UTnk8gn1Oi9cBJSIU9cQGLMA_8 = mulInt(((NI) 2), i0);
			T_UTnk8gn1Oi9cBJSIU9cQGLMA_9 = addInt((NI)(T_UTnk8gn1Oi9cBJSIU9cQGLMA_8), ((NI) 1));
			LOC4 = (NI)0;
			LOC4 = hexbyte_QCPx9abgIgtvQ39aT8xIuEJw(str0[(NI)(T_UTnk8gn1Oi9cBJSIU9cQGLMA_9)]);
			bytes0[i0] = ((NIM_CHAR) (((NI)chckRange((NI)((NI)((NU64)(LOC3) << (NU64)(((NI) 4))) | LOC4), ((NI) 0), ((NI) 255)))));
			nimln(45, "oids.nim");
			T_UTnk8gn1Oi9cBJSIU9cQGLMA_10 = addInt(i0, ((NI) 1));
			i0 = (NI)(T_UTnk8gn1Oi9cBJSIU9cQGLMA_10);
		} LA2: ;
	}
	popFrame();
	return result0;
}

N_NIMCALL(void, oidtostring_khwHESMMJSplBOOFbhAnFQ)(Oid_v0fX7UzOqz7toHgI0d87SA oid0, NCSTRING str_ddF9czGvnAErpuzppGp40eg) {
	NCSTRING str0;
	Oid_v0fX7UzOqz7toHgI0d87SA o0;
	NCSTRING bytes0;
	NI i0;
	nimfr("oidToString", "oids.nim")
	nimln(50, "oids.nim");
	str0 = str_ddF9czGvnAErpuzppGp40eg;
	nimln(51, "oids.nim");
	o0 = oid0;
	nimln(52, "oids.nim");
	bytes0 = ((NCSTRING) ((&o0)));
	nimln(53, "oids.nim");
	i0 = ((NI) 0);
	{
		nimln(54, "oids.nim");
		while (1) {
			NI b0;
			NI T_UTnk8gn1Oi9cBJSIU9cQGLMA_11;
			NI T_UTnk8gn1Oi9cBJSIU9cQGLMA_13;
			NI T_UTnk8gn1Oi9cBJSIU9cQGLMA_14;
			NI T_UTnk8gn1Oi9cBJSIU9cQGLMA_15;
			if (!(i0 < ((NI) 12))) goto LA2;
			nimln(55, "oids.nim");
			b0 = ((NU8)(bytes0[i0]));
			nimln(56, "oids.nim");
			T_UTnk8gn1Oi9cBJSIU9cQGLMA_11 = mulInt(((NI) 2), i0);
			if ((NU)((NI)((NU64)((NI)(((NI) (b0)) & ((NI) 240))) >> (NU64)(((NI) 4)))) > (NU)(((NimStringDesc*) &T_UTnk8gn1Oi9cBJSIU9cQGLMA_12)->Sup.len)) raiseIndexError();
			str0[(NI)(T_UTnk8gn1Oi9cBJSIU9cQGLMA_11)] = ((NimStringDesc*) &T_UTnk8gn1Oi9cBJSIU9cQGLMA_12)->data[(NI)((NU64)((NI)(((NI) (b0)) & ((NI) 240))) >> (NU64)(((NI) 4)))];
			nimln(57, "oids.nim");
			T_UTnk8gn1Oi9cBJSIU9cQGLMA_13 = mulInt(((NI) 2), i0);
			T_UTnk8gn1Oi9cBJSIU9cQGLMA_14 = addInt((NI)(T_UTnk8gn1Oi9cBJSIU9cQGLMA_13), ((NI) 1));
			if ((NU)((NI)(((NI) (b0)) & ((NI) 15))) > (NU)(((NimStringDesc*) &T_UTnk8gn1Oi9cBJSIU9cQGLMA_12)->Sup.len)) raiseIndexError();
			str0[(NI)(T_UTnk8gn1Oi9cBJSIU9cQGLMA_14)] = ((NimStringDesc*) &T_UTnk8gn1Oi9cBJSIU9cQGLMA_12)->data[(NI)(((NI) (b0)) & ((NI) 15))];
			nimln(58, "oids.nim");
			T_UTnk8gn1Oi9cBJSIU9cQGLMA_15 = addInt(i0, ((NI) 1));
			i0 = (NI)(T_UTnk8gn1Oi9cBJSIU9cQGLMA_15);
		} LA2: ;
	}
	nimln(59, "oids.nim");
	str0[((NI) 24)] = 0;
	popFrame();
}

N_NIMCALL(NimStringDesc*, HEX24_XZmIDj6b72IIMfJvOft31Q)(Oid_v0fX7UzOqz7toHgI0d87SA oid0) {
	NimStringDesc* result0;
	nimfr("$", "oids.nim")
	result0 = (NimStringDesc*)0;
	nimln(62, "oids.nim");
	result0 = mnewString(((NI) 24));
	nimln(63, "oids.nim");
	oidtostring_khwHESMMJSplBOOFbhAnFQ(oid0, result0->data);
	popFrame();
	return result0;
}

static N_INLINE(NI, atomicinc_4E9cxwuunx9aiL7vj9bdy8WvAsystem)(NI* memloc0, NI x0) {
	NI result0;
	result0 = (NI)0;
	result0 = __atomic_add_fetch(memloc0, x0, __ATOMIC_RELAXED);
	return result0;
}

static N_INLINE(void, swapendian32_IzdisrH4sYnsItUtxSkomA_2endians)(void* outp0, void* inp0) {
	NU32* i0;
	NU32* o0;
	nimfr("swapEndian32", "endians.nim")
	nimln(53, "endians.nim");
	i0 = ((NU32*) (inp0));
	nimln(54, "endians.nim");
	o0 = ((NU32*) (outp0));
	nimln(55, "endians.nim");
	(*o0) = __builtin_bswap32((*i0));
	popFrame();
}

static N_INLINE(void, bigendian32_IzdisrH4sYnsItUtxSkomA_8endians)(void* outp0, void* inp0) {
	nimfr("bigEndian32", "endians.nim")
	nimln(107, "endians.nim");
	swapendian32_IzdisrH4sYnsItUtxSkomA_2endians(outp0, inp0);
	popFrame();
}

N_NIMCALL(Oid_v0fX7UzOqz7toHgI0d87SA, genoid_CiwhU4LwBy9bUOUutq9cQYOQ)(void) {
	Oid_v0fX7UzOqz7toHgI0d87SA result0;
	int t0;
	NI32 i0;
	NI LOC1;
	nimfr("genOid", "oids.nim")
	memset((void*)(&result0), 0, sizeof(result0));
	nimln(75, "oids.nim");
	t0 = time(NIM_NIL);
	nimln(77, "oids.nim");
	LOC1 = (NI)0;
	LOC1 = atomicinc_4E9cxwuunx9aiL7vj9bdy8WvAsystem((&incr_uxzATGLVK9aAfCz88FkdO0g), ((NI) 1));
	i0 = ((NI32)chckRange(LOC1, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
	nimln(79, "oids.nim");
	{
		if (!(fuzz_8VX8F8ZpvRGTMF7N4xU39cg == ((NI32) 0))) goto LA4;
		nimln(81, "oids.nim");
		srand(t0);
		nimln(82, "oids.nim");
		fuzz_8VX8F8ZpvRGTMF7N4xU39cg = rand();
	}
	LA4: ;
	nimln(83, "oids.nim");
	bigendian32_IzdisrH4sYnsItUtxSkomA_8endians(((void*) ((&result0.time))), ((void*) ((&t0))));
	nimln(84, "oids.nim");
	result0.fuzz = fuzz_8VX8F8ZpvRGTMF7N4xU39cg;
	nimln(85, "oids.nim");
	bigendian32_IzdisrH4sYnsItUtxSkomA_8endians(((void*) ((&result0.count))), ((void*) ((&i0))));
	popFrame();
	return result0;
}

N_NIMCALL(time_t, generatedtime_M1ZAR9c5o7yGRtr8tvZy1KA)(Oid_v0fX7UzOqz7toHgI0d87SA oid0) {
	time_t result0;
	NI32 tmp0;
	NI32 dummy0;
	nimfr("generatedTime", "oids.nim")
	result0 = (time_t)0;
	tmp0 = (NI32)0;
	nimln(90, "oids.nim");
	dummy0 = oid0.time;
	nimln(91, "oids.nim");
	bigendian32_IzdisrH4sYnsItUtxSkomA_8endians(((void*) ((&tmp0))), ((void*) ((&dummy0))));
	nimln(92, "oids.nim");
	result0 = ((time_t) (tmp0));
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_oidsInit000)(void) {
	nimfr("oids", "oids.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_oidsDatInit000)(void) {
}

