/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/opt/nim/lib -o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_posix.o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_posix.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/socket.h>
#undef linux
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NIM_CHAR TY_dTlC27m9c9aWd5dvuePYanug[256];
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
TNimType NTI_9cZH5RlAr01KsIvF1l3qtjg;
TNimType NTI_O6FgeeKj9aWQk0Yis9btN5NA;
TNimType NTI_izBnW6u2uORlL4DiGflKAw;
extern TNimType NTI_nmiMWKVIe46vacnhAFrQvw;
TNimType NTI_dTlC27m9c9aWd5dvuePYanug;
TNimType NTI_TCRYwcKSxUXq9bMcFqsXBVw;
TNimType NTI_hPc7XqKClD9b78QZzY9cBimw;
extern NIM_THREADVAR TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void) {
	nimfr("posix", "posix.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void) {
static TNimNode* T_mJPr4mHlDfNAl9asG6X7NFA_2[2];
static TNimNode T_mJPr4mHlDfNAl9asG6X7NFA_0[3];
NTI_9cZH5RlAr01KsIvF1l3qtjg.size = sizeof(socklen_t);
NTI_9cZH5RlAr01KsIvF1l3qtjg.kind = 43;
NTI_9cZH5RlAr01KsIvF1l3qtjg.base = 0;
NTI_9cZH5RlAr01KsIvF1l3qtjg.flags = 3;
NTI_O6FgeeKj9aWQk0Yis9btN5NA.size = sizeof(struct sockaddr);
NTI_O6FgeeKj9aWQk0Yis9btN5NA.kind = 18;
NTI_O6FgeeKj9aWQk0Yis9btN5NA.base = 0;
NTI_O6FgeeKj9aWQk0Yis9btN5NA.flags = 3;
T_mJPr4mHlDfNAl9asG6X7NFA_2[0] = &T_mJPr4mHlDfNAl9asG6X7NFA_0[1];
NTI_izBnW6u2uORlL4DiGflKAw.size = sizeof(sa_family_t);
NTI_izBnW6u2uORlL4DiGflKAw.kind = 34;
NTI_izBnW6u2uORlL4DiGflKAw.base = 0;
NTI_izBnW6u2uORlL4DiGflKAw.flags = 3;
T_mJPr4mHlDfNAl9asG6X7NFA_0[1].kind = 1;
T_mJPr4mHlDfNAl9asG6X7NFA_0[1].offset = offsetof(struct sockaddr, sa_family);
T_mJPr4mHlDfNAl9asG6X7NFA_0[1].typ = (&NTI_izBnW6u2uORlL4DiGflKAw);
T_mJPr4mHlDfNAl9asG6X7NFA_0[1].name = "sa_family";
T_mJPr4mHlDfNAl9asG6X7NFA_2[1] = &T_mJPr4mHlDfNAl9asG6X7NFA_0[2];
NTI_dTlC27m9c9aWd5dvuePYanug.size = sizeof(TY_dTlC27m9c9aWd5dvuePYanug);
NTI_dTlC27m9c9aWd5dvuePYanug.kind = 16;
NTI_dTlC27m9c9aWd5dvuePYanug.base = (&NTI_nmiMWKVIe46vacnhAFrQvw);
NTI_dTlC27m9c9aWd5dvuePYanug.flags = 3;
T_mJPr4mHlDfNAl9asG6X7NFA_0[2].kind = 1;
T_mJPr4mHlDfNAl9asG6X7NFA_0[2].offset = offsetof(struct sockaddr, sa_data);
T_mJPr4mHlDfNAl9asG6X7NFA_0[2].typ = (&NTI_dTlC27m9c9aWd5dvuePYanug);
T_mJPr4mHlDfNAl9asG6X7NFA_0[2].name = "sa_data";
T_mJPr4mHlDfNAl9asG6X7NFA_0[0].len = 2; T_mJPr4mHlDfNAl9asG6X7NFA_0[0].kind = 2; T_mJPr4mHlDfNAl9asG6X7NFA_0[0].sons = &T_mJPr4mHlDfNAl9asG6X7NFA_2[0];
NTI_O6FgeeKj9aWQk0Yis9btN5NA.node = &T_mJPr4mHlDfNAl9asG6X7NFA_0[0];
NTI_TCRYwcKSxUXq9bMcFqsXBVw.size = sizeof(struct sockaddr*);
NTI_TCRYwcKSxUXq9bMcFqsXBVw.kind = 21;
NTI_TCRYwcKSxUXq9bMcFqsXBVw.base = (&NTI_O6FgeeKj9aWQk0Yis9btN5NA);
NTI_TCRYwcKSxUXq9bMcFqsXBVw.flags = 3;
NTI_hPc7XqKClD9b78QZzY9cBimw.size = sizeof(socklen_t*);
NTI_hPc7XqKClD9b78QZzY9cBimw.kind = 21;
NTI_hPc7XqKClD9b78QZzY9cBimw.base = (&NTI_9cZH5RlAr01KsIvF1l3qtjg);
NTI_hPc7XqKClD9b78QZzY9cBimw.flags = 3;
}

