/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/opt/nim/lib -o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_net.o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_net.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/socket.h>
#include <errno.h>
#undef linux
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NU8 Socketflag_4xio0cAXR7XG4pF9bVcpxEg;
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 Socketflag_4xio0cAXR7XG4pF9bVcpxEg_Set;
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
TNimType NTI_4xio0cAXR7XG4pF9bVcpxEg;
extern NIM_THREADVAR TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(int, toosflags_LPk8C9cHJSVIMMTqcH4p4xA)(Socketflag_4xio0cAXR7XG4pF9bVcpxEg_Set socketflags0) {
	int result0;
	nimfr("toOSFlags", "net.nim")
	result0 = (int)0;
	{
		Socketflag_4xio0cAXR7XG4pF9bVcpxEg f_58zDZXqG0ArUswniqWXnPg;
		NI i_eylLvCneeMVBBBy1QwWe9bA;
		f_58zDZXqG0ArUswniqWXnPg = (Socketflag_4xio0cAXR7XG4pF9bVcpxEg)0;
		nimln(2033, "system.nim");
		i_eylLvCneeMVBBBy1QwWe9bA = ((NI) 0);
		{
			nimln(2034, "system.nim");
			while (1) {
				NI T_XqsrSBxhOTPgLQ9cX4MmV4A_5;
				nimln(2033, "system.nim");
				if (!(i_eylLvCneeMVBBBy1QwWe9bA <= ((NI) 1))) goto LA3;
				nimln(2035, "system.nim");
				{
					nimln(196, "net.nim");
					if (!((socketflags0 &(1U<<((NU)(((Socketflag_4xio0cAXR7XG4pF9bVcpxEg)chckRange(i_eylLvCneeMVBBBy1QwWe9bA, ((Socketflag_4xio0cAXR7XG4pF9bVcpxEg) 0), ((Socketflag_4xio0cAXR7XG4pF9bVcpxEg) 1))))&7U)))!=0)) goto LA6;
					nimln(2035, "system.nim");
					f_58zDZXqG0ArUswniqWXnPg = ((Socketflag_4xio0cAXR7XG4pF9bVcpxEg)chckRange(i_eylLvCneeMVBBBy1QwWe9bA, ((Socketflag_4xio0cAXR7XG4pF9bVcpxEg) 0), ((Socketflag_4xio0cAXR7XG4pF9bVcpxEg) 1)));
					{
						nimln(197, "net.nim");
						switch (f_58zDZXqG0ArUswniqWXnPg) {
						case ((Socketflag_4xio0cAXR7XG4pF9bVcpxEg) 0):
						{
							nimln(199, "net.nim");
							result0 = (NI32)(result0 | MSG_PEEK);
						}
						break;
						case ((Socketflag_4xio0cAXR7XG4pF9bVcpxEg) 1):
						{
							nimln(200, "net.nim");
							goto LA8;
						}
						break;
						}
					} LA8: ;
				}
				LA6: ;
				nimln(2033, "system.nim");
				T_XqsrSBxhOTPgLQ9cX4MmV4A_5 = addInt(i_eylLvCneeMVBBBy1QwWe9bA, ((NI) 1));
				i_eylLvCneeMVBBBy1QwWe9bA = (NI)(T_XqsrSBxhOTPgLQ9cX4MmV4A_5);
			} LA3: ;
		}
	}
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, isdisconnectionerror_tWh5jL9aNOdo3APmHb1OdQA)(Socketflag_4xio0cAXR7XG4pF9bVcpxEg_Set flags0, NI32 lasterror0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	nimfr("isDisconnectionError", "net.nim")
	result0 = (NIM_BOOL)0;
	nimln(184, "net.nim");
	nimln(191, "net.nim");
	LOC1 = (NIM_BOOL)0;
	LOC1 = ((flags0 &(1U<<((NU)(((Socketflag_4xio0cAXR7XG4pF9bVcpxEg) 1))&7U)))!=0);
	if (!(LOC1)) goto LA2;
	nimln(192, "net.nim");
	LOC1 = (lasterror0 == ((NI)chckRange(ECONNRESET, ((NI) 0), ((NI) 65535))) || lasterror0 == ((NI)chckRange(EPIPE, ((NI) 0), ((NI) 65535))) || lasterror0 == ((NI)chckRange(ENETRESET, ((NI) 0), ((NI) 65535))));
	LA2: ;
	result0 = LOC1;
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit000)(void) {
	nimfr("net", "net.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit000)(void) {
static TNimNode* T_XqsrSBxhOTPgLQ9cX4MmV4A_2[2];
NI T_XqsrSBxhOTPgLQ9cX4MmV4A_4;
static char* NIM_CONST T_XqsrSBxhOTPgLQ9cX4MmV4A_3[2] = {
"Peek", 
"SafeDisconn"};
static TNimNode T_XqsrSBxhOTPgLQ9cX4MmV4A_0[3];
NTI_4xio0cAXR7XG4pF9bVcpxEg.size = sizeof(Socketflag_4xio0cAXR7XG4pF9bVcpxEg);
NTI_4xio0cAXR7XG4pF9bVcpxEg.kind = 14;
NTI_4xio0cAXR7XG4pF9bVcpxEg.base = 0;
NTI_4xio0cAXR7XG4pF9bVcpxEg.flags = 3;
for (T_XqsrSBxhOTPgLQ9cX4MmV4A_4 = 0; T_XqsrSBxhOTPgLQ9cX4MmV4A_4 < 2; T_XqsrSBxhOTPgLQ9cX4MmV4A_4++) {
T_XqsrSBxhOTPgLQ9cX4MmV4A_0[T_XqsrSBxhOTPgLQ9cX4MmV4A_4+0].kind = 1;
T_XqsrSBxhOTPgLQ9cX4MmV4A_0[T_XqsrSBxhOTPgLQ9cX4MmV4A_4+0].offset = T_XqsrSBxhOTPgLQ9cX4MmV4A_4;
T_XqsrSBxhOTPgLQ9cX4MmV4A_0[T_XqsrSBxhOTPgLQ9cX4MmV4A_4+0].name = T_XqsrSBxhOTPgLQ9cX4MmV4A_3[T_XqsrSBxhOTPgLQ9cX4MmV4A_4];
T_XqsrSBxhOTPgLQ9cX4MmV4A_2[T_XqsrSBxhOTPgLQ9cX4MmV4A_4] = &T_XqsrSBxhOTPgLQ9cX4MmV4A_0[T_XqsrSBxhOTPgLQ9cX4MmV4A_4+0];
}
T_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].len = 2; T_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].kind = 2; T_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].sons = &T_XqsrSBxhOTPgLQ9cX4MmV4A_2[0];
NTI_4xio0cAXR7XG4pF9bVcpxEg.node = &T_XqsrSBxhOTPgLQ9cX4MmV4A_0[2];
}

