/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/opt/nim/lib -o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_threadpool.o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_threadpool.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <pthread.h>
#include <sys/types.h>
                          #include <pthread.h>
#include <string.h>
#include <setjmp.h>
#include <sys/types.h>
#undef linux
typedef struct Semaphore_sx9abLHOwgGDBH9bpoqw2ezw Semaphore_sx9abLHOwgGDBH9bpoqw2ezw;
typedef struct Barrier Barrier;
typedef struct Flowvarbaseobj_CJfwFDAb1ST4bu6G9bMAYbg Flowvarbaseobj_CJfwFDAb1ST4bu6G9bMAYbg;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Awaitinfo_InuzBj4ASNnb8C8ZpRzfbA Awaitinfo_InuzBj4ASNnb8C8ZpRzfbA;
typedef struct Worker_AqHEWWcw2VBFjoa2Hp8Akw Worker_AqHEWWcw2VBFjoa2Hp8Akw;
typedef struct Tofreequeue_5COJP8EWIaAuXvZlDbQZmw Tofreequeue_5COJP8EWIaAuXvZlDbQZmw;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Exception Exception;
typedef struct TSafePoint TSafePoint;
typedef struct Thread_T9cLzsvk8o9b7NIZJCAgybKw Thread_T9cLzsvk8o9b7NIZJCAgybKw;
typedef struct Gcthread_hgJQSlfXDOK3SwSHjeZBXg Gcthread_hgJQSlfXDOK3SwSHjeZBXg;
typedef struct Threadpoolstate_jN9benzGjAA9bryIHC1FGnZA Threadpoolstate_jN9benzGjAA9bryIHC1FGnZA;
struct  Semaphore_sx9abLHOwgGDBH9bpoqw2ezw  {
pthread_cond_t c;
pthread_mutex_t L;
NI counter;
};
typedef NU8 TY_izDbpwaA8Rxj9b5mE6pSF7Q[24];
struct  Barrier  {
NI entered;
Semaphore_sx9abLHOwgGDBH9bpoqw2ezw cv;
NI left;
TY_izDbpwaA8Rxj9b5mE6pSF7Q cacheAlign2;
NIM_BOOL interest;
};
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Flowvarbaseobj_CJfwFDAb1ST4bu6G9bMAYbg  {
  TNimObject Sup;
NIM_BOOL ready;
NIM_BOOL usessemaphore;
NIM_BOOL awaited;
Semaphore_sx9abLHOwgGDBH9bpoqw2ezw cv;
Awaitinfo_InuzBj4ASNnb8C8ZpRzfbA* ai;
NI idx;
void* data;
void* owner;
};
typedef N_NIMCALL_PTR(void, TY_fhqfcnDhIcLpBpSTVsWEZg) (void* thread0, void* args0);
typedef void* TY_2PWyF6nokyTyhzmcY3ON3w[128];
struct  Tofreequeue_5COJP8EWIaAuXvZlDbQZmw  {
NI len;
pthread_mutex_t lock;
Semaphore_sx9abLHOwgGDBH9bpoqw2ezw empty;
TY_2PWyF6nokyTyhzmcY3ON3w data;
};
struct  Worker_AqHEWWcw2VBFjoa2Hp8Akw  {
Semaphore_sx9abLHOwgGDBH9bpoqw2ezw taskarrived;
Semaphore_sx9abLHOwgGDBH9bpoqw2ezw taskstarted;
TY_fhqfcnDhIcLpBpSTVsWEZg f;
void* data;
NIM_BOOL ready;
NIM_BOOL initialized;
NIM_BOOL shutdown;
Tofreequeue_5COJP8EWIaAuXvZlDbQZmw q;
Semaphore_sx9abLHOwgGDBH9bpoqw2ezw readyfortask;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Awaitinfo_InuzBj4ASNnb8C8ZpRzfbA  {
Semaphore_sx9abLHOwgGDBH9bpoqw2ezw cv;
NI idx;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e0, void* ClEnv);
void* ClEnv;
} TY_KeeAOYBd84Ofsw6Y7LizaQ;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
struct  Gcthread_hgJQSlfXDOK3SwSHjeZBXg  {
pthread_t sys;
};
typedef N_NIMCALL_PTR(void, TY_nSqh6BBL9cSEu9bcR48Z72QA) (Worker_AqHEWWcw2VBFjoa2Hp8Akw* m_0x9apmMLA4wzckULsmv57Lw);
struct  Thread_T9cLzsvk8o9b7NIZJCAgybKw  {
  Gcthread_hgJQSlfXDOK3SwSHjeZBXg Sup;
TY_nSqh6BBL9cSEu9bcR48Z72QA datafn;
Worker_AqHEWWcw2VBFjoa2Hp8Akw* data;
};
typedef Thread_T9cLzsvk8o9b7NIZJCAgybKw TY_t64oTbxGYdi34RY7u0jpWg[256];
typedef Worker_AqHEWWcw2VBFjoa2Hp8Akw TY_5sGw9aMSI320X9cbYIDJFEOQ[256];
typedef Thread_T9cLzsvk8o9b7NIZJCAgybKw TY_HrszqxUfcUHPydTmjRZfRg[32];
typedef Worker_AqHEWWcw2VBFjoa2Hp8Akw TY_W9bX58rb2TvIPS9bAprPBVQg[32];
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Threadpoolstate_jN9benzGjAA9bryIHC1FGnZA  {
NI calls;
};
typedef NU8 Threadpooladvice_vD9cAMuSmfH29a9al5Q9cUZCig;
N_NIMCALL(void, initsemaphore_9czoqdg4eHIgtJ4wssK5YHA)(Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv0);
static N_INLINE(void, initcond_WRFSiAr3z0qoVkqr9c7EaqQlocks)(pthread_cond_t* cond0);
static N_INLINE(void, initlock_NXoRcxfV39aV9cflSTUwtJ1glocks)(pthread_mutex_t* lock0);
static N_INLINE(void, destroysemaphore_ZRg3Z8DVlD9bBm5kQEOnV7Qthreadpool)(Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv0);
static N_INLINE(void, deinitcond_WRFSiAr3z0qoVkqr9c7EaqQ_2locks)(pthread_cond_t* cond0);
static N_INLINE(void, deinitlock_NXoRcxfV39aV9cflSTUwtJ1g_2locks)(pthread_mutex_t* lock0);
N_NIMCALL(void, await_9czoqdg4eHIgtJ4wssK5YHA_2)(Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv0);
N_NIMCALL(void, acquire_9bBEZeGCRkWQl9bLT1qt423Q)(pthread_mutex_t* lock0);
static N_INLINE(void, wait_C8C25W9c9aLsapjtr1flPecglocks)(pthread_cond_t* cond0, pthread_mutex_t* lock0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, release_9bBEZeGCRkWQl9bLT1qt423Q_2)(pthread_mutex_t* lock0);
N_NIMCALL(void, signal_9czoqdg4eHIgtJ4wssK5YHA_3)(Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
static N_INLINE(void, signal_WRFSiAr3z0qoVkqr9c7EaqQ_3locks)(pthread_cond_t* cond0);
static N_INLINE(void, barrierEnter)(Barrier* b0);
static N_INLINE(void, barrierLeave)(Barrier* b0);
static N_INLINE(NI, atomicinc_4E9cxwuunx9aiL7vj9bdy8WvAsystem)(NI* memloc0, NI x0);
static N_INLINE(void, openBarrier)(Barrier* b0);
N_NIMCALL(void, closeBarrier)(Barrier* b0);
N_NIMCALL(void, await_v7HeuUBcnpz8vQGjcNl2Zg)(Flowvarbaseobj_CJfwFDAb1ST4bu6G9bMAYbg* fv0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NIM_BOOL, selectworker_BW1ODxSJ4rN4KmfdYS8AFw)(Worker_AqHEWWcw2VBFjoa2Hp8Akw* w0, TY_fhqfcnDhIcLpBpSTVsWEZg fn0, void* data0);
N_NIMCALL(void, cleanflowvars_YsEpsvk4M2H0cFOPo7KYiA)(Worker_AqHEWWcw2VBFjoa2Hp8Akw* w0);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, nimGCunref)(void* p0);
N_NIMCALL(void, wakeupworkertoprocessqueue_YsEpsvk4M2H0cFOPo7KYiA_2)(Worker_AqHEWWcw2VBFjoa2Hp8Akw* w0);
static N_INLINE(void, cpurelax_IZ2oOmqdsYQ7vixQGKSDcA_2system)(void);
N_NIMCALL(void, HEX3Aanonymous_RN9c4f80Dl8mVIo1K9bSACqA)(void* w_S8sjzrxLhixyPVfrdtSX0Q, void* a0);
N_NIMCALL(void, finished_v7HeuUBcnpz8vQGjcNl2Zg_2)(Flowvarbaseobj_CJfwFDAb1ST4bu6G9bMAYbg* fv0);
N_NOINLINE(void, raiseassert_PpfSiTIeNpMAb9a5o6SglJw_2)(NimStringDesc* msg0);
N_NIMCALL(void, nimFlowVarCreateSemaphore)(Flowvarbaseobj_CJfwFDAb1ST4bu6G9bMAYbg* fv0);
N_NIMCALL(void, nimFlowVarSignal)(Flowvarbaseobj_CJfwFDAb1ST4bu6G9bMAYbg* fv0);
N_NIMCALL(NI, awaitany_vcBumXfLEGmomLN3bbmA5w)(Flowvarbaseobj_CJfwFDAb1ST4bu6G9bMAYbg** flowvars0, NI flowvars0Len0);
N_NIMCALL(NIM_BOOL, isready_k9cvjOLQv59bGjlW9ar7G4pOQ)(Flowvarbaseobj_CJfwFDAb1ST4bu6G9bMAYbg* fv0);
N_NIMCALL(void, nimArgsPassingDone)(void* p0);
N_NIMCALL(void, slave_ZLEiMrITYl7xqyEhA5iC1g)(Worker_AqHEWWcw2VBFjoa2Hp8Akw* w0);
N_NIMCALL(void, failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg0);
static N_INLINE(void, pushSafePoint)(TSafePoint* s0);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s0);
N_NIMCALL(void, reraiseException)(void);
static N_INLINE(NI, atomicdec_4E9cxwuunx9aiL7vj9bdy8WvA_2system)(NI* memloc0, NI x0);
N_NIMCALL(void, distinguishedslave_ZLEiMrITYl7xqyEhA5iC1g_2)(Worker_AqHEWWcw2VBFjoa2Hp8Akw* w0);
N_NIMCALL(void, setminpoolsize_i9c9c5F2sCRS4GypusVk8uIQ)(NI size0);
N_NIMCALL(void, setmaxpoolsize_i9c9c5F2sCRS4GypusVk8uIQ_2)(NI size0);
N_NIMCALL(void, createthread_Gg58sihoqa0UVgbqgCx9ctg)(Thread_T9cLzsvk8o9b7NIZJCAgybKw* t0, TY_nSqh6BBL9cSEu9bcR48Z72QA tp0, Worker_AqHEWWcw2VBFjoa2Hp8Akw* param0);
N_NOCONV(void*, threadprocwrapper_2AvjU29bJvs3FXJIcnmn4Kg)(void* closure0);
N_NIMCALL(void, threadprocwrapstackframe_39cRfNSawi9bXoVeZQCbx9cFw)(Thread_T9cLzsvk8o9b7NIZJCAgybKw* thrd0);
N_NIMCALL(void, threadprocwrapdispatch_9cCfbKEO7gGzRZFzD49bUvyQ)(Thread_T9cLzsvk8o9b7NIZJCAgybKw* thrd0);
N_NOINLINE(void, activateworkerthread_gZGpMQ9anM43sp7cjLJQjLg)(NI i0);
N_NOINLINE(void, activatedistinguishedthread_gZGpMQ9anM43sp7cjLJQjLg_2)(NI i0);
N_NIMCALL(void, setup_p4oO1XgRwu6WxNojgsXntg)(void);
N_NIMCALL(NI, ncpicountProcessors)(void);
N_NIMCALL(NIM_BOOL, preferspawn_Jvod3sf15qssvdMH82j5dg)(void);
N_NIMCALL(void, nimSpawn3)(TY_fhqfcnDhIcLpBpSTVsWEZg fn0, void* data0);
N_NIMCALL(NIM_BOOL, tryacquire_RVpMCi0dWU5mH1GyAP2R5w)(pthread_mutex_t* lock0);
N_NIMCALL(Threadpooladvice_vD9cAMuSmfH29a9al5Q9cUZCig, advice_uXlfLohkC9aBvpzhcIrG9amw)(Threadpoolstate_jN9benzGjAA9bryIHC1FGnZA* s0);
N_NIMCALL(void, nimSpawn4)(TY_fhqfcnDhIcLpBpSTVsWEZg fn0, void* data0, NI id0);
N_NIMCALL(void, sync_p4oO1XgRwu6WxNojgsXntg_2)(void);
extern NIM_THREADVAR TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NI currentpoolsize_ErccdOg9batM6rAb3hYbfxA;
NI maxpoolsize_I5gWiq7COu2xfOvex9aGTWw;
NI minpoolsize_L9a7W9byTjVXeXKRg5OtqNTg;
Semaphore_sx9abLHOwgGDBH9bpoqw2ezw gsomeready_RyUdpNfPQUpKmQaHtWHYoA;
Worker_AqHEWWcw2VBFjoa2Hp8Akw* readyworker_BT69aUhVoxO4qq9b8EinSVNA;
pthread_mutex_t numslaveslock_WtiE83BZa1NBG7G2g8ZnmA;
NI numslavesrunning_ptIe6dS9bOnWPjIrLSfTasw;
NI numslaveswaiting_fTOoJ83E0W3d2BkhxhQFwg;
NIM_THREADVAR NIM_BOOL isslave_t9a8wsVVRYqGEKhg1vb49b3g;
extern NIM_THREADVAR TSafePoint* exchandler_rqLlY5bs9atDw2OXYqJEn5g;
TY_t64oTbxGYdi34RY7u0jpWg workers_bezHuru9a1bEti2XBmfodvA;
TY_5sGw9aMSI320X9cbYIDJFEOQ workersdata_R5YxoJYCt3PvKeJGhluUDQ;
TY_HrszqxUfcUHPydTmjRZfRg distinguished_PEEgL9bODGVNNubj61abNQA;
TY_W9bX58rb2TvIPS9bAprPBVQg distinguisheddata_Lqsi7ieuVktaO9acMSZyorQ;
TNimType NTI_AqHEWWcw2VBFjoa2Hp8Akw;
TNimType NTI_sx9abLHOwgGDBH9bpoqw2ezw;
extern TNimType NTI_9bK5SEAqe27K49aDtonge9aQg;
extern TNimType NTI_lsB6JckQ3csMuiRW476VWg;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA;
TNimType NTI_fhqfcnDhIcLpBpSTVsWEZg;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ;
TNimType NTI_5COJP8EWIaAuXvZlDbQZmw;
TNimType NTI_2PWyF6nokyTyhzmcY3ON3w;
TNimType NTI_CyNApV6Mfiphj5eUnH5G1A;
Threadpoolstate_jN9benzGjAA9bryIHC1FGnZA state_7PVqgO4qfT36l9bZ9a9cqhD9bA;
pthread_mutex_t statelock_Of3qxka1C2uLE9anKCj52kA;
pthread_mutex_t distinguishedlock_lPmqsqhMalxIWA0zwhlpFg;
STRING_LITERAL(T_Qzgg5NBLvccay07XFph3Rw_6, "isNil(fv.ai) flowVar is still attached to an \'awaitAny\'", 55);
STRING_LITERAL(T_Qzgg5NBLvccay07XFph3Rw_12, "not w.ready ", 12);

static N_INLINE(void, initcond_WRFSiAr3z0qoVkqr9c7EaqQlocks)(pthread_cond_t* cond0) {
	pthread_cond_init(cond0, NIM_NIL);
}

static N_INLINE(void, initlock_NXoRcxfV39aV9cflSTUwtJ1glocks)(pthread_mutex_t* lock0) {
	pthread_mutex_init(lock0, NIM_NIL);
}

N_NIMCALL(void, initsemaphore_9czoqdg4eHIgtJ4wssK5YHA)(Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv0) {
	initcond_WRFSiAr3z0qoVkqr9c7EaqQlocks((&(*cv0).c));
	initlock_NXoRcxfV39aV9cflSTUwtJ1glocks((&(*cv0).L));
}

static N_INLINE(void, deinitcond_WRFSiAr3z0qoVkqr9c7EaqQ_2locks)(pthread_cond_t* cond0) {
	pthread_cond_destroy(cond0);
}

static N_INLINE(void, deinitlock_NXoRcxfV39aV9cflSTUwtJ1g_2locks)(pthread_mutex_t* lock0) {
	pthread_mutex_destroy(lock0);
}

static N_INLINE(void, destroysemaphore_ZRg3Z8DVlD9bBm5kQEOnV7Qthreadpool)(Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv0) {
	deinitcond_WRFSiAr3z0qoVkqr9c7EaqQ_2locks((&(*cv0).c));
	deinitlock_NXoRcxfV39aV9cflSTUwtJ1g_2locks((&(*cv0).L));
}

static N_INLINE(void, wait_C8C25W9c9aLsapjtr1flPecglocks)(pthread_cond_t* cond0, pthread_mutex_t* lock0) {
	pthread_cond_wait(cond0, lock0);
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, await_9czoqdg4eHIgtJ4wssK5YHA_2)(Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv0) {
	NI T_Qzgg5NBLvccay07XFph3Rw_2;
	acquire_9bBEZeGCRkWQl9bLT1qt423Q((&(*cv0).L));
	{
		while (1) {
			if (!((*cv0).counter <= ((NI) 0))) goto LA2;
			wait_C8C25W9c9aLsapjtr1flPecglocks((&(*cv0).c), (&(*cv0).L));
		} LA2: ;
	}
	T_Qzgg5NBLvccay07XFph3Rw_2 = subInt((*cv0).counter, ((NI) 1));
	(*cv0).counter = (NI)(T_Qzgg5NBLvccay07XFph3Rw_2);
	release_9bBEZeGCRkWQl9bLT1qt423Q_2((&(*cv0).L));
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, signal_WRFSiAr3z0qoVkqr9c7EaqQ_3locks)(pthread_cond_t* cond0) {
	pthread_cond_signal(cond0);
}

N_NIMCALL(void, signal_9czoqdg4eHIgtJ4wssK5YHA_3)(Semaphore_sx9abLHOwgGDBH9bpoqw2ezw* cv0) {
	NI T_Qzgg5NBLvccay07XFph3Rw_3;
	acquire_9bBEZeGCRkWQl9bLT1qt423Q((&(*cv0).L));
	T_Qzgg5NBLvccay07XFph3Rw_3 = addInt((*cv0).counter, ((NI) 1));
	(*cv0).counter = (NI)(T_Qzgg5NBLvccay07XFph3Rw_3);
	release_9bBEZeGCRkWQl9bLT1qt423Q_2((&(*cv0).L));
	signal_WRFSiAr3z0qoVkqr9c7EaqQ_3locks((&(*cv0).c));
}

static N_INLINE(void, barrierEnter)(Barrier* b0) {
	NI T_Qzgg5NBLvccay07XFph3Rw_4;
	T_Qzgg5NBLvccay07XFph3Rw_4 = addInt((*b0).entered, ((NI) 1));
	(*b0).entered = (NI)(T_Qzgg5NBLvccay07XFph3Rw_4);
}

static N_INLINE(NI, atomicinc_4E9cxwuunx9aiL7vj9bdy8WvAsystem)(NI* memloc0, NI x0) {
	NI result0;
	result0 = (NI)0;
	result0 = __atomic_add_fetch(memloc0, x0, __ATOMIC_RELAXED);
	return result0;
}

static N_INLINE(void, barrierLeave)(Barrier* b0) {
	NI LOC1;
	LOC1 = (NI)0;
	LOC1 = atomicinc_4E9cxwuunx9aiL7vj9bdy8WvAsystem((&(*b0).left), ((NI) 1));
	__atomic_thread_fence(__ATOMIC_SEQ_CST);
	{
		NIM_BOOL LOC4;
		LOC4 = (NIM_BOOL)0;
		LOC4 = (*b0).interest;
		if (!(LOC4)) goto LA5;
		LOC4 = ((*b0).entered <= (*b0).left);
		LA5: ;
		if (!LOC4) goto LA6;
		signal_9czoqdg4eHIgtJ4wssK5YHA_3((&(*b0).cv));
	}
	LA6: ;
}

static N_INLINE(void, openBarrier)(Barrier* b0) {
	(*b0).entered = ((NI) 0);
	(*b0).left = ((NI) 0);
	(*b0).interest = NIM_FALSE;
}

N_NIMCALL(void, closeBarrier)(Barrier* b0) {
	__atomic_thread_fence(__ATOMIC_SEQ_CST);
	{
		if (!!(((*b0).left == (*b0).entered))) goto LA3;
		initsemaphore_9czoqdg4eHIgtJ4wssK5YHA((&(*b0).cv));
		__atomic_thread_fence(__ATOMIC_SEQ_CST);
		(*b0).interest = NIM_TRUE;
		__atomic_thread_fence(__ATOMIC_SEQ_CST);
		{
			while (1) {
				if (!!(((*b0).left == (*b0).entered))) goto LA6;
				await_9czoqdg4eHIgtJ4wssK5YHA_2((&(*b0).cv));
			} LA6: ;
		}
		destroysemaphore_ZRg3Z8DVlD9bBm5kQEOnV7Qthreadpool((&(*b0).cv));
	}
	LA3: ;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, await_v7HeuUBcnpz8vQGjcNl2Zg)(Flowvarbaseobj_CJfwFDAb1ST4bu6G9bMAYbg* fv0) {
	nimfr("await", "threadpool.nim")
	nimln(136, "threadpool.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (*fv0).usessemaphore;
		if (!(LOC3)) goto LA4;
		LOC3 = !((*fv0).awaited);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(137, "threadpool.nim");
		(*fv0).awaited = NIM_TRUE;
		nimln(138, "threadpool.nim");
		await_9czoqdg4eHIgtJ4wssK5YHA_2((&(*fv0).cv));
		nimln(139, "threadpool.nim");
		destroysemaphore_ZRg3Z8DVlD9bBm5kQEOnV7Qthreadpool((&(*fv0).cv));
	}
	LA5: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, selectworker_BW1ODxSJ4rN4KmfdYS8AFw)(Worker_AqHEWWcw2VBFjoa2Hp8Akw* w0, TY_fhqfcnDhIcLpBpSTVsWEZg fn0, void* data0) {
	NIM_BOOL result0;
	nimfr("selectWorker", "threadpool.nim")
	result0 = (NIM_BOOL)0;
	nimln(142, "threadpool.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = __sync_bool_compare_and_swap((&(*w0).ready), NIM_TRUE, NIM_FALSE);
		if (!LOC3) goto LA4;
		nimln(143, "threadpool.nim");
		(*w0).data = data0;
		nimln(144, "threadpool.nim");
		(*w0).f = fn0;
		nimln(145, "threadpool.nim");
		signal_9czoqdg4eHIgtJ4wssK5YHA_3((&(*w0).taskarrived));
		nimln(146, "threadpool.nim");
		await_9czoqdg4eHIgtJ4wssK5YHA_2((&(*w0).taskstarted));
		nimln(147, "threadpool.nim");
		result0 = NIM_TRUE;
	}
	LA4: ;
	popFrame();
	return result0;
}

N_NIMCALL(void, cleanflowvars_YsEpsvk4M2H0cFOPo7KYiA)(Worker_AqHEWWcw2VBFjoa2Hp8Akw* w0) {
	Tofreequeue_5COJP8EWIaAuXvZlDbQZmw* q0;
	nimfr("cleanFlowVars", "threadpool.nim")
	nimln(150, "threadpool.nim");
	q0 = (&(*w0).q);
	nimln(151, "threadpool.nim");
	acquire_9bBEZeGCRkWQl9bLT1qt423Q((&(*q0).lock));
	{
		NI i_MsxJEFuIRjHznn49cDmcY7g;
		NI HEX3Atmp_8mzcEb9cTJOMrZAElS8y8qQ;
		NI res_14Uxue716w7RKwMsr9bOa1g;
		i_MsxJEFuIRjHznn49cDmcY7g = (NI)0;
		HEX3Atmp_8mzcEb9cTJOMrZAElS8y8qQ = (NI)0;
		nimln(152, "threadpool.nim");
		HEX3Atmp_8mzcEb9cTJOMrZAElS8y8qQ = subInt((*q0).len, 1);
		nimln(1908, "system.nim");
		res_14Uxue716w7RKwMsr9bOa1g = ((NI) 0);
		{
			nimln(1909, "system.nim");
			while (1) {
				NI T_Qzgg5NBLvccay07XFph3Rw_5;
				nimln(1908, "system.nim");
				if (!(res_14Uxue716w7RKwMsr9bOa1g <= HEX3Atmp_8mzcEb9cTJOMrZAElS8y8qQ)) goto LA3;
				nimln(1910, "system.nim");
				i_MsxJEFuIRjHznn49cDmcY7g = res_14Uxue716w7RKwMsr9bOa1g;
				nimln(153, "threadpool.nim");
				if ((NU)(i_MsxJEFuIRjHznn49cDmcY7g) > (NU)(127)) raiseIndexError();
				nimGCunref(((TNimObject*) ((*q0).data[(i_MsxJEFuIRjHznn49cDmcY7g)- 0])));
				nimln(1908, "system.nim");
				T_Qzgg5NBLvccay07XFph3Rw_5 = addInt(res_14Uxue716w7RKwMsr9bOa1g, ((NI) 1));
				res_14Uxue716w7RKwMsr9bOa1g = (NI)(T_Qzgg5NBLvccay07XFph3Rw_5);
			} LA3: ;
		}
	}
	nimln(155, "threadpool.nim");
	(*q0).len = ((NI) 0);
	nimln(156, "threadpool.nim");
	release_9bBEZeGCRkWQl9bLT1qt423Q_2((&(*q0).lock));
	popFrame();
}

static N_INLINE(void, cpurelax_IZ2oOmqdsYQ7vixQGKSDcA_2system)(void) {
	asm volatile("pause" ::: "memory");
}

N_NIMCALL(void, HEX3Aanonymous_RN9c4f80Dl8mVIo1K9bSACqA)(void* w_S8sjzrxLhixyPVfrdtSX0Q, void* a0) {
	Worker_AqHEWWcw2VBFjoa2Hp8Akw* w0;
	nimfr(":anonymous", "threadpool.nim")
	nimln(166, "threadpool.nim");
	w0 = ((Worker_AqHEWWcw2VBFjoa2Hp8Akw*) (w_S8sjzrxLhixyPVfrdtSX0Q));
	nimln(167, "threadpool.nim");
	cleanflowvars_YsEpsvk4M2H0cFOPo7KYiA(w0);
	nimln(168, "threadpool.nim");
	signal_9czoqdg4eHIgtJ4wssK5YHA_3((&(*w0).q.empty));
	popFrame();
}

N_NIMCALL(void, wakeupworkertoprocessqueue_YsEpsvk4M2H0cFOPo7KYiA_2)(Worker_AqHEWWcw2VBFjoa2Hp8Akw* w0) {
	nimfr("wakeupWorkerToProcessQueue", "threadpool.nim")
	{
		nimln(161, "threadpool.nim");
		while (1) {
			NIM_BOOL LOC3;
			LOC3 = (NIM_BOOL)0;
			LOC3 = __sync_bool_compare_and_swap((&(*w0).ready), NIM_TRUE, NIM_FALSE);
			if (!!(LOC3)) goto LA2;
			nimln(162, "threadpool.nim");
			cpurelax_IZ2oOmqdsYQ7vixQGKSDcA_2system();
		} LA2: ;
	}
	nimln(164, "threadpool.nim");
	(*w0).data = NIM_NIL;
	nimln(165, "threadpool.nim");
	(*w0).f = HEX3Aanonymous_RN9c4f80Dl8mVIo1K9bSACqA;
	nimln(169, "threadpool.nim");
	signal_9czoqdg4eHIgtJ4wssK5YHA_3((&(*w0).taskarrived));
	popFrame();
}

N_NIMCALL(void, finished_v7HeuUBcnpz8vQGjcNl2Zg_2)(Flowvarbaseobj_CJfwFDAb1ST4bu6G9bMAYbg* fv0) {
	Worker_AqHEWWcw2VBFjoa2Hp8Akw* owner0;
	Tofreequeue_5COJP8EWIaAuXvZlDbQZmw* q0;
	NI T_Qzgg5NBLvccay07XFph3Rw_7;
	nimfr("finished", "threadpool.nim")
{	nimln(172, "threadpool.nim");
	{
		if (!!(((*fv0).ai == 0))) goto LA3;
		raiseassert_PpfSiTIeNpMAb9a5o6SglJw_2(((NimStringDesc*) &T_Qzgg5NBLvccay07XFph3Rw_6));
	}
	LA3: ;
	nimln(176, "threadpool.nim");
	await_v7HeuUBcnpz8vQGjcNl2Zg(fv0);
	nimln(177, "threadpool.nim");
	{
		if (!((*fv0).data == 0)) goto LA7;
		goto BeforeRet;
	}
	LA7: ;
	nimln(178, "threadpool.nim");
	owner0 = ((Worker_AqHEWWcw2VBFjoa2Hp8Akw*) ((*fv0).owner));
	nimln(179, "threadpool.nim");
	q0 = (&(*owner0).q);
	nimln(180, "threadpool.nim");
	acquire_9bBEZeGCRkWQl9bLT1qt423Q((&(*q0).lock));
	{
		nimln(181, "threadpool.nim");
		while (1) {
			if (!!(((*q0).len < ((NI) 128)))) goto LA10;
			nimln(183, "threadpool.nim");
			release_9bBEZeGCRkWQl9bLT1qt423Q_2((&(*q0).lock));
			nimln(184, "threadpool.nim");
			wakeupworkertoprocessqueue_YsEpsvk4M2H0cFOPo7KYiA_2(owner0);
			nimln(185, "threadpool.nim");
			await_9czoqdg4eHIgtJ4wssK5YHA_2((&(*q0).empty));
			nimln(186, "threadpool.nim");
			acquire_9bBEZeGCRkWQl9bLT1qt423Q((&(*q0).lock));
		} LA10: ;
	}
	nimln(187, "threadpool.nim");
	if ((NU)((*q0).len) > (NU)(127)) raiseIndexError();
	(*q0).data[((*q0).len)- 0] = ((void*) ((*fv0).data));
	nimln(188, "threadpool.nim");
	T_Qzgg5NBLvccay07XFph3Rw_7 = addInt((*q0).len, ((NI) 1));
	(*q0).len = (NI)(T_Qzgg5NBLvccay07XFph3Rw_7);
	nimln(189, "threadpool.nim");
	release_9bBEZeGCRkWQl9bLT1qt423Q_2((&(*q0).lock));
	nimln(190, "threadpool.nim");
	(*fv0).data = NIM_NIL;
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, nimFlowVarCreateSemaphore)(Flowvarbaseobj_CJfwFDAb1ST4bu6G9bMAYbg* fv0) {
	nimfr("nimFlowVarCreateSemaphore", "threadpool.nim")
	nimln(198, "threadpool.nim");
	initsemaphore_9czoqdg4eHIgtJ4wssK5YHA((&(*fv0).cv));
	nimln(199, "threadpool.nim");
	(*fv0).usessemaphore = NIM_TRUE;
	popFrame();
}

N_NIMCALL(void, nimFlowVarSignal)(Flowvarbaseobj_CJfwFDAb1ST4bu6G9bMAYbg* fv0) {
	nimfr("nimFlowVarSignal", "threadpool.nim")
	nimln(202, "threadpool.nim");
	{
		NI T_Qzgg5NBLvccay07XFph3Rw_8;
		nimln(347, "system.nim");
		nimln(202, "threadpool.nim");
		if (!!(((*fv0).ai == NIM_NIL))) goto LA3;
		nimln(203, "threadpool.nim");
		acquire_9bBEZeGCRkWQl9bLT1qt423Q((&(*(*fv0).ai).cv.L));
		nimln(204, "threadpool.nim");
		(*(*fv0).ai).idx = (*fv0).idx;
		nimln(205, "threadpool.nim");
		T_Qzgg5NBLvccay07XFph3Rw_8 = addInt((*(*fv0).ai).cv.counter, ((NI) 1));
		(*(*fv0).ai).cv.counter = (NI)(T_Qzgg5NBLvccay07XFph3Rw_8);
		nimln(206, "threadpool.nim");
		release_9bBEZeGCRkWQl9bLT1qt423Q_2((&(*(*fv0).ai).cv.L));
		nimln(207, "threadpool.nim");
		signal_WRFSiAr3z0qoVkqr9c7EaqQ_3locks((&(*(*fv0).ai).cv.c));
	}
	LA3: ;
	nimln(208, "threadpool.nim");
	{
		if (!(*fv0).usessemaphore) goto LA7;
		nimln(209, "threadpool.nim");
		signal_9czoqdg4eHIgtJ4wssK5YHA_3((&(*fv0).cv));
	}
	LA7: ;
	popFrame();
}

N_NIMCALL(NI, awaitany_vcBumXfLEGmomLN3bbmA5w)(Flowvarbaseobj_CJfwFDAb1ST4bu6G9bMAYbg** flowvars0, NI flowvars0Len0) {
	NI result0;
	Awaitinfo_InuzBj4ASNnb8C8ZpRzfbA ai0;
	NI conflicts0;
	nimfr("awaitAny", "threadpool.nim")
	result0 = (NI)0;
	memset((void*)(&ai0), 0, sizeof(ai0));
	nimln(254, "threadpool.nim");
	initsemaphore_9czoqdg4eHIgtJ4wssK5YHA((&ai0.cv));
	nimln(255, "threadpool.nim");
	conflicts0 = ((NI) 0);
	{
		NI i_a37CzOxFjrSOYasLDaS81Q;
		NI HEX3Atmp_krfZLZj7GAAiBq2Z2hHw4w;
		NI res_th1QrAns9b2wampMp7qbV2g;
		i_a37CzOxFjrSOYasLDaS81Q = (NI)0;
		HEX3Atmp_krfZLZj7GAAiBq2Z2hHw4w = (NI)0;
		nimln(256, "threadpool.nim");
		HEX3Atmp_krfZLZj7GAAiBq2Z2hHw4w = (flowvars0Len0-1);
		nimln(1908, "system.nim");
		res_th1QrAns9b2wampMp7qbV2g = ((NI) 0);
		{
			nimln(1909, "system.nim");
			while (1) {
				NI T_Qzgg5NBLvccay07XFph3Rw_10;
				nimln(1908, "system.nim");
				if (!(res_th1QrAns9b2wampMp7qbV2g <= HEX3Atmp_krfZLZj7GAAiBq2Z2hHw4w)) goto LA3;
				nimln(1910, "system.nim");
				i_a37CzOxFjrSOYasLDaS81Q = res_th1QrAns9b2wampMp7qbV2g;
				nimln(257, "threadpool.nim");
				{
					NIM_BOOL LOC6;
					if ((NU)(i_a37CzOxFjrSOYasLDaS81Q) >= (NU)(flowvars0Len0)) raiseIndexError();
					LOC6 = (NIM_BOOL)0;
					LOC6 = __sync_bool_compare_and_swap(&(*flowvars0[i_a37CzOxFjrSOYasLDaS81Q]).ai, NIM_NIL, (&ai0));
					if (!LOC6) goto LA7;
					nimln(258, "threadpool.nim");
					if ((NU)(i_a37CzOxFjrSOYasLDaS81Q) >= (NU)(flowvars0Len0)) raiseIndexError();
					(*flowvars0[i_a37CzOxFjrSOYasLDaS81Q]).idx = i_a37CzOxFjrSOYasLDaS81Q;
				}
				goto LA4;
				LA7: ;
				{
					NI T_Qzgg5NBLvccay07XFph3Rw_9;
					nimln(260, "threadpool.nim");
					T_Qzgg5NBLvccay07XFph3Rw_9 = addInt(conflicts0, ((NI) 1));
					conflicts0 = (NI)(T_Qzgg5NBLvccay07XFph3Rw_9);
				}
				LA4: ;
				nimln(1908, "system.nim");
				T_Qzgg5NBLvccay07XFph3Rw_10 = addInt(res_th1QrAns9b2wampMp7qbV2g, ((NI) 1));
				res_th1QrAns9b2wampMp7qbV2g = (NI)(T_Qzgg5NBLvccay07XFph3Rw_10);
			} LA3: ;
		}
	}
	nimln(261, "threadpool.nim");
	{
		if (!(conflicts0 < flowvars0Len0)) goto LA12;
		nimln(262, "threadpool.nim");
		await_9czoqdg4eHIgtJ4wssK5YHA_2((&ai0.cv));
		nimln(263, "threadpool.nim");
		result0 = ai0.idx;
		{
			NI i_a37CzOxFjrSOYasLDaS81Q_2;
			NI HEX3Atmp_krfZLZj7GAAiBq2Z2hHw4w_2;
			NI res_th1QrAns9b2wampMp7qbV2g_2;
			i_a37CzOxFjrSOYasLDaS81Q_2 = (NI)0;
			HEX3Atmp_krfZLZj7GAAiBq2Z2hHw4w_2 = (NI)0;
			nimln(264, "threadpool.nim");
			HEX3Atmp_krfZLZj7GAAiBq2Z2hHw4w_2 = (flowvars0Len0-1);
			nimln(1908, "system.nim");
			res_th1QrAns9b2wampMp7qbV2g_2 = ((NI) 0);
			{
				nimln(1909, "system.nim");
				while (1) {
					NIM_BOOL LOC17;
					NI T_Qzgg5NBLvccay07XFph3Rw_11;
					nimln(1908, "system.nim");
					if (!(res_th1QrAns9b2wampMp7qbV2g_2 <= HEX3Atmp_krfZLZj7GAAiBq2Z2hHw4w_2)) goto LA16;
					nimln(1910, "system.nim");
					i_a37CzOxFjrSOYasLDaS81Q_2 = res_th1QrAns9b2wampMp7qbV2g_2;
					nimln(265, "threadpool.nim");
					if ((NU)(i_a37CzOxFjrSOYasLDaS81Q_2) >= (NU)(flowvars0Len0)) raiseIndexError();
					LOC17 = (NIM_BOOL)0;
					LOC17 = __sync_bool_compare_and_swap(&(*flowvars0[i_a37CzOxFjrSOYasLDaS81Q_2]).ai, (&ai0), NIM_NIL);
					nimln(1908, "system.nim");
					T_Qzgg5NBLvccay07XFph3Rw_11 = addInt(res_th1QrAns9b2wampMp7qbV2g_2, ((NI) 1));
					res_th1QrAns9b2wampMp7qbV2g_2 = (NI)(T_Qzgg5NBLvccay07XFph3Rw_11);
				} LA16: ;
			}
		}
	}
	goto LA10;
	LA12: ;
	{
		nimln(267, "threadpool.nim");
		result0 = ((NI) -1);
	}
	LA10: ;
	nimln(268, "threadpool.nim");
	destroysemaphore_ZRg3Z8DVlD9bBm5kQEOnV7Qthreadpool((&ai0.cv));
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, isready_k9cvjOLQv59bGjlW9ar7G4pOQ)(Flowvarbaseobj_CJfwFDAb1ST4bu6G9bMAYbg* fv0) {
	NIM_BOOL result0;
	nimfr("isReady", "threadpool.nim")
	result0 = (NIM_BOOL)0;
	nimln(274, "threadpool.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (*fv0).usessemaphore;
		if (!(LOC3)) goto LA4;
		LOC3 = !((*fv0).awaited);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(275, "threadpool.nim");
		acquire_9bBEZeGCRkWQl9bLT1qt423Q((&(*fv0).cv.L));
		nimln(276, "threadpool.nim");
		result0 = (((NI) 0) < (*fv0).cv.counter);
		nimln(277, "threadpool.nim");
		release_9bBEZeGCRkWQl9bLT1qt423Q_2((&(*fv0).cv.L));
	}
	goto LA1;
	LA5: ;
	{
		nimln(279, "threadpool.nim");
		result0 = NIM_TRUE;
	}
	LA1: ;
	popFrame();
	return result0;
}

N_NIMCALL(void, nimArgsPassingDone)(void* p0) {
	Worker_AqHEWWcw2VBFjoa2Hp8Akw* w0;
	nimfr("nimArgsPassingDone", "threadpool.nim")
	nimln(282, "threadpool.nim");
	w0 = ((Worker_AqHEWWcw2VBFjoa2Hp8Akw*) (p0));
	nimln(283, "threadpool.nim");
	signal_9czoqdg4eHIgtJ4wssK5YHA_3((&(*w0).taskstarted));
	popFrame();
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s0) {
	(*s0).hasRaiseAction = NIM_FALSE;
	(*s0).prev = exchandler_rqLlY5bs9atDw2OXYqJEn5g;
	exchandler_rqLlY5bs9atDw2OXYqJEn5g = s0;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_rqLlY5bs9atDw2OXYqJEn5g = (*exchandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s0) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
}

static N_INLINE(NI, atomicdec_4E9cxwuunx9aiL7vj9bdy8WvA_2system)(NI* memloc0, NI x0) {
	NI result0;
	result0 = (NI)0;
	result0 = __atomic_sub_fetch(memloc0, x0, __ATOMIC_RELAXED);
	return result0;
}

N_NIMCALL(void, slave_ZLEiMrITYl7xqyEhA5iC1g)(Worker_AqHEWWcw2VBFjoa2Hp8Akw* w0) {
	nimfr("slave", "threadpool.nim")
	nimln(313, "threadpool.nim");
	isslave_t9a8wsVVRYqGEKhg1vb49b3g = NIM_TRUE;
	{
		nimln(314, "threadpool.nim");
		while (1) {
			TSafePoint T_Qzgg5NBLvccay07XFph3Rw_13;
			TSafePoint T_Qzgg5NBLvccay07XFph3Rw_15;
			nimln(316, "threadpool.nim");
			__atomic_store_n((&(*w0).ready), NIM_TRUE, __ATOMIC_SEQ_CST);
			nimln(319, "threadpool.nim");
			readyworker_BT69aUhVoxO4qq9b8EinSVNA = w0;
			nimln(320, "threadpool.nim");
			signal_9czoqdg4eHIgtJ4wssK5YHA_3((&gsomeready_RyUdpNfPQUpKmQaHtWHYoA));
			nimln(321, "threadpool.nim");
			await_9czoqdg4eHIgtJ4wssK5YHA_2((&(*w0).taskarrived));
			nimln(324, "threadpool.nim");
			{
				if (!!(!((*w0).ready))) goto LA5;
				failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &T_Qzgg5NBLvccay07XFph3Rw_12));
			}
			LA5: ;
			nimln(326, "threadpool.nim");
			acquire_9bBEZeGCRkWQl9bLT1qt423Q((&numslaveslock_WtiE83BZa1NBG7G2g8ZnmA));
			nimln(64, "locks.nim");
			pushSafePoint(&T_Qzgg5NBLvccay07XFph3Rw_13);
			T_Qzgg5NBLvccay07XFph3Rw_13.status = setjmp(T_Qzgg5NBLvccay07XFph3Rw_13.context);
			if (T_Qzgg5NBLvccay07XFph3Rw_13.status == 0) {
				NI T_Qzgg5NBLvccay07XFph3Rw_14;
				nimln(327, "threadpool.nim");
				T_Qzgg5NBLvccay07XFph3Rw_14 = addInt(numslavesrunning_ptIe6dS9bOnWPjIrLSfTasw, ((NI) 1));
				numslavesrunning_ptIe6dS9bOnWPjIrLSfTasw = (NI)(T_Qzgg5NBLvccay07XFph3Rw_14);
				popSafePoint();
			}
			else {
				popSafePoint();
				setFrame((TFrame*)&FR);
			}
			{
				nimln(326, "threadpool.nim");
				release_9bBEZeGCRkWQl9bLT1qt423Q_2((&numslaveslock_WtiE83BZa1NBG7G2g8ZnmA));
			}
			if (T_Qzgg5NBLvccay07XFph3Rw_13.status != 0) reraiseException();
			nimln(329, "threadpool.nim");
			(*w0).f(((void*) (w0)), (*w0).data);
			nimln(331, "threadpool.nim");
			acquire_9bBEZeGCRkWQl9bLT1qt423Q((&numslaveslock_WtiE83BZa1NBG7G2g8ZnmA));
			nimln(64, "locks.nim");
			pushSafePoint(&T_Qzgg5NBLvccay07XFph3Rw_15);
			T_Qzgg5NBLvccay07XFph3Rw_15.status = setjmp(T_Qzgg5NBLvccay07XFph3Rw_15.context);
			if (T_Qzgg5NBLvccay07XFph3Rw_15.status == 0) {
				NI T_Qzgg5NBLvccay07XFph3Rw_16;
				nimln(332, "threadpool.nim");
				T_Qzgg5NBLvccay07XFph3Rw_16 = subInt(numslavesrunning_ptIe6dS9bOnWPjIrLSfTasw, ((NI) 1));
				numslavesrunning_ptIe6dS9bOnWPjIrLSfTasw = (NI)(T_Qzgg5NBLvccay07XFph3Rw_16);
				popSafePoint();
			}
			else {
				popSafePoint();
				setFrame((TFrame*)&FR);
			}
			{
				nimln(331, "threadpool.nim");
				release_9bBEZeGCRkWQl9bLT1qt423Q_2((&numslaveslock_WtiE83BZa1NBG7G2g8ZnmA));
			}
			if (T_Qzgg5NBLvccay07XFph3Rw_15.status != 0) reraiseException();
			nimln(334, "threadpool.nim");
			{
				nimln(347, "system.nim");
				nimln(334, "threadpool.nim");
				if (!!(((*w0).q.len == ((NI) 0)))) goto LA15;
				cleanflowvars_YsEpsvk4M2H0cFOPo7KYiA(w0);
			}
			LA15: ;
			nimln(335, "threadpool.nim");
			{
				NI LOC21;
				if (!(*w0).shutdown) goto LA19;
				nimln(336, "threadpool.nim");
				(*w0).shutdown = NIM_FALSE;
				nimln(337, "threadpool.nim");
				LOC21 = (NI)0;
				LOC21 = atomicdec_4E9cxwuunx9aiL7vj9bdy8WvA_2system((&currentpoolsize_ErccdOg9batM6rAb3hYbfxA), ((NI) 1));
			}
			LA19: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, distinguishedslave_ZLEiMrITYl7xqyEhA5iC1g_2)(Worker_AqHEWWcw2VBFjoa2Hp8Akw* w0) {
	nimfr("distinguishedSlave", "threadpool.nim")
	{
		nimln(340, "threadpool.nim");
		while (1) {
			nimln(342, "threadpool.nim");
			__atomic_store_n((&(*w0).ready), NIM_TRUE, __ATOMIC_SEQ_CST);
			nimln(345, "threadpool.nim");
			signal_9czoqdg4eHIgtJ4wssK5YHA_3((&(*w0).readyfortask));
			nimln(346, "threadpool.nim");
			await_9czoqdg4eHIgtJ4wssK5YHA_2((&(*w0).taskarrived));
			nimln(347, "threadpool.nim");
			{
				if (!!(!((*w0).ready))) goto LA5;
				failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &T_Qzgg5NBLvccay07XFph3Rw_12));
			}
			LA5: ;
			nimln(348, "threadpool.nim");
			(*w0).f(((void*) (w0)), (*w0).data);
			nimln(349, "threadpool.nim");
			{
				nimln(347, "system.nim");
				nimln(349, "threadpool.nim");
				if (!!(((*w0).q.len == ((NI) 0)))) goto LA9;
				cleanflowvars_YsEpsvk4M2H0cFOPo7KYiA(w0);
			}
			LA9: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, setminpoolsize_i9c9c5F2sCRS4GypusVk8uIQ)(NI size0) {
	nimfr("setMinPoolSize", "threadpool.nim")
	nimln(363, "threadpool.nim");
	minpoolsize_L9a7W9byTjVXeXKRg5OtqNTg = ((NI) (size0));
	popFrame();
}

N_NIMCALL(void, setmaxpoolsize_i9c9c5F2sCRS4GypusVk8uIQ_2)(NI size0) {
	nimfr("setMaxPoolSize", "threadpool.nim")
	nimln(368, "threadpool.nim");
	maxpoolsize_I5gWiq7COu2xfOvex9aGTWw = ((NI) (size0));
	nimln(369, "threadpool.nim");
	{
		if (!(maxpoolsize_I5gWiq7COu2xfOvex9aGTWw < currentpoolsize_ErccdOg9batM6rAb3hYbfxA)) goto LA3;
		{
			NI i_uwssD9aq9cy9b9bK9bsrv2zrF2Q;
			NI HEX3Atmp_r4t2jrT9c6VXY9b4P3ml2v6w;
			NI T_Qzgg5NBLvccay07XFph3Rw_17;
			NI res_qzZk5Ut89at5H2uDpSn3mvg;
			i_uwssD9aq9cy9b9bK9bsrv2zrF2Q = (NI)0;
			HEX3Atmp_r4t2jrT9c6VXY9b4P3ml2v6w = (NI)0;
			nimln(370, "threadpool.nim");
			T_Qzgg5NBLvccay07XFph3Rw_17 = subInt(currentpoolsize_ErccdOg9batM6rAb3hYbfxA, ((NI) 1));
			HEX3Atmp_r4t2jrT9c6VXY9b4P3ml2v6w = (NI)(T_Qzgg5NBLvccay07XFph3Rw_17);
			nimln(1908, "system.nim");
			res_qzZk5Ut89at5H2uDpSn3mvg = maxpoolsize_I5gWiq7COu2xfOvex9aGTWw;
			{
				nimln(1909, "system.nim");
				while (1) {
					Worker_AqHEWWcw2VBFjoa2Hp8Akw* w0;
					NI T_Qzgg5NBLvccay07XFph3Rw_18;
					nimln(1908, "system.nim");
					if (!(res_qzZk5Ut89at5H2uDpSn3mvg <= HEX3Atmp_r4t2jrT9c6VXY9b4P3ml2v6w)) goto LA7;
					nimln(1910, "system.nim");
					i_uwssD9aq9cy9b9bK9bsrv2zrF2Q = res_qzZk5Ut89at5H2uDpSn3mvg;
					nimln(371, "threadpool.nim");
					if ((NU)(i_uwssD9aq9cy9b9bK9bsrv2zrF2Q) > (NU)(255)) raiseIndexError();
					w0 = (&workersdata_R5YxoJYCt3PvKeJGhluUDQ[(i_uwssD9aq9cy9b9bK9bsrv2zrF2Q)- 0]);
					nimln(372, "threadpool.nim");
					(*w0).shutdown = NIM_TRUE;
					nimln(1908, "system.nim");
					T_Qzgg5NBLvccay07XFph3Rw_18 = addInt(res_qzZk5Ut89at5H2uDpSn3mvg, ((NI) 1));
					res_qzZk5Ut89at5H2uDpSn3mvg = (NI)(T_Qzgg5NBLvccay07XFph3Rw_18);
				} LA7: ;
			}
		}
	}
	LA3: ;
	popFrame();
}

N_NOINLINE(void, activateworkerthread_gZGpMQ9anM43sp7cjLJQjLg)(NI i0) {
	nimfr("activateWorkerThread", "threadpool.nim")
	nimln(378, "threadpool.nim");
	if ((NU)(i0) > (NU)(255)) raiseIndexError();
	initsemaphore_9czoqdg4eHIgtJ4wssK5YHA((&workersdata_R5YxoJYCt3PvKeJGhluUDQ[(i0)- 0].taskarrived));
	nimln(379, "threadpool.nim");
	if ((NU)(i0) > (NU)(255)) raiseIndexError();
	initsemaphore_9czoqdg4eHIgtJ4wssK5YHA((&workersdata_R5YxoJYCt3PvKeJGhluUDQ[(i0)- 0].taskstarted));
	nimln(380, "threadpool.nim");
	if ((NU)(i0) > (NU)(255)) raiseIndexError();
	workersdata_R5YxoJYCt3PvKeJGhluUDQ[(i0)- 0].initialized = NIM_TRUE;
	nimln(381, "threadpool.nim");
	if ((NU)(i0) > (NU)(255)) raiseIndexError();
	initsemaphore_9czoqdg4eHIgtJ4wssK5YHA((&workersdata_R5YxoJYCt3PvKeJGhluUDQ[(i0)- 0].q.empty));
	nimln(382, "threadpool.nim");
	if ((NU)(i0) > (NU)(255)) raiseIndexError();
	initlock_NXoRcxfV39aV9cflSTUwtJ1glocks((&workersdata_R5YxoJYCt3PvKeJGhluUDQ[(i0)- 0].q.lock));
	nimln(383, "threadpool.nim");
	if ((NU)(i0) > (NU)(255)) raiseIndexError();
	if ((NU)(i0) > (NU)(255)) raiseIndexError();
	createthread_Gg58sihoqa0UVgbqgCx9ctg((&workers_bezHuru9a1bEti2XBmfodvA[(i0)- 0]), slave_ZLEiMrITYl7xqyEhA5iC1g, (&workersdata_R5YxoJYCt3PvKeJGhluUDQ[(i0)- 0]));
	popFrame();
}

N_NOINLINE(void, activatedistinguishedthread_gZGpMQ9anM43sp7cjLJQjLg_2)(NI i0) {
	nimfr("activateDistinguishedThread", "threadpool.nim")
	nimln(390, "threadpool.nim");
	if ((NU)(i0) > (NU)(31)) raiseIndexError();
	initsemaphore_9czoqdg4eHIgtJ4wssK5YHA((&distinguisheddata_Lqsi7ieuVktaO9acMSZyorQ[(i0)- 0].taskarrived));
	nimln(391, "threadpool.nim");
	if ((NU)(i0) > (NU)(31)) raiseIndexError();
	initsemaphore_9czoqdg4eHIgtJ4wssK5YHA((&distinguisheddata_Lqsi7ieuVktaO9acMSZyorQ[(i0)- 0].taskstarted));
	nimln(392, "threadpool.nim");
	if ((NU)(i0) > (NU)(31)) raiseIndexError();
	distinguisheddata_Lqsi7ieuVktaO9acMSZyorQ[(i0)- 0].initialized = NIM_TRUE;
	nimln(393, "threadpool.nim");
	if ((NU)(i0) > (NU)(31)) raiseIndexError();
	initsemaphore_9czoqdg4eHIgtJ4wssK5YHA((&distinguisheddata_Lqsi7ieuVktaO9acMSZyorQ[(i0)- 0].q.empty));
	nimln(394, "threadpool.nim");
	if ((NU)(i0) > (NU)(31)) raiseIndexError();
	initlock_NXoRcxfV39aV9cflSTUwtJ1glocks((&distinguisheddata_Lqsi7ieuVktaO9acMSZyorQ[(i0)- 0].q.lock));
	nimln(395, "threadpool.nim");
	if ((NU)(i0) > (NU)(31)) raiseIndexError();
	initsemaphore_9czoqdg4eHIgtJ4wssK5YHA((&distinguisheddata_Lqsi7ieuVktaO9acMSZyorQ[(i0)- 0].readyfortask));
	nimln(396, "threadpool.nim");
	if ((NU)(i0) > (NU)(31)) raiseIndexError();
	if ((NU)(i0) > (NU)(31)) raiseIndexError();
	createthread_Gg58sihoqa0UVgbqgCx9ctg((&distinguished_PEEgL9bODGVNNubj61abNQA[(i0)- 0]), distinguishedslave_ZLEiMrITYl7xqyEhA5iC1g_2, (&distinguisheddata_Lqsi7ieuVktaO9acMSZyorQ[(i0)- 0]));
	popFrame();
}

N_NIMCALL(void, setup_p4oO1XgRwu6WxNojgsXntg)(void) {
	NI p0;
	nimfr("setup", "threadpool.nim")
	nimln(399, "threadpool.nim");
	p0 = ncpicountProcessors();
	nimln(402, "threadpool.nim");
	currentpoolsize_ErccdOg9batM6rAb3hYbfxA = ((p0 <= ((NI) 256)) ? p0 : ((NI) 256));
	nimln(403, "threadpool.nim");
	readyworker_BT69aUhVoxO4qq9b8EinSVNA = (&workersdata_R5YxoJYCt3PvKeJGhluUDQ[(((NI) 0))- 0]);
	{
		NI i_Xr3LY7B7HR2htpYD4HgXRA;
		NI HEX3Atmp_ZXU2HoC8zmkTygcjhkhFQQ;
		NI res_bOqYXrR8mrM9czgTwuZkSUg;
		i_Xr3LY7B7HR2htpYD4HgXRA = (NI)0;
		HEX3Atmp_ZXU2HoC8zmkTygcjhkhFQQ = (NI)0;
		nimln(404, "threadpool.nim");
		HEX3Atmp_ZXU2HoC8zmkTygcjhkhFQQ = subInt(currentpoolsize_ErccdOg9batM6rAb3hYbfxA, 1);
		nimln(1908, "system.nim");
		res_bOqYXrR8mrM9czgTwuZkSUg = ((NI) 0);
		{
			nimln(1909, "system.nim");
			while (1) {
				NI T_Qzgg5NBLvccay07XFph3Rw_22;
				nimln(1908, "system.nim");
				if (!(res_bOqYXrR8mrM9czgTwuZkSUg <= HEX3Atmp_ZXU2HoC8zmkTygcjhkhFQQ)) goto LA3;
				nimln(1910, "system.nim");
				i_Xr3LY7B7HR2htpYD4HgXRA = res_bOqYXrR8mrM9czgTwuZkSUg;
				nimln(404, "threadpool.nim");
				activateworkerthread_gZGpMQ9anM43sp7cjLJQjLg(i_Xr3LY7B7HR2htpYD4HgXRA);
				nimln(1908, "system.nim");
				T_Qzgg5NBLvccay07XFph3Rw_22 = addInt(res_bOqYXrR8mrM9czgTwuZkSUg, ((NI) 1));
				res_bOqYXrR8mrM9czgTwuZkSUg = (NI)(T_Qzgg5NBLvccay07XFph3Rw_22);
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(NIM_BOOL, preferspawn_Jvod3sf15qssvdMH82j5dg)(void) {
	NIM_BOOL result0;
	nimfr("preferSpawn", "threadpool.nim")
	result0 = (NIM_BOOL)0;
	nimln(410, "threadpool.nim");
	result0 = (((NI) 0) < gsomeready_RyUdpNfPQUpKmQaHtWHYoA.counter);
	popFrame();
	return result0;
}

N_NIMCALL(void, nimSpawn3)(TY_fhqfcnDhIcLpBpSTVsWEZg fn0, void* data0) {
	nimfr("nimSpawn3", "threadpool.nim")
{	{
		nimln(447, "threadpool.nim");
		while (1) {
			nimln(448, "threadpool.nim");
			{
				NIM_BOOL LOC5;
				LOC5 = (NIM_BOOL)0;
				LOC5 = selectworker_BW1ODxSJ4rN4KmfdYS8AFw(readyworker_BT69aUhVoxO4qq9b8EinSVNA, fn0, data0);
				if (!LOC5) goto LA6;
				goto BeforeRet;
			}
			LA6: ;
			{
				NI i_RG0N2CJecwm3syRiIPU0Ww;
				NI HEX3Atmp_rWZpkcRJ6dq5zx2nU2735A;
				NI res_wPcWvbO0nadiAHYoUJb2rg;
				i_RG0N2CJecwm3syRiIPU0Ww = (NI)0;
				HEX3Atmp_rWZpkcRJ6dq5zx2nU2735A = (NI)0;
				nimln(449, "threadpool.nim");
				HEX3Atmp_rWZpkcRJ6dq5zx2nU2735A = subInt(currentpoolsize_ErccdOg9batM6rAb3hYbfxA, 1);
				nimln(1908, "system.nim");
				res_wPcWvbO0nadiAHYoUJb2rg = ((NI) 0);
				{
					nimln(1909, "system.nim");
					while (1) {
						NI T_Qzgg5NBLvccay07XFph3Rw_23;
						nimln(1908, "system.nim");
						if (!(res_wPcWvbO0nadiAHYoUJb2rg <= HEX3Atmp_rWZpkcRJ6dq5zx2nU2735A)) goto LA10;
						nimln(1910, "system.nim");
						i_RG0N2CJecwm3syRiIPU0Ww = res_wPcWvbO0nadiAHYoUJb2rg;
						nimln(450, "threadpool.nim");
						{
							NIM_BOOL LOC13;
							if ((NU)(i_RG0N2CJecwm3syRiIPU0Ww) > (NU)(255)) raiseIndexError();
							LOC13 = (NIM_BOOL)0;
							LOC13 = selectworker_BW1ODxSJ4rN4KmfdYS8AFw((&workersdata_R5YxoJYCt3PvKeJGhluUDQ[(i_RG0N2CJecwm3syRiIPU0Ww)- 0]), fn0, data0);
							if (!LOC13) goto LA14;
							goto BeforeRet;
						}
						LA14: ;
						nimln(1908, "system.nim");
						T_Qzgg5NBLvccay07XFph3Rw_23 = addInt(res_wPcWvbO0nadiAHYoUJb2rg, ((NI) 1));
						res_wPcWvbO0nadiAHYoUJb2rg = (NI)(T_Qzgg5NBLvccay07XFph3Rw_23);
					} LA10: ;
				}
			}
			nimln(454, "threadpool.nim");
			{
				NIM_BOOL LOC18;
				LOC18 = (NIM_BOOL)0;
				LOC18 = (state_7PVqgO4qfT36l9bZ9a9cqhD9bA.calls < maxpoolsize_I5gWiq7COu2xfOvex9aGTWw);
				if (LOC18) goto LA19;
				LOC18 = (((NI) ((NI)(state_7PVqgO4qfT36l9bZ9a9cqhD9bA.calls & ((NI) 127)))) == ((NI) 0));
				LA19: ;
				if (!LOC18) goto LA20;
				nimln(456, "threadpool.nim");
				{
					NIM_BOOL LOC24;
					Threadpooladvice_vD9cAMuSmfH29a9al5Q9cUZCig LOC27;
					LOC24 = (NIM_BOOL)0;
					LOC24 = tryacquire_RVpMCi0dWU5mH1GyAP2R5w((&statelock_Of3qxka1C2uLE9anKCj52kA));
					if (!LOC24) goto LA25;
					nimln(457, "threadpool.nim");
					LOC27 = (Threadpooladvice_vD9cAMuSmfH29a9al5Q9cUZCig)0;
					LOC27 = advice_uXlfLohkC9aBvpzhcIrG9amw((&state_7PVqgO4qfT36l9bZ9a9cqhD9bA));
					switch (LOC27) {
					case ((Threadpooladvice_vD9cAMuSmfH29a9al5Q9cUZCig) 0):
					{
					}
					break;
					case ((Threadpooladvice_vD9cAMuSmfH29a9al5Q9cUZCig) 1):
					{
						nimln(460, "threadpool.nim");
						{
							Worker_AqHEWWcw2VBFjoa2Hp8Akw* w0;
							NI LOC38;
							if (!(currentpoolsize_ErccdOg9batM6rAb3hYbfxA < maxpoolsize_I5gWiq7COu2xfOvex9aGTWw)) goto LA32;
							nimln(461, "threadpool.nim");
							{
								if ((NU)(currentpoolsize_ErccdOg9batM6rAb3hYbfxA) > (NU)(255)) raiseIndexError();
								if (!!(workersdata_R5YxoJYCt3PvKeJGhluUDQ[(currentpoolsize_ErccdOg9batM6rAb3hYbfxA)- 0].initialized)) goto LA36;
								nimln(462, "threadpool.nim");
								activateworkerthread_gZGpMQ9anM43sp7cjLJQjLg(currentpoolsize_ErccdOg9batM6rAb3hYbfxA);
							}
							LA36: ;
							nimln(463, "threadpool.nim");
							if ((NU)(currentpoolsize_ErccdOg9batM6rAb3hYbfxA) > (NU)(255)) raiseIndexError();
							w0 = (&workersdata_R5YxoJYCt3PvKeJGhluUDQ[(currentpoolsize_ErccdOg9batM6rAb3hYbfxA)- 0]);
							nimln(464, "threadpool.nim");
							LOC38 = (NI)0;
							LOC38 = atomicinc_4E9cxwuunx9aiL7vj9bdy8WvAsystem((&currentpoolsize_ErccdOg9batM6rAb3hYbfxA), ((NI) 1));
							nimln(465, "threadpool.nim");
							{
								NIM_BOOL LOC41;
								LOC41 = (NIM_BOOL)0;
								LOC41 = selectworker_BW1ODxSJ4rN4KmfdYS8AFw(w0, fn0, data0);
								if (!LOC41) goto LA42;
								nimln(466, "threadpool.nim");
								release_9bBEZeGCRkWQl9bLT1qt423Q_2((&statelock_Of3qxka1C2uLE9anKCj52kA));
								nimln(467, "threadpool.nim");
								goto BeforeRet;
							}
							LA42: ;
						}
						LA32: ;
					}
					break;
					case ((Threadpooladvice_vD9cAMuSmfH29a9al5Q9cUZCig) 2):
					{
						nimln(470, "threadpool.nim");
						{
							Worker_AqHEWWcw2VBFjoa2Hp8Akw* w0;
							NI T_Qzgg5NBLvccay07XFph3Rw_24;
							if (!(minpoolsize_L9a7W9byTjVXeXKRg5OtqNTg < currentpoolsize_ErccdOg9batM6rAb3hYbfxA)) goto LA47;
							nimln(471, "threadpool.nim");
							T_Qzgg5NBLvccay07XFph3Rw_24 = subInt(currentpoolsize_ErccdOg9batM6rAb3hYbfxA, ((NI) 1));
							if ((NU)((NI)(T_Qzgg5NBLvccay07XFph3Rw_24)) > (NU)(255)) raiseIndexError();
							w0 = (&workersdata_R5YxoJYCt3PvKeJGhluUDQ[((NI)(T_Qzgg5NBLvccay07XFph3Rw_24))- 0]);
							nimln(472, "threadpool.nim");
							(*w0).shutdown = NIM_TRUE;
						}
						LA47: ;
					}
					break;
					}
					nimln(474, "threadpool.nim");
					release_9bBEZeGCRkWQl9bLT1qt423Q_2((&statelock_Of3qxka1C2uLE9anKCj52kA));
				}
				LA25: ;
			}
			LA20: ;
			nimln(487, "threadpool.nim");
			{
				TSafePoint T_Qzgg5NBLvccay07XFph3Rw_25;
				if (!isslave_t9a8wsVVRYqGEKhg1vb49b3g) goto LA51;
				nimln(490, "threadpool.nim");
				acquire_9bBEZeGCRkWQl9bLT1qt423Q((&numslaveslock_WtiE83BZa1NBG7G2g8ZnmA));
				nimln(64, "locks.nim");
				pushSafePoint(&T_Qzgg5NBLvccay07XFph3Rw_25);
				T_Qzgg5NBLvccay07XFph3Rw_25.status = setjmp(T_Qzgg5NBLvccay07XFph3Rw_25.context);
				if (T_Qzgg5NBLvccay07XFph3Rw_25.status == 0) {
					NI T_Qzgg5NBLvccay07XFph3Rw_27;
					nimln(491, "threadpool.nim");
					{
						NI T_Qzgg5NBLvccay07XFph3Rw_26;
						T_Qzgg5NBLvccay07XFph3Rw_26 = addInt(numslaveswaiting_fTOoJ83E0W3d2BkhxhQFwg, ((NI) 1));
						if (!(numslavesrunning_ptIe6dS9bOnWPjIrLSfTasw <= (NI)(T_Qzgg5NBLvccay07XFph3Rw_26))) goto LA56;
						nimln(495, "threadpool.nim");
						{
							Worker_AqHEWWcw2VBFjoa2Hp8Akw* w0;
							NI LOC66;
							if (!(currentpoolsize_ErccdOg9batM6rAb3hYbfxA < maxpoolsize_I5gWiq7COu2xfOvex9aGTWw)) goto LA60;
							nimln(496, "threadpool.nim");
							{
								if ((NU)(currentpoolsize_ErccdOg9batM6rAb3hYbfxA) > (NU)(255)) raiseIndexError();
								if (!!(workersdata_R5YxoJYCt3PvKeJGhluUDQ[(currentpoolsize_ErccdOg9batM6rAb3hYbfxA)- 0].initialized)) goto LA64;
								nimln(497, "threadpool.nim");
								activateworkerthread_gZGpMQ9anM43sp7cjLJQjLg(currentpoolsize_ErccdOg9batM6rAb3hYbfxA);
							}
							LA64: ;
							nimln(498, "threadpool.nim");
							if ((NU)(currentpoolsize_ErccdOg9batM6rAb3hYbfxA) > (NU)(255)) raiseIndexError();
							w0 = (&workersdata_R5YxoJYCt3PvKeJGhluUDQ[(currentpoolsize_ErccdOg9batM6rAb3hYbfxA)- 0]);
							nimln(499, "threadpool.nim");
							LOC66 = (NI)0;
							LOC66 = atomicinc_4E9cxwuunx9aiL7vj9bdy8WvAsystem((&currentpoolsize_ErccdOg9batM6rAb3hYbfxA), ((NI) 1));
							nimln(500, "threadpool.nim");
							{
								NIM_BOOL LOC69;
								LOC69 = (NIM_BOOL)0;
								LOC69 = selectworker_BW1ODxSJ4rN4KmfdYS8AFw(w0, fn0, data0);
								if (!LOC69) goto LA70;
								nimln(501, "threadpool.nim");
								popSafePoint();
								nimln(490, "threadpool.nim");
								release_9bBEZeGCRkWQl9bLT1qt423Q_2((&numslaveslock_WtiE83BZa1NBG7G2g8ZnmA));
								goto BeforeRet;
							}
							LA70: ;
						}
						goto LA58;
						LA60: ;
						{
						}
						LA58: ;
					}
					LA56: ;
					nimln(507, "threadpool.nim");
					T_Qzgg5NBLvccay07XFph3Rw_27 = addInt(numslaveswaiting_fTOoJ83E0W3d2BkhxhQFwg, ((NI) 1));
					numslaveswaiting_fTOoJ83E0W3d2BkhxhQFwg = (NI)(T_Qzgg5NBLvccay07XFph3Rw_27);
					popSafePoint();
				}
				else {
					popSafePoint();
					setFrame((TFrame*)&FR);
				}
				{
					nimln(490, "threadpool.nim");
					release_9bBEZeGCRkWQl9bLT1qt423Q_2((&numslaveslock_WtiE83BZa1NBG7G2g8ZnmA));
				}
				if (T_Qzgg5NBLvccay07XFph3Rw_25.status != 0) reraiseException();
			}
			LA51: ;
			nimln(509, "threadpool.nim");
			await_9czoqdg4eHIgtJ4wssK5YHA_2((&gsomeready_RyUdpNfPQUpKmQaHtWHYoA));
			nimln(511, "threadpool.nim");
			{
				TSafePoint T_Qzgg5NBLvccay07XFph3Rw_28;
				if (!isslave_t9a8wsVVRYqGEKhg1vb49b3g) goto LA77;
				nimln(512, "threadpool.nim");
				acquire_9bBEZeGCRkWQl9bLT1qt423Q((&numslaveslock_WtiE83BZa1NBG7G2g8ZnmA));
				nimln(64, "locks.nim");
				pushSafePoint(&T_Qzgg5NBLvccay07XFph3Rw_28);
				T_Qzgg5NBLvccay07XFph3Rw_28.status = setjmp(T_Qzgg5NBLvccay07XFph3Rw_28.context);
				if (T_Qzgg5NBLvccay07XFph3Rw_28.status == 0) {
					NI T_Qzgg5NBLvccay07XFph3Rw_29;
					nimln(513, "threadpool.nim");
					T_Qzgg5NBLvccay07XFph3Rw_29 = subInt(numslaveswaiting_fTOoJ83E0W3d2BkhxhQFwg, ((NI) 1));
					numslaveswaiting_fTOoJ83E0W3d2BkhxhQFwg = (NI)(T_Qzgg5NBLvccay07XFph3Rw_29);
					popSafePoint();
				}
				else {
					popSafePoint();
					setFrame((TFrame*)&FR);
				}
				{
					nimln(512, "threadpool.nim");
					release_9bBEZeGCRkWQl9bLT1qt423Q_2((&numslaveslock_WtiE83BZa1NBG7G2g8ZnmA));
				}
				if (T_Qzgg5NBLvccay07XFph3Rw_28.status != 0) reraiseException();
			}
			LA77: ;
		}
	}
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, nimSpawn4)(TY_fhqfcnDhIcLpBpSTVsWEZg fn0, void* data0, NI id0) {
	nimfr("nimSpawn4", "threadpool.nim")
	nimln(521, "threadpool.nim");
	acquire_9bBEZeGCRkWQl9bLT1qt423Q((&distinguishedlock_lPmqsqhMalxIWA0zwhlpFg));
	nimln(522, "threadpool.nim");
	{
		if (!!(distinguisheddata_Lqsi7ieuVktaO9acMSZyorQ[(id0)- 0].initialized)) goto LA3;
		nimln(523, "threadpool.nim");
		activatedistinguishedthread_gZGpMQ9anM43sp7cjLJQjLg_2(((NI) (id0)));
	}
	LA3: ;
	nimln(524, "threadpool.nim");
	release_9bBEZeGCRkWQl9bLT1qt423Q_2((&distinguishedlock_lPmqsqhMalxIWA0zwhlpFg));
	{
		nimln(525, "threadpool.nim");
		while (1) {
			nimln(526, "threadpool.nim");
			{
				NIM_BOOL LOC9;
				LOC9 = (NIM_BOOL)0;
				LOC9 = selectworker_BW1ODxSJ4rN4KmfdYS8AFw((&distinguisheddata_Lqsi7ieuVktaO9acMSZyorQ[(id0)- 0]), fn0, data0);
				if (!LOC9) goto LA10;
				goto LA5;
			}
			LA10: ;
			nimln(527, "threadpool.nim");
			await_9czoqdg4eHIgtJ4wssK5YHA_2((&distinguisheddata_Lqsi7ieuVktaO9acMSZyorQ[(id0)- 0].readyfortask));
		}
	} LA5: ;
	popFrame();
}

N_NIMCALL(void, sync_p4oO1XgRwu6WxNojgsXntg_2)(void) {
	nimfr("sync", "threadpool.nim")
	{
		nimln(533, "threadpool.nim");
		while (1) {
			NIM_BOOL allready0;
			nimln(534, "threadpool.nim");
			allready0 = NIM_TRUE;
			{
				NI i_uF5tssmPpsmv03RjWmQpGA;
				NI HEX3Atmp_L9caFGsUOXHOnT7oR4nmuRg;
				NI res_7Mir54IiJyl1U2NFqT3NDQ;
				i_uF5tssmPpsmv03RjWmQpGA = (NI)0;
				HEX3Atmp_L9caFGsUOXHOnT7oR4nmuRg = (NI)0;
				nimln(535, "threadpool.nim");
				HEX3Atmp_L9caFGsUOXHOnT7oR4nmuRg = subInt(currentpoolsize_ErccdOg9batM6rAb3hYbfxA, 1);
				nimln(1908, "system.nim");
				res_7Mir54IiJyl1U2NFqT3NDQ = ((NI) 0);
				{
					nimln(1909, "system.nim");
					while (1) {
						NIM_BOOL LOC10;
						NI T_Qzgg5NBLvccay07XFph3Rw_30;
						nimln(1908, "system.nim");
						if (!(res_7Mir54IiJyl1U2NFqT3NDQ <= HEX3Atmp_L9caFGsUOXHOnT7oR4nmuRg)) goto LA5;
						nimln(1910, "system.nim");
						i_uF5tssmPpsmv03RjWmQpGA = res_7Mir54IiJyl1U2NFqT3NDQ;
						nimln(536, "threadpool.nim");
						{
							if (!!(allready0)) goto LA8;
							goto LA3;
						}
						LA8: ;
						nimln(537, "threadpool.nim");
						LOC10 = (NIM_BOOL)0;
						LOC10 = allready0;
						if (!(LOC10)) goto LA11;
						if ((NU)(i_uF5tssmPpsmv03RjWmQpGA) > (NU)(255)) raiseIndexError();
						LOC10 = workersdata_R5YxoJYCt3PvKeJGhluUDQ[(i_uF5tssmPpsmv03RjWmQpGA)- 0].ready;
						LA11: ;
						allready0 = LOC10;
						nimln(1908, "system.nim");
						T_Qzgg5NBLvccay07XFph3Rw_30 = addInt(res_7Mir54IiJyl1U2NFqT3NDQ, ((NI) 1));
						res_7Mir54IiJyl1U2NFqT3NDQ = (NI)(T_Qzgg5NBLvccay07XFph3Rw_30);
					} LA5: ;
				}
			} LA3: ;
			nimln(538, "threadpool.nim");
			{
				if (!allready0) goto LA14;
				goto LA1;
			}
			LA14: ;
			nimln(539, "threadpool.nim");
			await_9czoqdg4eHIgtJ4wssK5YHA_2((&gsomeready_RyUdpNfPQUpKmQaHtWHYoA));
		}
	} LA1: ;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_threadpoolInit000)(void) {
	nimfr("threadpool", "threadpool.nim")
	nimln(295, "threadpool.nim");
	maxpoolsize_I5gWiq7COu2xfOvex9aGTWw = ((NI) 256);
	nimln(296, "threadpool.nim");
	minpoolsize_L9a7W9byTjVXeXKRg5OtqNTg = ((NI) 4);
	nimln(308, "threadpool.nim");
	initlock_NXoRcxfV39aV9cflSTUwtJ1glocks((&numslaveslock_WtiE83BZa1NBG7G2g8ZnmA));
	nimln(310, "threadpool.nim");
	initsemaphore_9czoqdg4eHIgtJ4wssK5YHA((&gsomeready_RyUdpNfPQUpKmQaHtWHYoA));
	nimln(443, "threadpool.nim");
	initlock_NXoRcxfV39aV9cflSTUwtJ1glocks((&statelock_Of3qxka1C2uLE9anKCj52kA));
	nimln(518, "threadpool.nim");
	initlock_NXoRcxfV39aV9cflSTUwtJ1glocks((&distinguishedlock_lPmqsqhMalxIWA0zwhlpFg));
	nimln(541, "threadpool.nim");
	setup_p4oO1XgRwu6WxNojgsXntg();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_threadpoolDatInit000)(void) {
static TNimNode* T_Qzgg5NBLvccay07XFph3Rw_19[9];
static TNimNode* T_Qzgg5NBLvccay07XFph3Rw_20[3];
static TNimNode* T_Qzgg5NBLvccay07XFph3Rw_21[4];
static TNimNode T_Qzgg5NBLvccay07XFph3Rw_0[19];
NTI_AqHEWWcw2VBFjoa2Hp8Akw.size = sizeof(Worker_AqHEWWcw2VBFjoa2Hp8Akw);
NTI_AqHEWWcw2VBFjoa2Hp8Akw.kind = 18;
NTI_AqHEWWcw2VBFjoa2Hp8Akw.base = 0;
NTI_AqHEWWcw2VBFjoa2Hp8Akw.flags = 3;
T_Qzgg5NBLvccay07XFph3Rw_19[0] = &T_Qzgg5NBLvccay07XFph3Rw_0[1];
NTI_sx9abLHOwgGDBH9bpoqw2ezw.size = sizeof(Semaphore_sx9abLHOwgGDBH9bpoqw2ezw);
NTI_sx9abLHOwgGDBH9bpoqw2ezw.kind = 18;
NTI_sx9abLHOwgGDBH9bpoqw2ezw.base = 0;
NTI_sx9abLHOwgGDBH9bpoqw2ezw.flags = 3;
T_Qzgg5NBLvccay07XFph3Rw_20[0] = &T_Qzgg5NBLvccay07XFph3Rw_0[3];
T_Qzgg5NBLvccay07XFph3Rw_0[3].kind = 1;
T_Qzgg5NBLvccay07XFph3Rw_0[3].offset = offsetof(Semaphore_sx9abLHOwgGDBH9bpoqw2ezw, c);
T_Qzgg5NBLvccay07XFph3Rw_0[3].typ = (&NTI_9bK5SEAqe27K49aDtonge9aQg);
T_Qzgg5NBLvccay07XFph3Rw_0[3].name = "c";
T_Qzgg5NBLvccay07XFph3Rw_20[1] = &T_Qzgg5NBLvccay07XFph3Rw_0[4];
T_Qzgg5NBLvccay07XFph3Rw_0[4].kind = 1;
T_Qzgg5NBLvccay07XFph3Rw_0[4].offset = offsetof(Semaphore_sx9abLHOwgGDBH9bpoqw2ezw, L);
T_Qzgg5NBLvccay07XFph3Rw_0[4].typ = (&NTI_lsB6JckQ3csMuiRW476VWg);
T_Qzgg5NBLvccay07XFph3Rw_0[4].name = "L";
T_Qzgg5NBLvccay07XFph3Rw_20[2] = &T_Qzgg5NBLvccay07XFph3Rw_0[5];
T_Qzgg5NBLvccay07XFph3Rw_0[5].kind = 1;
T_Qzgg5NBLvccay07XFph3Rw_0[5].offset = offsetof(Semaphore_sx9abLHOwgGDBH9bpoqw2ezw, counter);
T_Qzgg5NBLvccay07XFph3Rw_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA);
T_Qzgg5NBLvccay07XFph3Rw_0[5].name = "counter";
T_Qzgg5NBLvccay07XFph3Rw_0[2].len = 3; T_Qzgg5NBLvccay07XFph3Rw_0[2].kind = 2; T_Qzgg5NBLvccay07XFph3Rw_0[2].sons = &T_Qzgg5NBLvccay07XFph3Rw_20[0];
NTI_sx9abLHOwgGDBH9bpoqw2ezw.node = &T_Qzgg5NBLvccay07XFph3Rw_0[2];
T_Qzgg5NBLvccay07XFph3Rw_0[1].kind = 1;
T_Qzgg5NBLvccay07XFph3Rw_0[1].offset = offsetof(Worker_AqHEWWcw2VBFjoa2Hp8Akw, taskarrived);
T_Qzgg5NBLvccay07XFph3Rw_0[1].typ = (&NTI_sx9abLHOwgGDBH9bpoqw2ezw);
T_Qzgg5NBLvccay07XFph3Rw_0[1].name = "taskArrived";
T_Qzgg5NBLvccay07XFph3Rw_19[1] = &T_Qzgg5NBLvccay07XFph3Rw_0[6];
T_Qzgg5NBLvccay07XFph3Rw_0[6].kind = 1;
T_Qzgg5NBLvccay07XFph3Rw_0[6].offset = offsetof(Worker_AqHEWWcw2VBFjoa2Hp8Akw, taskstarted);
T_Qzgg5NBLvccay07XFph3Rw_0[6].typ = (&NTI_sx9abLHOwgGDBH9bpoqw2ezw);
T_Qzgg5NBLvccay07XFph3Rw_0[6].name = "taskStarted";
T_Qzgg5NBLvccay07XFph3Rw_19[2] = &T_Qzgg5NBLvccay07XFph3Rw_0[7];
NTI_fhqfcnDhIcLpBpSTVsWEZg.size = sizeof(TY_fhqfcnDhIcLpBpSTVsWEZg);
NTI_fhqfcnDhIcLpBpSTVsWEZg.kind = 25;
NTI_fhqfcnDhIcLpBpSTVsWEZg.base = 0;
NTI_fhqfcnDhIcLpBpSTVsWEZg.flags = 3;
T_Qzgg5NBLvccay07XFph3Rw_0[7].kind = 1;
T_Qzgg5NBLvccay07XFph3Rw_0[7].offset = offsetof(Worker_AqHEWWcw2VBFjoa2Hp8Akw, f);
T_Qzgg5NBLvccay07XFph3Rw_0[7].typ = (&NTI_fhqfcnDhIcLpBpSTVsWEZg);
T_Qzgg5NBLvccay07XFph3Rw_0[7].name = "f";
T_Qzgg5NBLvccay07XFph3Rw_19[3] = &T_Qzgg5NBLvccay07XFph3Rw_0[8];
T_Qzgg5NBLvccay07XFph3Rw_0[8].kind = 1;
T_Qzgg5NBLvccay07XFph3Rw_0[8].offset = offsetof(Worker_AqHEWWcw2VBFjoa2Hp8Akw, data);
T_Qzgg5NBLvccay07XFph3Rw_0[8].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw);
T_Qzgg5NBLvccay07XFph3Rw_0[8].name = "data";
T_Qzgg5NBLvccay07XFph3Rw_19[4] = &T_Qzgg5NBLvccay07XFph3Rw_0[9];
T_Qzgg5NBLvccay07XFph3Rw_0[9].kind = 1;
T_Qzgg5NBLvccay07XFph3Rw_0[9].offset = offsetof(Worker_AqHEWWcw2VBFjoa2Hp8Akw, ready);
T_Qzgg5NBLvccay07XFph3Rw_0[9].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ);
T_Qzgg5NBLvccay07XFph3Rw_0[9].name = "ready";
T_Qzgg5NBLvccay07XFph3Rw_19[5] = &T_Qzgg5NBLvccay07XFph3Rw_0[10];
T_Qzgg5NBLvccay07XFph3Rw_0[10].kind = 1;
T_Qzgg5NBLvccay07XFph3Rw_0[10].offset = offsetof(Worker_AqHEWWcw2VBFjoa2Hp8Akw, initialized);
T_Qzgg5NBLvccay07XFph3Rw_0[10].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ);
T_Qzgg5NBLvccay07XFph3Rw_0[10].name = "initialized";
T_Qzgg5NBLvccay07XFph3Rw_19[6] = &T_Qzgg5NBLvccay07XFph3Rw_0[11];
T_Qzgg5NBLvccay07XFph3Rw_0[11].kind = 1;
T_Qzgg5NBLvccay07XFph3Rw_0[11].offset = offsetof(Worker_AqHEWWcw2VBFjoa2Hp8Akw, shutdown);
T_Qzgg5NBLvccay07XFph3Rw_0[11].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ);
T_Qzgg5NBLvccay07XFph3Rw_0[11].name = "shutdown";
T_Qzgg5NBLvccay07XFph3Rw_19[7] = &T_Qzgg5NBLvccay07XFph3Rw_0[12];
NTI_5COJP8EWIaAuXvZlDbQZmw.size = sizeof(Tofreequeue_5COJP8EWIaAuXvZlDbQZmw);
NTI_5COJP8EWIaAuXvZlDbQZmw.kind = 18;
NTI_5COJP8EWIaAuXvZlDbQZmw.base = 0;
NTI_5COJP8EWIaAuXvZlDbQZmw.flags = 3;
T_Qzgg5NBLvccay07XFph3Rw_21[0] = &T_Qzgg5NBLvccay07XFph3Rw_0[14];
T_Qzgg5NBLvccay07XFph3Rw_0[14].kind = 1;
T_Qzgg5NBLvccay07XFph3Rw_0[14].offset = offsetof(Tofreequeue_5COJP8EWIaAuXvZlDbQZmw, len);
T_Qzgg5NBLvccay07XFph3Rw_0[14].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA);
T_Qzgg5NBLvccay07XFph3Rw_0[14].name = "len";
T_Qzgg5NBLvccay07XFph3Rw_21[1] = &T_Qzgg5NBLvccay07XFph3Rw_0[15];
T_Qzgg5NBLvccay07XFph3Rw_0[15].kind = 1;
T_Qzgg5NBLvccay07XFph3Rw_0[15].offset = offsetof(Tofreequeue_5COJP8EWIaAuXvZlDbQZmw, lock);
T_Qzgg5NBLvccay07XFph3Rw_0[15].typ = (&NTI_lsB6JckQ3csMuiRW476VWg);
T_Qzgg5NBLvccay07XFph3Rw_0[15].name = "lock";
T_Qzgg5NBLvccay07XFph3Rw_21[2] = &T_Qzgg5NBLvccay07XFph3Rw_0[16];
T_Qzgg5NBLvccay07XFph3Rw_0[16].kind = 1;
T_Qzgg5NBLvccay07XFph3Rw_0[16].offset = offsetof(Tofreequeue_5COJP8EWIaAuXvZlDbQZmw, empty);
T_Qzgg5NBLvccay07XFph3Rw_0[16].typ = (&NTI_sx9abLHOwgGDBH9bpoqw2ezw);
T_Qzgg5NBLvccay07XFph3Rw_0[16].name = "empty";
T_Qzgg5NBLvccay07XFph3Rw_21[3] = &T_Qzgg5NBLvccay07XFph3Rw_0[17];
NTI_2PWyF6nokyTyhzmcY3ON3w.size = sizeof(TY_2PWyF6nokyTyhzmcY3ON3w);
NTI_2PWyF6nokyTyhzmcY3ON3w.kind = 16;
NTI_2PWyF6nokyTyhzmcY3ON3w.base = (&NTI_vr5DoT1jILTGdRlYv1OYpw);
NTI_2PWyF6nokyTyhzmcY3ON3w.flags = 3;
T_Qzgg5NBLvccay07XFph3Rw_0[17].kind = 1;
T_Qzgg5NBLvccay07XFph3Rw_0[17].offset = offsetof(Tofreequeue_5COJP8EWIaAuXvZlDbQZmw, data);
T_Qzgg5NBLvccay07XFph3Rw_0[17].typ = (&NTI_2PWyF6nokyTyhzmcY3ON3w);
T_Qzgg5NBLvccay07XFph3Rw_0[17].name = "data";
T_Qzgg5NBLvccay07XFph3Rw_0[13].len = 4; T_Qzgg5NBLvccay07XFph3Rw_0[13].kind = 2; T_Qzgg5NBLvccay07XFph3Rw_0[13].sons = &T_Qzgg5NBLvccay07XFph3Rw_21[0];
NTI_5COJP8EWIaAuXvZlDbQZmw.node = &T_Qzgg5NBLvccay07XFph3Rw_0[13];
T_Qzgg5NBLvccay07XFph3Rw_0[12].kind = 1;
T_Qzgg5NBLvccay07XFph3Rw_0[12].offset = offsetof(Worker_AqHEWWcw2VBFjoa2Hp8Akw, q);
T_Qzgg5NBLvccay07XFph3Rw_0[12].typ = (&NTI_5COJP8EWIaAuXvZlDbQZmw);
T_Qzgg5NBLvccay07XFph3Rw_0[12].name = "q";
T_Qzgg5NBLvccay07XFph3Rw_19[8] = &T_Qzgg5NBLvccay07XFph3Rw_0[18];
T_Qzgg5NBLvccay07XFph3Rw_0[18].kind = 1;
T_Qzgg5NBLvccay07XFph3Rw_0[18].offset = offsetof(Worker_AqHEWWcw2VBFjoa2Hp8Akw, readyfortask);
T_Qzgg5NBLvccay07XFph3Rw_0[18].typ = (&NTI_sx9abLHOwgGDBH9bpoqw2ezw);
T_Qzgg5NBLvccay07XFph3Rw_0[18].name = "readyForTask";
T_Qzgg5NBLvccay07XFph3Rw_0[0].len = 9; T_Qzgg5NBLvccay07XFph3Rw_0[0].kind = 2; T_Qzgg5NBLvccay07XFph3Rw_0[0].sons = &T_Qzgg5NBLvccay07XFph3Rw_19[0];
NTI_AqHEWWcw2VBFjoa2Hp8Akw.node = &T_Qzgg5NBLvccay07XFph3Rw_0[0];
NTI_CyNApV6Mfiphj5eUnH5G1A.size = sizeof(Worker_AqHEWWcw2VBFjoa2Hp8Akw*);
NTI_CyNApV6Mfiphj5eUnH5G1A.kind = 21;
NTI_CyNApV6Mfiphj5eUnH5G1A.base = (&NTI_AqHEWWcw2VBFjoa2Hp8Akw);
NTI_CyNApV6Mfiphj5eUnH5G1A.flags = 3;
}

