/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/opt/nim/lib -o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_sharedlist.o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_sharedlist.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#include <string.h>
#include <pthread.h>
#undef linux
typedef struct Sharedlist_9cWkTIPQvNw7gFHMOEzMCLw Sharedlist_9cWkTIPQvNw7gFHMOEzMCLw;
typedef struct SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw;
struct  Sharedlist_9cWkTIPQvNw7gFHMOEzMCLw  {
SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw* head;
SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw* tail;
pthread_mutex_t lock;
};
typedef void* TY_Rrw59cMvNu8cDA9cQDh4v2oA[100];
struct  SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw  {
SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw* next;
NI datalen;
TY_Rrw59cMvNu8cDA9cQDh4v2oA d;
};
static N_INLINE(void, initlock_NXoRcxfV39aV9cflSTUwtJ1glocks)(pthread_mutex_t* lock0);
N_NIMCALL(void, acquire_9bBEZeGCRkWQl9bLT1qt423Q)(pthread_mutex_t* lock0);
N_NOCONV(void*, allocshared0_sVm4rDImKK2ZDdylByayiA_3)(NI size0);
N_NIMCALL(void, release_9bBEZeGCRkWQl9bLT1qt423Q_2)(pthread_mutex_t* lock0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
extern NIM_THREADVAR TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(void, initlock_NXoRcxfV39aV9cflSTUwtJ1glocks)(pthread_mutex_t* lock0) {
	pthread_mutex_init(lock0, NIM_NIL);
}

N_NIMCALL(Sharedlist_9cWkTIPQvNw7gFHMOEzMCLw, initsharedlist_ftyWlQN9a0f9cDyTF3NRz9cTg)(void) {
	Sharedlist_9cWkTIPQvNw7gFHMOEzMCLw result0;
	memset((void*)(&result0), 0, sizeof(result0));
	initlock_NXoRcxfV39aV9cflSTUwtJ1glocks((&result0.lock));
	result0.head = NIM_NIL;
	result0.tail = NIM_NIL;
	return result0;
}

N_NIMCALL(void, add_LMD14ZZveJ1hTQDkuvr6bQ)(Sharedlist_9cWkTIPQvNw7gFHMOEzMCLw* x0, void* y0) {
	SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw* node0;
	acquire_9bBEZeGCRkWQl9bLT1qt423Q((&(*x0).lock));
	node0 = (SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw*)0;
	{
		NIM_BOOL LOC3;
		void* LOC7;
		LOC3 = (NIM_BOOL)0;
		LOC3 = ((*x0).tail == NIM_NIL);
		if (LOC3) goto LA4;
		LOC3 = ((*(*x0).tail).datalen == ((NI) 100));
		LA4: ;
		if (!LOC3) goto LA5;
		LOC7 = (void*)0;
		LOC7 = allocshared0_sVm4rDImKK2ZDdylByayiA_3(((NI) (((NI)sizeof(SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw)))));
		node0 = ((SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw*) (LOC7));
		(*node0).next = (*x0).tail;
		(*x0).tail = node0;
		{
			if (!((*x0).head == NIM_NIL)) goto LA10;
			(*x0).head = node0;
		}
		LA10: ;
	}
	goto LA1;
	LA5: ;
	{
		node0 = (*x0).tail;
	}
	LA1: ;
	(*node0).d[((*node0).datalen)- 0] = y0;
	(*node0).datalen += ((NI) 1);
	release_9bBEZeGCRkWQl9bLT1qt423Q_2((&(*x0).lock));
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_sharedlistInit000)(void) {
	nimfr("sharedlist", "sharedlist.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_sharedlistDatInit000)(void) {
}

