/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/opt/nim/lib -o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_cpuload.o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_cpuload.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#undef linux
typedef struct Threadpoolstate_jN9benzGjAA9bryIHC1FGnZA Threadpoolstate_jN9benzGjAA9bryIHC1FGnZA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef NU8 Threadpooladvice_vD9cAMuSmfH29a9al5Q9cUZCig;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 Filemode_fVUBHvW79bXUw1j55Oo9avSQ;
struct  Threadpoolstate_jN9benzGjAA9bryIHC1FGnZA  {
NI calls;
};
N_NIMCALL(Threadpooladvice_vD9cAMuSmfH29a9al5Q9cUZCig, advice_uXlfLohkC9aBvpzhcIrG9amw)(Threadpoolstate_jN9benzGjAA9bryIHC1FGnZA* s0);
N_NIMCALL(FILE*, open_hqzpWQbdA2B8l9a6wwNoP4g)(NimStringDesc* filename0, Filemode_fVUBHvW79bXUw1j55Oo9avSQ mode0, NI bufsize0);
N_NIMCALL(void, close_BWnr8V7RERYno9bIdPmw8Hw)(FILE* f0);
N_NIMCALL(NI, ncpicountProcessors)(void);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, mulInt)(NI a0, NI b0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
extern NIM_THREADVAR TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(T_CFWzmO8DEHxStvjr8GyqGg_2, "/proc/loadavg", 13);

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(Threadpooladvice_vD9cAMuSmfH29a9al5Q9cUZCig, advice_uXlfLohkC9aBvpzhcIrG9amw)(Threadpoolstate_jN9benzGjAA9bryIHC1FGnZA* s0) {
	Threadpooladvice_vD9cAMuSmfH29a9al5Q9cUZCig result0;
	FILE* f0;
	NF b0;
	NI busy0;
	NI total0;
	NI cpus0;
	NI T_CFWzmO8DEHxStvjr8GyqGg_6;
	nimfr("advice", "cpuload.nim")
	result0 = (Threadpooladvice_vD9cAMuSmfH29a9al5Q9cUZCig)0;
	nimln(63, "cpuload.nim");
	f0 = open_hqzpWQbdA2B8l9a6wwNoP4g(((NimStringDesc*) &T_CFWzmO8DEHxStvjr8GyqGg_2), ((Filemode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));
	b0 = (NF)0;
	busy0 = (NI)0;
	total0 = (NI)0;
	nimln(66, "cpuload.nim");
	fscanf(f0, "%lf %lf %lf %ld/%ld", (&b0), (&b0), (&b0), (&busy0), (&total0));
	nimln(68, "cpuload.nim");
	close_BWnr8V7RERYno9bIdPmw8Hw(f0);
	nimln(69, "cpuload.nim");
	cpus0 = ncpicountProcessors();
	nimln(70, "cpuload.nim");
	{
		NI T_CFWzmO8DEHxStvjr8GyqGg_3;
		T_CFWzmO8DEHxStvjr8GyqGg_3 = subInt(busy0, ((NI) 1));
		if (!((NI)(T_CFWzmO8DEHxStvjr8GyqGg_3) < cpus0)) goto LA3;
		nimln(71, "cpuload.nim");
		result0 = ((Threadpooladvice_vD9cAMuSmfH29a9al5Q9cUZCig) 1);
	}
	goto LA1;
	LA3: ;
	{
		NI T_CFWzmO8DEHxStvjr8GyqGg_4;
		NI T_CFWzmO8DEHxStvjr8GyqGg_5;
		nimln(72, "cpuload.nim");
		T_CFWzmO8DEHxStvjr8GyqGg_4 = mulInt(cpus0, ((NI) 2));
		T_CFWzmO8DEHxStvjr8GyqGg_5 = subInt(busy0, ((NI) 1));
		if (!((NI)(T_CFWzmO8DEHxStvjr8GyqGg_4) <= (NI)(T_CFWzmO8DEHxStvjr8GyqGg_5))) goto LA6;
		nimln(73, "cpuload.nim");
		result0 = ((Threadpooladvice_vD9cAMuSmfH29a9al5Q9cUZCig) 2);
	}
	goto LA1;
	LA6: ;
	{
		nimln(75, "cpuload.nim");
		result0 = ((Threadpooladvice_vD9cAMuSmfH29a9al5Q9cUZCig) 0);
	}
	LA1: ;
	nimln(79, "cpuload.nim");
	T_CFWzmO8DEHxStvjr8GyqGg_6 = addInt((*s0).calls, ((NI) 1));
	(*s0).calls = (NI)(T_CFWzmO8DEHxStvjr8GyqGg_6);
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuloadInit000)(void) {
	nimfr("cpuload", "cpuload.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_cpuloadDatInit000)(void) {
}

