/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/opt/nim/lib -o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_endians.o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_endians.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef linux
static N_INLINE(void, swapendian64_IzdisrH4sYnsItUtxSkomAendians)(void* outp0, void* inp0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, swapendian32_IzdisrH4sYnsItUtxSkomA_2endians)(void* outp0, void* inp0);
static N_INLINE(void, swapendian16_IzdisrH4sYnsItUtxSkomA_3endians)(void* outp0, void* inp0);
static N_INLINE(void, littleendian64_IzdisrH4sYnsItUtxSkomA_4endians)(void* outp0, void* inp0);
static N_INLINE(void, copymem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest0, void* source0, NI size0);
static N_INLINE(void, littleendian32_IzdisrH4sYnsItUtxSkomA_5endians)(void* outp0, void* inp0);
static N_INLINE(void, littleendian16_IzdisrH4sYnsItUtxSkomA_6endians)(void* outp0, void* inp0);
static N_INLINE(void, bigendian64_IzdisrH4sYnsItUtxSkomA_7endians)(void* outp0, void* inp0);
static N_INLINE(void, bigendian32_IzdisrH4sYnsItUtxSkomA_8endians)(void* outp0, void* inp0);
static N_INLINE(void, bigendian16_IzdisrH4sYnsItUtxSkomA_9endians)(void* outp0, void* inp0);
extern NIM_THREADVAR TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, swapendian64_IzdisrH4sYnsItUtxSkomAendians)(void* outp0, void* inp0) {
	NU64* i0;
	NU64* o0;
	nimfr("swapEndian64", "endians.nim")
	nimln(48, "endians.nim");
	i0 = ((NU64*) (inp0));
	nimln(49, "endians.nim");
	o0 = ((NU64*) (outp0));
	nimln(50, "endians.nim");
	(*o0) = __builtin_bswap64((*i0));
	popFrame();
}

static N_INLINE(void, swapendian32_IzdisrH4sYnsItUtxSkomA_2endians)(void* outp0, void* inp0) {
	NU32* i0;
	NU32* o0;
	nimfr("swapEndian32", "endians.nim")
	nimln(53, "endians.nim");
	i0 = ((NU32*) (inp0));
	nimln(54, "endians.nim");
	o0 = ((NU32*) (outp0));
	nimln(55, "endians.nim");
	(*o0) = __builtin_bswap32((*i0));
	popFrame();
}

static N_INLINE(void, swapendian16_IzdisrH4sYnsItUtxSkomA_3endians)(void* outp0, void* inp0) {
	NU16* i0;
	NU16* o0;
	nimfr("swapEndian16", "endians.nim")
	nimln(58, "endians.nim");
	i0 = ((NU16*) (inp0));
	nimln(59, "endians.nim");
	o0 = ((NU16*) (outp0));
	nimln(60, "endians.nim");
	(*o0) = __builtin_bswap16((*i0));
	popFrame();
}

static N_INLINE(void, copymem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest0, void* source0, NI size0) {
	void* LOC1;
	LOC1 = (void*)0;
	LOC1 = memcpy(dest0, source0, ((size_t) (size0)));
}

static N_INLINE(void, littleendian64_IzdisrH4sYnsItUtxSkomA_4endians)(void* outp0, void* inp0) {
	nimfr("littleEndian64", "endians.nim")
	nimln(103, "endians.nim");
	copymem_E1xtACub5WcDa3vbrIXbwgsystem(outp0, inp0, ((NI) 8));
	popFrame();
}

static N_INLINE(void, littleendian32_IzdisrH4sYnsItUtxSkomA_5endians)(void* outp0, void* inp0) {
	nimfr("littleEndian32", "endians.nim")
	nimln(104, "endians.nim");
	copymem_E1xtACub5WcDa3vbrIXbwgsystem(outp0, inp0, ((NI) 4));
	popFrame();
}

static N_INLINE(void, littleendian16_IzdisrH4sYnsItUtxSkomA_6endians)(void* outp0, void* inp0) {
	nimfr("littleEndian16", "endians.nim")
	nimln(105, "endians.nim");
	copymem_E1xtACub5WcDa3vbrIXbwgsystem(outp0, inp0, ((NI) 2));
	popFrame();
}

static N_INLINE(void, bigendian64_IzdisrH4sYnsItUtxSkomA_7endians)(void* outp0, void* inp0) {
	nimfr("bigEndian64", "endians.nim")
	nimln(106, "endians.nim");
	swapendian64_IzdisrH4sYnsItUtxSkomAendians(outp0, inp0);
	popFrame();
}

static N_INLINE(void, bigendian32_IzdisrH4sYnsItUtxSkomA_8endians)(void* outp0, void* inp0) {
	nimfr("bigEndian32", "endians.nim")
	nimln(107, "endians.nim");
	swapendian32_IzdisrH4sYnsItUtxSkomA_2endians(outp0, inp0);
	popFrame();
}

static N_INLINE(void, bigendian16_IzdisrH4sYnsItUtxSkomA_9endians)(void* outp0, void* inp0) {
	nimfr("bigEndian16", "endians.nim")
	nimln(108, "endians.nim");
	swapendian16_IzdisrH4sYnsItUtxSkomA_3endians(outp0, inp0);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansInit000)(void) {
	nimfr("endians", "endians.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_endiansDatInit000)(void) {
}

