/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/opt/nim/lib -o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_deques.o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_deques.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef linux
typedef struct Deque_lXZKLUMbpAcAUzeVrG09bNg Deque_lXZKLUMbpAcAUzeVrG09bNg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY_WF89a8QyKeDCh4DYWTmSiBg TY_WF89a8QyKeDCh4DYWTmSiBg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct Cellseq_Axo1XVm9aaQueTOldv8le5w Cellseq_Axo1XVm9aaQueTOldv8le5w;
typedef struct Gcheap_1TRH1TZMaVZTnLNcIHuNFQ Gcheap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct Gcstack_7fytPA5bBsob6See21YMRA Gcstack_7fytPA5bBsob6See21YMRA;
typedef struct Memregion_x81NhDv59b8ercDZ9bi85jyg Memregion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct Smallchunk_tXn60W2f8h3jgAYdEmy5NQ Smallchunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct Llchunk_XsENErzHIZV9bhvyJx56wGw Llchunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct Bigchunk_Rv9c70Uhp2TytkX7eH78qEg Bigchunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct Intset_EZObFrE3NC9bIb3YMkY9crZA Intset_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct Avlnode_IaqjtwKhxLEpvDS9bct9blEw Avlnode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct Gcstat_0RwLoVBHZPfUAcLczmfQAg Gcstat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct Cellset_jG87P0AI9aZtss9ccTYBIISQ Cellset_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct Pagedesc_fublkgIY4LG3mT51LU2WHg Pagedesc_fublkgIY4LG3mT51LU2WHg;
typedef struct Sharedlist_9cWkTIPQvNw7gFHMOEzMCLw Sharedlist_9cWkTIPQvNw7gFHMOEzMCLw;
typedef struct SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw;
typedef struct Basechunk_Sdq7WpT6qAH858F5ZEdG3w Basechunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct Freecell_u6M5LHprqzkn9axr04yg9bGQ Freecell_u6M5LHprqzkn9axr04yg9bGQ;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Deque_lXZKLUMbpAcAUzeVrG09bNg  {
TY_WF89a8QyKeDCh4DYWTmSiBg* data;
NI head;
NI tail;
NI count;
NI mask;
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (void* ClEnv);
void* ClEnv;
} TY_IIomJ6ptE6vfJ5zRbATgkQ;
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  Cellseq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  Intset_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
struct  Memregion_x81NhDv59b8ercDZ9bi85jyg  {
NI minlargeobj;
NI maxlargeobj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freesmallchunks;
Llchunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* freechunkslist;
Intset_EZObFrE3NC9bIb3YMkY9crZA chunkstarts;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* root;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* last;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* freeavlnodes;
NIM_BOOL locked;
NIM_BOOL blockchunksizeincrease;
NI nextchunksize;
};
struct  Gcstat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
Pagedesc_fublkgIY4LG3mT51LU2WHg* head;
Pagedesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  Sharedlist_9cWkTIPQvNw7gFHMOEzMCLw  {
SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw* head;
SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw* tail;
pthread_mutex_t lock;
};
struct  Gcheap_1TRH1TZMaVZTnLNcIHuNFQ  {
Gcstack_7fytPA5bBsob6See21YMRA* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq_Axo1XVm9aaQueTOldv8le5w zct;
Cellseq_Axo1XVm9aaQueTOldv8le5w decstack;
Cellseq_Axo1XVm9aaQueTOldv8le5w tempstack;
NI recgclock;
Memregion_x81NhDv59b8ercDZ9bi85jyg region;
Gcstat_0RwLoVBHZPfUAcLczmfQAg stat;
Cellset_jG87P0AI9aZtss9ccTYBIISQ marked;
Cellseq_Axo1XVm9aaQueTOldv8le5w additionalroots;
Sharedlist_9cWkTIPQvNw7gFHMOEzMCLw todispose;
};
struct  Gcstack_7fytPA5bBsob6See21YMRA  {
Gcstack_7fytPA5bBsob6See21YMRA* prev;
Gcstack_7fytPA5bBsob6See21YMRA* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk_tXn60W2f8h3jgAYdEmy5NQ  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* next;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
Freecell_u6M5LHprqzkn9axr04yg9bGQ* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
Llchunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  Bigchunk_Rv9c70Uhp2TytkX7eH78qEg  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* next;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NI align;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef Avlnode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  Avlnode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc_fublkgIY4LG3mT51LU2WHg  {
Pagedesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef void* TY_Rrw59cMvNu8cDA9cQDh4v2oA[100];
struct  SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw  {
SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw* next;
NI datalen;
TY_Rrw59cMvNu8cDA9cQDh4v2oA d;
};
struct  Freecell_u6M5LHprqzkn9axr04yg9bGQ  {
Freecell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zerofield;
};
struct TY_WF89a8QyKeDCh4DYWTmSiBg {
  TGenericSeq Sup;
  TY_IIomJ6ptE6vfJ5zRbATgkQ data[SEQ_DECL_SIZE];
};
N_NIMCALL(NIM_BOOL, ispoweroftwo_M0Db9b9cHxuUgw2ZF0P8utPg)(NI x0);
N_NIMCALL(void, failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
static N_NIMCALL(void, Marker_TY_WF89a8QyKeDCh4DYWTmSiBg)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ0, NI len0);
N_NIMCALL(void, unsureAsgnRef)(void** dest0, void* src0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, expandifneeded_yUfcbmt639aJ6tr007RgLpQ)(Deque_lXZKLUMbpAcAUzeVrG09bNg* deq0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NIMCALL(TY_WF89a8QyKeDCh4DYWTmSiBg*, newseq_FGDbRopuA4y4tNQGp9cEEsg)(NI len0);
N_NIMCALL(NI, mulInt)(NI a0, NI b0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, asgnRef)(void** dest0, void* src0);
static N_INLINE(void, incref_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0);
static N_INLINE(void, decref_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NOINLINE(void, addzct_fCDI7oO1NNVXXURtxSzsRw)(Cellseq_Axo1XVm9aaQueTOldv8le5w* s0, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
extern TNimType NTI_IIomJ6ptE6vfJ5zRbATgkQ;
TNimType NTI_WF89a8QyKeDCh4DYWTmSiBg;
extern NIM_THREADVAR TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_lXZKLUMbpAcAUzeVrG09bNg;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA;
extern NIM_THREADVAR Gcheap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(T_NdgYN5HU2ty0qMI5oazWyg_2, "isPowerOfTwo(initialSize) ", 26);

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}
static N_NIMCALL(void, Marker_TY_WF89a8QyKeDCh4DYWTmSiBg)(void* p, NI op) {
	TY_WF89a8QyKeDCh4DYWTmSiBg* a;
	NI LOC1;
	a = (TY_WF89a8QyKeDCh4DYWTmSiBg*)p;
	LOC1 = (NI)0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].ClEnv, op);
	}
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, initdeque_ReEIfP39bwVCXJ79bSWPO49aw)(NI initialsize0, Deque_lXZKLUMbpAcAUzeVrG09bNg* Result) {
	NI T_NdgYN5HU2ty0qMI5oazWyg_3;
	nimfr("initDeque", "deques.nim")
	nimln(58, "deques.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = ispoweroftwo_M0Db9b9cHxuUgw2ZF0P8utPg(initialsize0);
		if (!!(LOC3)) goto LA4;
		failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &T_NdgYN5HU2ty0qMI5oazWyg_2));
	}
	LA4: ;
	nimln(59, "deques.nim");
	T_NdgYN5HU2ty0qMI5oazWyg_3 = subInt(initialsize0, ((NI) 1));
	(*Result).mask = (NI)(T_NdgYN5HU2ty0qMI5oazWyg_3);
	nimln(60, "deques.nim");
	unsureAsgnRef((void**) (&(*Result).data), (TY_WF89a8QyKeDCh4DYWTmSiBg*) newSeq((&NTI_WF89a8QyKeDCh4DYWTmSiBg), ((NI)chckRange(initialsize0, ((NI) 0), ((NI) IL64(9223372036854775807))))));
	popFrame();
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, incref_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0) {
	nimfr("incRef", "gc.nim")
	nimln(232, "gc.nim");
	(*c0).refcount = (NI)((NU64)((*c0).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln(134, "gc.nim");
	result0 = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(220, "gc.nim");
	addzct_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c0);
	popFrame();
}

static N_INLINE(void, decref_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0) {
	nimfr("decRef", "gc.nim")
	nimln(227, "gc.nim");
	{
		(*c0).refcount -= ((NI) 8);
		if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(228, "gc.nim");
		rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system(c0);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest0, void* src0) {
	nimfr("asgnRef", "gc.nim")
	nimln(273, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* LOC5;
		nimln(347, "system.nim");
		nimln(273, "gc.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		LOC5 = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		LOC5 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src0);
		incref_9cAA5YuQAAC3MVbnGeV86swsystem(LOC5);
	}
	LA3: ;
	nimln(274, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* LOC10;
		nimln(347, "system.nim");
		nimln(274, "gc.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA8;
		LOC10 = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		LOC10 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest0));
		decref_MV4BBk6J1qu70IbBxwEn4wsystem(LOC10);
	}
	LA8: ;
	nimln(275, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

N_NIMCALL(void, expandifneeded_yUfcbmt639aJ6tr007RgLpQ)(Deque_lXZKLUMbpAcAUzeVrG09bNg* deq0) {
	NI cap0;
	NI T_NdgYN5HU2ty0qMI5oazWyg_5;
	nimfr("expandIfNeeded", "deques.nim")
	nimln(129, "deques.nim");
	T_NdgYN5HU2ty0qMI5oazWyg_5 = addInt((*deq0).mask, ((NI) 1));
	cap0 = (NI)(T_NdgYN5HU2ty0qMI5oazWyg_5);
	nimln(130, "deques.nim");
	{
		NIM_BOOL LOC3;
		TY_WF89a8QyKeDCh4DYWTmSiBg* n0;
		NI T_NdgYN5HU2ty0qMI5oazWyg_6;
		NI T_NdgYN5HU2ty0qMI5oazWyg_9;
		NI T_NdgYN5HU2ty0qMI5oazWyg_10;
		LOC3 = (NIM_BOOL)0;
		LOC3 = unlikely((cap0 <= (*deq0).count));
		if (!LOC3) goto LA4;
		nimln(131, "deques.nim");
		T_NdgYN5HU2ty0qMI5oazWyg_6 = mulInt(cap0, ((NI) 2));
		n0 = newseq_FGDbRopuA4y4tNQGp9cEEsg(((NI)chckRange((NI)(T_NdgYN5HU2ty0qMI5oazWyg_6), ((NI) 0), ((NI) IL64(9223372036854775807)))));
		{
			NI i_fsnXgYZVE9bMDXsNTupabUg;
			TY_IIomJ6ptE6vfJ5zRbATgkQ x_vzXE83sKP44ogH70lFRocQ;
			Deque_lXZKLUMbpAcAUzeVrG09bNg HEX3Atmp_aV29bpY1lQaXmCAarK264bg;
			NI i_fsnXgYZVE9bMDXsNTupabUg_2;
			i_fsnXgYZVE9bMDXsNTupabUg = (NI)0;
			memset((void*)(&x_vzXE83sKP44ogH70lFRocQ), 0, sizeof(x_vzXE83sKP44ogH70lFRocQ));
			memset((void*)(&HEX3Atmp_aV29bpY1lQaXmCAarK264bg), 0, sizeof(HEX3Atmp_aV29bpY1lQaXmCAarK264bg));
			nimln(132, "deques.nim");
			memcpy((void*)(&HEX3Atmp_aV29bpY1lQaXmCAarK264bg), (NIM_CONST void*)(&(*deq0)), sizeof(HEX3Atmp_aV29bpY1lQaXmCAarK264bg));
			nimln(112, "deques.nim");
			i_fsnXgYZVE9bMDXsNTupabUg_2 = HEX3Atmp_aV29bpY1lQaXmCAarK264bg.head;
			{
				NI c_Y9bgX1Cq1CUSK9cXK35AlMQw;
				NI HEX3Atmp_aV29bpY1lQaXmCAarK264bg_2;
				NI i_fsnXgYZVE9bMDXsNTupabUg_3;
				c_Y9bgX1Cq1CUSK9cXK35AlMQw = (NI)0;
				HEX3Atmp_aV29bpY1lQaXmCAarK264bg_2 = (NI)0;
				nimln(113, "deques.nim");
				HEX3Atmp_aV29bpY1lQaXmCAarK264bg_2 = HEX3Atmp_aV29bpY1lQaXmCAarK264bg.count;
				nimln(3689, "system.nim");
				i_fsnXgYZVE9bMDXsNTupabUg_3 = ((NI) 0);
				{
					nimln(3690, "system.nim");
					while (1) {
						NI T_NdgYN5HU2ty0qMI5oazWyg_7;
						NI T_NdgYN5HU2ty0qMI5oazWyg_8;
						nimln(3689, "system.nim");
						if (!(i_fsnXgYZVE9bMDXsNTupabUg_3 < HEX3Atmp_aV29bpY1lQaXmCAarK264bg_2)) goto LA9;
						c_Y9bgX1Cq1CUSK9cXK35AlMQw = i_fsnXgYZVE9bMDXsNTupabUg_3;
						nimln(113, "deques.nim");
						i_fsnXgYZVE9bMDXsNTupabUg = c_Y9bgX1Cq1CUSK9cXK35AlMQw;
						nimln(114, "deques.nim");
						if ((NU)(i_fsnXgYZVE9bMDXsNTupabUg_2) >= (NU)(HEX3Atmp_aV29bpY1lQaXmCAarK264bg.data->Sup.len)) raiseIndexError();
						x_vzXE83sKP44ogH70lFRocQ.ClEnv = HEX3Atmp_aV29bpY1lQaXmCAarK264bg.data->data[i_fsnXgYZVE9bMDXsNTupabUg_2].ClEnv;
						x_vzXE83sKP44ogH70lFRocQ.ClPrc = HEX3Atmp_aV29bpY1lQaXmCAarK264bg.data->data[i_fsnXgYZVE9bMDXsNTupabUg_2].ClPrc;
						nimln(133, "deques.nim");
						if ((NU)(i_fsnXgYZVE9bMDXsNTupabUg) >= (NU)(n0->Sup.len)) raiseIndexError();
						asgnRef((void**) (&n0->data[i_fsnXgYZVE9bMDXsNTupabUg].ClEnv), x_vzXE83sKP44ogH70lFRocQ.ClEnv);
						n0->data[i_fsnXgYZVE9bMDXsNTupabUg].ClPrc = x_vzXE83sKP44ogH70lFRocQ.ClPrc;
						nimln(115, "deques.nim");
						nimln(112, "deques.nim");
						T_NdgYN5HU2ty0qMI5oazWyg_7 = addInt(i_fsnXgYZVE9bMDXsNTupabUg_2, ((NI) 1));
						i_fsnXgYZVE9bMDXsNTupabUg_2 = (NI)((NI)(T_NdgYN5HU2ty0qMI5oazWyg_7) & HEX3Atmp_aV29bpY1lQaXmCAarK264bg.mask);
						nimln(3689, "system.nim");
						T_NdgYN5HU2ty0qMI5oazWyg_8 = addInt(i_fsnXgYZVE9bMDXsNTupabUg_3, ((NI) 1));
						i_fsnXgYZVE9bMDXsNTupabUg_3 = (NI)(T_NdgYN5HU2ty0qMI5oazWyg_8);
					} LA9: ;
				}
			}
		}
		nimln(134, "deques.nim");
		unsureAsgnRef((void**) (&(*deq0).data), n0);
		nimln(135, "deques.nim");
		T_NdgYN5HU2ty0qMI5oazWyg_9 = mulInt(cap0, ((NI) 2));
		T_NdgYN5HU2ty0qMI5oazWyg_10 = subInt((NI)(T_NdgYN5HU2ty0qMI5oazWyg_9), ((NI) 1));
		(*deq0).mask = (NI)(T_NdgYN5HU2ty0qMI5oazWyg_10);
		nimln(136, "deques.nim");
		(*deq0).tail = (*deq0).count;
		nimln(137, "deques.nim");
		(*deq0).head = ((NI) 0);
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(void, addlast_vqmMzAk3ZYGwAn5hysAc6w)(Deque_lXZKLUMbpAcAUzeVrG09bNg* deq0, TY_IIomJ6ptE6vfJ5zRbATgkQ item0) {
	NI T_NdgYN5HU2ty0qMI5oazWyg_11;
	NI T_NdgYN5HU2ty0qMI5oazWyg_12;
	nimfr("addLast", "deques.nim")
	nimln(148, "deques.nim");
	expandifneeded_yUfcbmt639aJ6tr007RgLpQ(deq0);
	nimln(149, "deques.nim");
	T_NdgYN5HU2ty0qMI5oazWyg_11 = addInt((*deq0).count, ((NI) 1));
	(*deq0).count = (NI)(T_NdgYN5HU2ty0qMI5oazWyg_11);
	nimln(150, "deques.nim");
	if ((NU)((*deq0).tail) >= (NU)((*deq0).data->Sup.len)) raiseIndexError();
	asgnRef((void**) (&(*deq0).data->data[(*deq0).tail].ClEnv), item0.ClEnv);
	(*deq0).data->data[(*deq0).tail].ClPrc = item0.ClPrc;
	nimln(151, "deques.nim");
	T_NdgYN5HU2ty0qMI5oazWyg_12 = addInt((*deq0).tail, ((NI) 1));
	(*deq0).tail = (NI)((NI)(T_NdgYN5HU2ty0qMI5oazWyg_12) & (*deq0).mask);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_dequesInit000)(void) {
	nimfr("deques", "deques.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_dequesDatInit000)(void) {
static TNimNode* T_NdgYN5HU2ty0qMI5oazWyg_4[5];
static TNimNode T_NdgYN5HU2ty0qMI5oazWyg_0[6];
NTI_WF89a8QyKeDCh4DYWTmSiBg.size = sizeof(TY_WF89a8QyKeDCh4DYWTmSiBg*);
NTI_WF89a8QyKeDCh4DYWTmSiBg.kind = 24;
NTI_WF89a8QyKeDCh4DYWTmSiBg.base = (&NTI_IIomJ6ptE6vfJ5zRbATgkQ);
NTI_WF89a8QyKeDCh4DYWTmSiBg.marker = Marker_TY_WF89a8QyKeDCh4DYWTmSiBg;
NTI_lXZKLUMbpAcAUzeVrG09bNg.size = sizeof(Deque_lXZKLUMbpAcAUzeVrG09bNg);
NTI_lXZKLUMbpAcAUzeVrG09bNg.kind = 18;
NTI_lXZKLUMbpAcAUzeVrG09bNg.base = 0;
T_NdgYN5HU2ty0qMI5oazWyg_4[0] = &T_NdgYN5HU2ty0qMI5oazWyg_0[1];
T_NdgYN5HU2ty0qMI5oazWyg_0[1].kind = 1;
T_NdgYN5HU2ty0qMI5oazWyg_0[1].offset = offsetof(Deque_lXZKLUMbpAcAUzeVrG09bNg, data);
T_NdgYN5HU2ty0qMI5oazWyg_0[1].typ = (&NTI_WF89a8QyKeDCh4DYWTmSiBg);
T_NdgYN5HU2ty0qMI5oazWyg_0[1].name = "data";
T_NdgYN5HU2ty0qMI5oazWyg_4[1] = &T_NdgYN5HU2ty0qMI5oazWyg_0[2];
T_NdgYN5HU2ty0qMI5oazWyg_0[2].kind = 1;
T_NdgYN5HU2ty0qMI5oazWyg_0[2].offset = offsetof(Deque_lXZKLUMbpAcAUzeVrG09bNg, head);
T_NdgYN5HU2ty0qMI5oazWyg_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA);
T_NdgYN5HU2ty0qMI5oazWyg_0[2].name = "head";
T_NdgYN5HU2ty0qMI5oazWyg_4[2] = &T_NdgYN5HU2ty0qMI5oazWyg_0[3];
T_NdgYN5HU2ty0qMI5oazWyg_0[3].kind = 1;
T_NdgYN5HU2ty0qMI5oazWyg_0[3].offset = offsetof(Deque_lXZKLUMbpAcAUzeVrG09bNg, tail);
T_NdgYN5HU2ty0qMI5oazWyg_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA);
T_NdgYN5HU2ty0qMI5oazWyg_0[3].name = "tail";
T_NdgYN5HU2ty0qMI5oazWyg_4[3] = &T_NdgYN5HU2ty0qMI5oazWyg_0[4];
T_NdgYN5HU2ty0qMI5oazWyg_0[4].kind = 1;
T_NdgYN5HU2ty0qMI5oazWyg_0[4].offset = offsetof(Deque_lXZKLUMbpAcAUzeVrG09bNg, count);
T_NdgYN5HU2ty0qMI5oazWyg_0[4].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA);
T_NdgYN5HU2ty0qMI5oazWyg_0[4].name = "count";
T_NdgYN5HU2ty0qMI5oazWyg_4[4] = &T_NdgYN5HU2ty0qMI5oazWyg_0[5];
T_NdgYN5HU2ty0qMI5oazWyg_0[5].kind = 1;
T_NdgYN5HU2ty0qMI5oazWyg_0[5].offset = offsetof(Deque_lXZKLUMbpAcAUzeVrG09bNg, mask);
T_NdgYN5HU2ty0qMI5oazWyg_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA);
T_NdgYN5HU2ty0qMI5oazWyg_0[5].name = "mask";
T_NdgYN5HU2ty0qMI5oazWyg_0[0].len = 5; T_NdgYN5HU2ty0qMI5oazWyg_0[0].kind = 2; T_NdgYN5HU2ty0qMI5oazWyg_0[0].sons = &T_NdgYN5HU2ty0qMI5oazWyg_4[0];
NTI_lXZKLUMbpAcAUzeVrG09bNg.node = &T_NdgYN5HU2ty0qMI5oazWyg_0[0];
}

