/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/opt/nim/lib -o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_selectors.o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_selectors.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/epoll.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef linux
typedef struct Table_bnna5wr180tUeaeDFxJ4xA Table_bnna5wr180tUeaeDFxJ4xA;
typedef struct Selectorkey_gE60aCfYXV1Nf1VTfPbepw Selectorkey_gE60aCfYXV1Nf1VTfPbepw;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY_wQibBbBZLWmdoNxHgCZRyw TY_wQibBbBZLWmdoNxHgCZRyw;
typedef struct TY_ponAwt7gy9asnIS681IafZQ TY_ponAwt7gy9asnIS681IafZQ;
typedef struct Selector_X89cGFWVbzYzXTnuQzGngmA Selector_X89cGFWVbzYzXTnuQzGngmA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY_bkMUR8maranmy38dEG39cHA TY_bkMUR8maranmy38dEG39cHA;
typedef struct TY_nEEz1gjcivYloysklmeNTg TY_nEEz1gjcivYloysklmeNTg;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct Cellseq_Axo1XVm9aaQueTOldv8le5w Cellseq_Axo1XVm9aaQueTOldv8le5w;
typedef struct Gcheap_1TRH1TZMaVZTnLNcIHuNFQ Gcheap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct Gcstack_7fytPA5bBsob6See21YMRA Gcstack_7fytPA5bBsob6See21YMRA;
typedef struct Memregion_x81NhDv59b8ercDZ9bi85jyg Memregion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct Smallchunk_tXn60W2f8h3jgAYdEmy5NQ Smallchunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct Llchunk_XsENErzHIZV9bhvyJx56wGw Llchunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct Bigchunk_Rv9c70Uhp2TytkX7eH78qEg Bigchunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct Intset_EZObFrE3NC9bIb3YMkY9crZA Intset_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct Avlnode_IaqjtwKhxLEpvDS9bct9blEw Avlnode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct Gcstat_0RwLoVBHZPfUAcLczmfQAg Gcstat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct Cellset_jG87P0AI9aZtss9ccTYBIISQ Cellset_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct Pagedesc_fublkgIY4LG3mT51LU2WHg Pagedesc_fublkgIY4LG3mT51LU2WHg;
typedef struct Sharedlist_9cWkTIPQvNw7gFHMOEzMCLw Sharedlist_9cWkTIPQvNw7gFHMOEzMCLw;
typedef struct SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw;
typedef struct Basechunk_Sdq7WpT6qAH858F5ZEdG3w Basechunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct Freecell_u6M5LHprqzkn9axr04yg9bGQ Freecell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NU8 Event_nI40bZzTyYVrl763dZ9aHDg_Set;
struct  Selectorkey_gE60aCfYXV1Nf1VTfPbepw  {
int fd;
Event_nI40bZzTyYVrl763dZ9aHDg_Set events;
TNimObject* data;
};
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 Event_nI40bZzTyYVrl763dZ9aHDg;
struct  Table_bnna5wr180tUeaeDFxJ4xA  {
TY_wQibBbBZLWmdoNxHgCZRyw* data;
NI counter;
};
struct TY_ponAwt7gy9asnIS681IafZQ {
NI Field0;
int Field1;
Selectorkey_gE60aCfYXV1Nf1VTfPbepw Field2;
};
typedef struct epoll_event TY_iNLNjoAj1poPzqx9biLwG9bA[64];
struct  Selector_X89cGFWVbzYzXTnuQzGngmA  {
int epollfd;
TY_iNLNjoAj1poPzqx9biLwG9bA events;
Table_bnna5wr180tUeaeDFxJ4xA fds;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY_nEEz1gjcivYloysklmeNTg {
Selectorkey_gE60aCfYXV1Nf1VTfPbepw Field0;
Event_nI40bZzTyYVrl763dZ9aHDg_Set Field1;
};
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  Cellseq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  Intset_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
struct  Memregion_x81NhDv59b8ercDZ9bi85jyg  {
NI minlargeobj;
NI maxlargeobj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freesmallchunks;
Llchunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* freechunkslist;
Intset_EZObFrE3NC9bIb3YMkY9crZA chunkstarts;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* root;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* last;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* freeavlnodes;
NIM_BOOL locked;
NIM_BOOL blockchunksizeincrease;
NI nextchunksize;
};
struct  Gcstat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
Pagedesc_fublkgIY4LG3mT51LU2WHg* head;
Pagedesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  Sharedlist_9cWkTIPQvNw7gFHMOEzMCLw  {
SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw* head;
SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw* tail;
pthread_mutex_t lock;
};
struct  Gcheap_1TRH1TZMaVZTnLNcIHuNFQ  {
Gcstack_7fytPA5bBsob6See21YMRA* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq_Axo1XVm9aaQueTOldv8le5w zct;
Cellseq_Axo1XVm9aaQueTOldv8le5w decstack;
Cellseq_Axo1XVm9aaQueTOldv8le5w tempstack;
NI recgclock;
Memregion_x81NhDv59b8ercDZ9bi85jyg region;
Gcstat_0RwLoVBHZPfUAcLczmfQAg stat;
Cellset_jG87P0AI9aZtss9ccTYBIISQ marked;
Cellseq_Axo1XVm9aaQueTOldv8le5w additionalroots;
Sharedlist_9cWkTIPQvNw7gFHMOEzMCLw todispose;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Gcstack_7fytPA5bBsob6See21YMRA  {
Gcstack_7fytPA5bBsob6See21YMRA* prev;
Gcstack_7fytPA5bBsob6See21YMRA* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk_tXn60W2f8h3jgAYdEmy5NQ  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* next;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
Freecell_u6M5LHprqzkn9axr04yg9bGQ* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
Llchunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  Bigchunk_Rv9c70Uhp2TytkX7eH78qEg  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* next;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NI align;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef Avlnode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  Avlnode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc_fublkgIY4LG3mT51LU2WHg  {
Pagedesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef void* TY_Rrw59cMvNu8cDA9cQDh4v2oA[100];
struct  SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw  {
SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw* next;
NI datalen;
TY_Rrw59cMvNu8cDA9cQDh4v2oA d;
};
struct  Freecell_u6M5LHprqzkn9axr04yg9bGQ  {
Freecell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zerofield;
};
struct TY_bkMUR8maranmy38dEG39cHA {
  TGenericSeq Sup;
  TY_nEEz1gjcivYloysklmeNTg data[SEQ_DECL_SIZE];
};
struct TY_wQibBbBZLWmdoNxHgCZRyw {
  TGenericSeq Sup;
  TY_ponAwt7gy9asnIS681IafZQ data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, hash_9c3uvkGO9cpD9a7QU6mLwadLAselectors)(int x0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, HEX5BHEX5DHEX3D_3jMA6nwaCZ3e6Iyj5brtkg)(Table_bnna5wr180tUeaeDFxJ4xA* t0, int key0, Selectorkey_gE60aCfYXV1Nf1VTfPbepw val0);
static N_INLINE(NI, rawget_E9aV5vakSLJS0MAIqaecQsQtables)(Table_bnna5wr180tUeaeDFxJ4xA t0, int key0, NI* hc0);
static N_INLINE(NIM_BOOL, isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, nexttry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h0, NI maxhash0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NIMCALL(void, enlarge_XLab9bp69boKR7fPCKfFQ2hg)(Table_bnna5wr180tUeaeDFxJ4xA* t0);
N_NIMCALL(void, rawinsert_pD9czBD2OndL9cSDqb78Urig)(Table_bnna5wr180tUeaeDFxJ4xA* t0, TY_wQibBbBZLWmdoNxHgCZRyw** data0, int key0, Selectorkey_gE60aCfYXV1Nf1VTfPbepw val0, NI hc0, NI h0);
static N_INLINE(NI, rawgetknownhc_sVNCrVempRVYb0DwgWRB0Atables)(Table_bnna5wr180tUeaeDFxJ4xA t0, int key0, NI hc0);
N_NIMCALL(Selectorkey_gE60aCfYXV1Nf1VTfPbepw*, HEX5BHEX5D_Sd5XGNdJD9bEXX0z89aJkm7g)(Table_bnna5wr180tUeaeDFxJ4xA* t0, int key0);
N_NIMCALL(void, del_MPpoRTFhkQVAZDvswQqiSA)(Table_bnna5wr180tUeaeDFxJ4xA* t0, int key0);
N_NIMCALL(void, HEX5BHEX5D_QeLiydbSBk8OZJj1o5uN0w)(Table_bnna5wr180tUeaeDFxJ4xA t0, int key0, Selectorkey_gE60aCfYXV1Nf1VTfPbepw* Result);
N_NIMCALL(void, inittable_Hx3BnoioZlM0c7U4t1cT0w)(NI initialsize0, Table_bnna5wr180tUeaeDFxJ4xA* Result);
N_NIMCALL(NIM_BOOL, haskey_PW8rl8fmQKFFAo5bXDIQTQ)(Table_bnna5wr180tUeaeDFxJ4xA t0, int key0);
N_NIMCALL(struct epoll_event, createeventstruct_7vZrkYak2uWtlsjSDvVhgw)(Event_nI40bZzTyYVrl763dZ9aHDg_Set events0, int fd0);
N_NIMCALL(void, register_QCHaUKprAzyUegaWtXEnGw)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0, Event_nI40bZzTyYVrl763dZ9aHDg_Set events0, TNimObject* data0);
N_NOINLINE(void, raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA)(NI32 errorcode0, NimStringDesc* additionalinfo0);
N_NIMCALL(NI32, oslasterror_pMOMIZAQaKFp1XoL58mjVg)(void);
N_NIMCALL(void, update_VzJ8OVqBzjqu4C23Nq9bPvg)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0, Event_nI40bZzTyYVrl763dZ9aHDg_Set events0);
N_NIMCALL(void, unregister_2fDHSfeVBEEsLBSaUEUOzA)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
N_NIMCALL(void, close_MwlkQPYetm2csv9bp6JpPWw)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0);
N_NIMCALL(NIM_BOOL, epollhasfd_xj6cssVSm8j9bytjWGf29cUw)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0);
N_NIMCALL(TY_bkMUR8maranmy38dEG39cHA*, select_HpncstI132GvQ9ceBTIOgrg)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, NI timeout0);
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
static N_NIMCALL(void, Marker_TY_bkMUR8maranmy38dEG39cHA)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ0, NI len0);
N_NIMCALL(void, failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg0);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq0, NI elemsize0);
static N_INLINE(void, asgnRef)(void** dest0, void* src0);
static N_INLINE(void, incref_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0);
static N_INLINE(void, decref_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NOINLINE(void, addzct_fCDI7oO1NNVXXURtxSzsRw)(Cellseq_Axo1XVm9aaQueTOldv8le5w* s0, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NIMCALL(void, newselector_tcCxAL6x4L39akwZ39aVA6Tg)(Selector_X89cGFWVbzYzXTnuQzGngmA* Result);
N_NIMCALL(NIM_BOOL, contains_xj6cssVSm8j9bytjWGf29cUw_2)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0);
N_NIMCALL(void, HEX5BHEX5D_cRbUBRdnAVbKu6ptO8AZLQ)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0, Selectorkey_gE60aCfYXV1Nf1VTfPbepw* Result);
N_NOINLINE(void, chckNil)(void* p0);
N_NIMCALL(void, genericReset)(void* dest0, TNimType* mt0);
N_NIMCALL(NIM_BOOL, HEX3DHEX3D_fW6ECiKEQQ03nZ1qZlamvA)(Selectorkey_gE60aCfYXV1Nf1VTfPbepw x0, Selectorkey_gE60aCfYXV1Nf1VTfPbepw y0);
N_NIMCALL(NIM_BOOL, contains_Y3zqrOiY8I6fpNd9ahsiVnw)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, Selectorkey_gE60aCfYXV1Nf1VTfPbepw key0);
N_NIMCALL(NI, len_Q1GsJskrVK5e0DS9cZT9bODg)(Table_bnna5wr180tUeaeDFxJ4xA t0);
N_NIMCALL(NI, len_6bMoxDMwI4Nef9a1VY5tbmw)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0);
extern NIM_THREADVAR TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_gE60aCfYXV1Nf1VTfPbepw;
extern TNimType NTI_nlCscttRCss70IBTyuBqnA;
TNimType NTI_nI40bZzTyYVrl763dZ9aHDg;
TNimType NTI_YIRsZrDT89buh37M5yeUgng;
extern TNimType NTI_1VeTzqrFu2VJ4a6cGvuoyA;
TNimType NTI_nEEz1gjcivYloysklmeNTg;
TNimType NTI_bkMUR8maranmy38dEG39cHA;
extern NIM_THREADVAR Gcheap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_X89cGFWVbzYzXTnuQzGngmA;
extern TNimType NTI_zUGEEklrq4WOkixy0PK9cIw;
TNimType NTI_iNLNjoAj1poPzqx9biLwG9bA;
extern TNimType NTI_bnna5wr180tUeaeDFxJ4xA;
STRING_LITERAL(T_ln5vuDpFyDrAqQbYD2g52Q_9, "", 0);
STRING_LITERAL(T_ln5vuDpFyDrAqQbYD2g52Q_11, "\012  not (selectorKey.fd == SocketHandle(0)) ", 43);

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NI, hash_9c3uvkGO9cpD9a7QU6mLwadLAselectors)(int x0) {
	NI result0;
	nimfr("hash", "hashes.nim")
	result0 = (NI)0;
	nimln(121, "hashes.nim");
	result0 = ((NI) (x0));
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode0) {
	NIM_BOOL result0;
	nimfr("isFilled", "tableimpl.nim")
	result0 = (NIM_BOOL)0;
	nimln(18, "tableimpl.nim");
	nimln(347, "system.nim");
	nimln(18, "tableimpl.nim");
	result0 = !((hcode0 == ((NI) 0)));
	popFrame();
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, nexttry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h0, NI maxhash0) {
	NI result0;
	NI T_ln5vuDpFyDrAqQbYD2g52Q_6;
	nimfr("nextTry", "tableimpl.nim")
	result0 = (NI)0;
	nimln(28, "tableimpl.nim");
	T_ln5vuDpFyDrAqQbYD2g52Q_6 = addInt(h0, ((NI) 1));
	result0 = (NI)((NI)(T_ln5vuDpFyDrAqQbYD2g52Q_6) & maxhash0);
	popFrame();
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, rawget_E9aV5vakSLJS0MAIqaecQsQtables)(Table_bnna5wr180tUeaeDFxJ4xA t0, int key0, NI* hc0) {
	NI result0;
	NI h0;
	NI T_ln5vuDpFyDrAqQbYD2g52Q_7;
	nimfr("rawGet", "tableimpl.nim")
{	result0 = (NI)0;
	nimln(43, "tableimpl.nim");
	(*hc0) = hash_9c3uvkGO9cpD9a7QU6mLwadLAselectors(key0);
	nimln(53, "tableimpl.nim");
	{
		if (!((*hc0) == ((NI) 0))) goto LA3;
		nimln(45, "tableimpl.nim");
		(*hc0) = ((NI) 314159265);
	}
	LA3: ;
	nimln(31, "tableimpl.nim");
	nimln(116, "tables.nim");
	h0 = (NI)((*hc0) & (t0.data ? (t0.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC7;
			if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
			LOC7 = (NIM_BOOL)0;
			LOC7 = isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t0.data->data[h0].Field0);
			if (!LOC7) goto LA6;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC10;
				LOC10 = (NIM_BOOL)0;
				if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
				LOC10 = (t0.data->data[h0].Field0 == (*hc0));
				if (!(LOC10)) goto LA11;
				if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
				LOC10 = (t0.data->data[h0].Field1 == key0);
				LA11: ;
				if (!LOC10) goto LA12;
				nimln(38, "tableimpl.nim");
				result0 = h0;
				goto BeforeRet;
			}
			LA12: ;
			nimln(39, "tableimpl.nim");
			nimln(116, "tables.nim");
			h0 = nexttry_OLPhxSyW9bte5CwHzzQVhfAtables(h0, (t0.data ? (t0.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln(75, "tableimpl.nim");
	nimln(40, "tableimpl.nim");
	T_ln5vuDpFyDrAqQbYD2g52Q_7 = subInt(((NI) -1), h0);
	result0 = (NI)(T_ln5vuDpFyDrAqQbYD2g52Q_7);
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NI, rawgetknownhc_sVNCrVempRVYb0DwgWRB0Atables)(Table_bnna5wr180tUeaeDFxJ4xA t0, int key0, NI hc0) {
	NI result0;
	NI h0;
	NI T_ln5vuDpFyDrAqQbYD2g52Q_8;
	nimfr("rawGetKnownHC", "tableimpl.nim")
{	result0 = (NI)0;
	nimln(31, "tableimpl.nim");
	nimln(116, "tables.nim");
	h0 = (NI)(hc0 & (t0.data ? (t0.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC3;
			if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
			LOC3 = (NIM_BOOL)0;
			LOC3 = isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t0.data->data[h0].Field0);
			if (!LOC3) goto LA2;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = (NIM_BOOL)0;
				if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
				LOC6 = (t0.data->data[h0].Field0 == hc0);
				if (!(LOC6)) goto LA7;
				if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
				LOC6 = (t0.data->data[h0].Field1 == key0);
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(38, "tableimpl.nim");
				result0 = h0;
				goto BeforeRet;
			}
			LA8: ;
			nimln(39, "tableimpl.nim");
			nimln(116, "tables.nim");
			h0 = nexttry_OLPhxSyW9bte5CwHzzQVhfAtables(h0, (t0.data ? (t0.data->Sup.len-1) : -1));
		} LA2: ;
	}
	nimln(69, "tableimpl.nim");
	nimln(40, "tableimpl.nim");
	T_ln5vuDpFyDrAqQbYD2g52Q_8 = subInt(((NI) -1), h0);
	result0 = (NI)(T_ln5vuDpFyDrAqQbYD2g52Q_8);
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(struct epoll_event, createeventstruct_7vZrkYak2uWtlsjSDvVhgw)(Event_nI40bZzTyYVrl763dZ9aHDg_Set events0, int fd0) {
	struct epoll_event result0;
	nimfr("createEventStruct", "selectors.nim")
	memset((void*)(&result0), 0, sizeof(result0));
	nimln(95, "selectors.nim");
	{
		if (!((events0 &(1U<<((NU)(((Event_nI40bZzTyYVrl763dZ9aHDg) 0))&7U)))!=0)) goto LA3;
		nimln(96, "selectors.nim");
		result0.events = ((NU32) 1);
	}
	LA3: ;
	nimln(97, "selectors.nim");
	{
		if (!((events0 &(1U<<((NU)(((Event_nI40bZzTyYVrl763dZ9aHDg) 1))&7U)))!=0)) goto LA7;
		nimln(98, "selectors.nim");
		result0.events = (unsigned int)(result0.events | ((NI) 4));
	}
	LA7: ;
	nimln(99, "selectors.nim");
	result0.events = (unsigned int)(result0.events | ((NI) 8192));
	nimln(100, "selectors.nim");
	result0.data.fd = fd0;
	popFrame();
	return result0;
}

N_NIMCALL(void, register_QCHaUKprAzyUegaWtXEnGw)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0, Event_nI40bZzTyYVrl763dZ9aHDg_Set events0, TNimObject* data0) {
	struct epoll_event event0;
	Selectorkey_gE60aCfYXV1Nf1VTfPbepw LOC11;
	nimfr("register", "selectors.nim")
	nimln(104, "selectors.nim");
	event0 = createeventstruct_7vZrkYak2uWtlsjSDvVhgw(events0, fd0);
	nimln(105, "selectors.nim");
	{
		nimln(347, "system.nim");
		nimln(105, "selectors.nim");
		if (!!((events0 == 0))) goto LA3;
		nimln(106, "selectors.nim");
		{
			int LOC7;
			NI32 LOC10;
			nimln(347, "system.nim");
			nimln(106, "selectors.nim");
			LOC7 = (int)0;
			LOC7 = epoll_ctl((*s0).epollfd, ((int) 1), fd0, (&event0));
			if (!!((LOC7 == ((NI32) 0)))) goto LA8;
			nimln(107, "selectors.nim");
			LOC10 = (NI32)0;
			LOC10 = oslasterror_pMOMIZAQaKFp1XoL58mjVg();
			raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC10, ((NimStringDesc*) &T_ln5vuDpFyDrAqQbYD2g52Q_9));
		}
		LA8: ;
	}
	LA3: ;
	nimln(109, "selectors.nim");
	memset((void*)(&LOC11), 0, sizeof(LOC11));
	memset((void*)(&LOC11), 0, sizeof(LOC11));
	LOC11.fd = fd0;
	LOC11.events = events0;
	LOC11.data = data0;
	HEX5BHEX5DHEX3D_3jMA6nwaCZ3e6Iyj5brtkg((&(*s0).fds), fd0, LOC11);
	popFrame();
}

N_NIMCALL(void, update_VzJ8OVqBzjqu4C23Nq9bPvg)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0, Event_nI40bZzTyYVrl763dZ9aHDg_Set events0) {
	nimfr("update", "selectors.nim")
	nimln(112, "selectors.nim");
	{
		Selectorkey_gE60aCfYXV1Nf1VTfPbepw* LOC3;
		nimln(347, "system.nim");
		nimln(112, "selectors.nim");
		LOC3 = (Selectorkey_gE60aCfYXV1Nf1VTfPbepw*)0;
		LOC3 = HEX5BHEX5D_Sd5XGNdJD9bEXX0z89aJkm7g((&(*s0).fds), fd0);
		if (!!(((*LOC3).events == events0))) goto LA4;
		nimln(113, "selectors.nim");
		{
			Selectorkey_gE60aCfYXV1Nf1VTfPbepw* LOC16;
			if (!(events0 == 0)) goto LA8;
			nimln(119, "selectors.nim");
			{
				int LOC12;
				NI32 LOC15;
				nimln(347, "system.nim");
				nimln(119, "selectors.nim");
				LOC12 = (int)0;
				LOC12 = epoll_ctl((*s0).epollfd, ((int) 2), fd0, NIM_NIL);
				if (!!((LOC12 == ((NI32) 0)))) goto LA13;
				nimln(120, "selectors.nim");
				LOC15 = (NI32)0;
				LOC15 = oslasterror_pMOMIZAQaKFp1XoL58mjVg();
				raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC15, ((NimStringDesc*) &T_ln5vuDpFyDrAqQbYD2g52Q_9));
			}
			LA13: ;
			nimln(121, "selectors.nim");
			LOC16 = (Selectorkey_gE60aCfYXV1Nf1VTfPbepw*)0;
			LOC16 = HEX5BHEX5D_Sd5XGNdJD9bEXX0z89aJkm7g((&(*s0).fds), fd0);
			(*LOC16).events = events0;
		}
		goto LA6;
		LA8: ;
		{
			struct epoll_event event0;
			Selectorkey_gE60aCfYXV1Nf1VTfPbepw* LOC36;
			nimln(123, "selectors.nim");
			event0 = createeventstruct_7vZrkYak2uWtlsjSDvVhgw(events0, fd0);
			nimln(124, "selectors.nim");
			{
				Selectorkey_gE60aCfYXV1Nf1VTfPbepw* LOC20;
				LOC20 = (Selectorkey_gE60aCfYXV1Nf1VTfPbepw*)0;
				LOC20 = HEX5BHEX5D_Sd5XGNdJD9bEXX0z89aJkm7g((&(*s0).fds), fd0);
				if (!((*LOC20).events == 0)) goto LA21;
				nimln(127, "selectors.nim");
				{
					int LOC25;
					NI32 LOC28;
					nimln(347, "system.nim");
					nimln(127, "selectors.nim");
					LOC25 = (int)0;
					LOC25 = epoll_ctl((*s0).epollfd, ((int) 1), fd0, (&event0));
					if (!!((LOC25 == ((NI32) 0)))) goto LA26;
					nimln(128, "selectors.nim");
					LOC28 = (NI32)0;
					LOC28 = oslasterror_pMOMIZAQaKFp1XoL58mjVg();
					raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC28, ((NimStringDesc*) &T_ln5vuDpFyDrAqQbYD2g52Q_9));
				}
				LA26: ;
			}
			goto LA18;
			LA21: ;
			{
				nimln(130, "selectors.nim");
				{
					int LOC32;
					NI32 LOC35;
					nimln(347, "system.nim");
					nimln(130, "selectors.nim");
					LOC32 = (int)0;
					LOC32 = epoll_ctl((*s0).epollfd, ((int) 3), fd0, (&event0));
					if (!!((LOC32 == ((NI32) 0)))) goto LA33;
					nimln(131, "selectors.nim");
					LOC35 = (NI32)0;
					LOC35 = oslasterror_pMOMIZAQaKFp1XoL58mjVg();
					raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC35, ((NimStringDesc*) &T_ln5vuDpFyDrAqQbYD2g52Q_9));
				}
				LA33: ;
			}
			LA18: ;
			nimln(132, "selectors.nim");
			LOC36 = (Selectorkey_gE60aCfYXV1Nf1VTfPbepw*)0;
			LOC36 = HEX5BHEX5D_Sd5XGNdJD9bEXX0z89aJkm7g((&(*s0).fds), fd0);
			(*LOC36).events = events0;
		}
		LA6: ;
	}
	LA4: ;
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, unregister_2fDHSfeVBEEsLBSaUEUOzA)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0) {
	nimfr("unregister", "selectors.nim")
	nimln(135, "selectors.nim");
	{
		Selectorkey_gE60aCfYXV1Nf1VTfPbepw* LOC3;
		nimln(347, "system.nim");
		nimln(135, "selectors.nim");
		LOC3 = (Selectorkey_gE60aCfYXV1Nf1VTfPbepw*)0;
		LOC3 = HEX5BHEX5D_Sd5XGNdJD9bEXX0z89aJkm7g((&(*s0).fds), fd0);
		if (!!(((*LOC3).events == 0))) goto LA4;
		nimln(136, "selectors.nim");
		{
			int LOC8;
			NI32 err0;
			nimln(347, "system.nim");
			nimln(136, "selectors.nim");
			LOC8 = (int)0;
			LOC8 = epoll_ctl((*s0).epollfd, ((int) 2), fd0, NIM_NIL);
			if (!!((LOC8 == ((NI32) 0)))) goto LA9;
			nimln(137, "selectors.nim");
			err0 = oslasterror_pMOMIZAQaKFp1XoL58mjVg();
			nimln(138, "selectors.nim");
			{
				nimln(1130, "system.nim");
				nimln(138, "selectors.nim");
				if (!!((err0 == ((NI)chckRange(ENOENT, ((NI) 0), ((NI) 65535))) || err0 == ((NI)chckRange(EBADF, ((NI) 0), ((NI) 65535)))))) goto LA13;
				nimln(140, "selectors.nim");
				raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(err0, ((NimStringDesc*) &T_ln5vuDpFyDrAqQbYD2g52Q_9));
			}
			LA13: ;
		}
		LA9: ;
	}
	LA4: ;
	nimln(141, "selectors.nim");
	del_MPpoRTFhkQVAZDvswQqiSA((&(*s0).fds), fd0);
	popFrame();
}

N_NIMCALL(void, close_MwlkQPYetm2csv9bp6JpPWw)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0) {
	nimfr("close", "selectors.nim")
	nimln(145, "selectors.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(347, "system.nim");
		nimln(145, "selectors.nim");
		LOC3 = (int)0;
		LOC3 = close((*s0).epollfd);
		if (!!((LOC3 == ((NI32) 0)))) goto LA4;
		LOC6 = (NI32)0;
		LOC6 = oslasterror_pMOMIZAQaKFp1XoL58mjVg();
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC6, ((NimStringDesc*) &T_ln5vuDpFyDrAqQbYD2g52Q_9));
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, epollhasfd_xj6cssVSm8j9bytjWGf29cUw)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0) {
	NIM_BOOL result0;
	struct epoll_event event0;
	Selectorkey_gE60aCfYXV1Nf1VTfPbepw LOC1;
	nimfr("epollHasFd", "selectors.nim")
{	result0 = (NIM_BOOL)0;
	nimln(148, "selectors.nim");
	result0 = NIM_TRUE;
	nimln(149, "selectors.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	HEX5BHEX5D_QeLiydbSBk8OZJj1o5uN0w((*s0).fds, fd0, (&LOC1));
	event0 = createeventstruct_7vZrkYak2uWtlsjSDvVhgw(LOC1.events, fd0);
	nimln(150, "selectors.nim");
	{
		int LOC4;
		NI32 err0;
		nimln(347, "system.nim");
		nimln(150, "selectors.nim");
		LOC4 = (int)0;
		LOC4 = epoll_ctl((*s0).epollfd, ((int) 3), fd0, (&event0));
		if (!!((LOC4 == ((NI32) 0)))) goto LA5;
		nimln(151, "selectors.nim");
		err0 = oslasterror_pMOMIZAQaKFp1XoL58mjVg();
		nimln(152, "selectors.nim");
		{
			if (!(err0 == ((NI)chckRange(ENOENT, ((NI) 0), ((NI) 65535))) || err0 == ((NI)chckRange(EBADF, ((NI) 0), ((NI) 65535))))) goto LA9;
			nimln(153, "selectors.nim");
			result0 = NIM_FALSE;
			goto BeforeRet;
		}
		LA9: ;
		nimln(154, "selectors.nim");
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(err0, ((NimStringDesc*) &T_ln5vuDpFyDrAqQbYD2g52Q_9));
	}
	LA5: ;
	}BeforeRet: ;
	popFrame();
	return result0;
}
static N_NIMCALL(void, Marker_TY_bkMUR8maranmy38dEG39cHA)(void* p, NI op) {
	TY_bkMUR8maranmy38dEG39cHA* a;
	NI LOC1;
	a = (TY_bkMUR8maranmy38dEG39cHA*)p;
	LOC1 = (NI)0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field0.data, op);
	}
}

static N_INLINE(void, incref_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0) {
	nimfr("incRef", "gc.nim")
	nimln(232, "gc.nim");
	(*c0).refcount = (NI)((NU64)((*c0).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln(134, "gc.nim");
	result0 = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(220, "gc.nim");
	addzct_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c0);
	popFrame();
}

static N_INLINE(void, decref_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0) {
	nimfr("decRef", "gc.nim")
	nimln(227, "gc.nim");
	{
		(*c0).refcount -= ((NI) 8);
		if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(228, "gc.nim");
		rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system(c0);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest0, void* src0) {
	nimfr("asgnRef", "gc.nim")
	nimln(273, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* LOC5;
		nimln(347, "system.nim");
		nimln(273, "gc.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		LOC5 = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		LOC5 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src0);
		incref_9cAA5YuQAAC3MVbnGeV86swsystem(LOC5);
	}
	LA3: ;
	nimln(274, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* LOC10;
		nimln(347, "system.nim");
		nimln(274, "gc.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA8;
		LOC10 = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		LOC10 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest0));
		decref_MV4BBk6J1qu70IbBxwEn4wsystem(LOC10);
	}
	LA8: ;
	nimln(275, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

N_NIMCALL(TY_bkMUR8maranmy38dEG39cHA*, select_HpncstI132GvQ9ceBTIOgrg)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, NI timeout0) {
	TY_bkMUR8maranmy38dEG39cHA* result0;
	int evnum0;
	nimfr("select", "selectors.nim")
{	result0 = (TY_bkMUR8maranmy38dEG39cHA*)0;
	nimln(157, "selectors.nim");
	result0 = (TY_bkMUR8maranmy38dEG39cHA*) newSeq((&NTI_bkMUR8maranmy38dEG39cHA), 0);
	nimln(158, "selectors.nim");
	evnum0 = epoll_wait((*s0).epollfd, (&(*s0).events[(((NI) 0))- 0]), ((int) 64), ((int)chckRange(timeout0, ((int) (-2147483647 -1)), ((int) 2147483647))));
	nimln(159, "selectors.nim");
	{
		NI32 err0;
		if (!(evnum0 < ((NI32) 0))) goto LA3;
		nimln(160, "selectors.nim");
		err0 = oslasterror_pMOMIZAQaKFp1XoL58mjVg();
		nimln(161, "selectors.nim");
		{
			if (!(err0 == EINTR)) goto LA7;
			nimln(162, "selectors.nim");
			result0 = (TY_bkMUR8maranmy38dEG39cHA*) newSeq((&NTI_bkMUR8maranmy38dEG39cHA), 0);
			goto BeforeRet;
		}
		LA7: ;
		nimln(163, "selectors.nim");
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(err0, ((NimStringDesc*) &T_ln5vuDpFyDrAqQbYD2g52Q_9));
	}
	LA3: ;
	nimln(164, "selectors.nim");
	{
		if (!(evnum0 == ((NI32) 0))) goto LA11;
		result0 = (TY_bkMUR8maranmy38dEG39cHA*) newSeq((&NTI_bkMUR8maranmy38dEG39cHA), 0);
		goto BeforeRet;
	}
	LA11: ;
	{
		int i_G2aNgotvyNgCmEeJt7MaUg;
		int HEX3Atmp_VZtRxmNtWeoJoc6mALBNPw;
		NI res_4x6E9aozdZBDkmdCLxZt9bjQ;
		i_G2aNgotvyNgCmEeJt7MaUg = (int)0;
		HEX3Atmp_VZtRxmNtWeoJoc6mALBNPw = (int)0;
		nimln(165, "selectors.nim");
		HEX3Atmp_VZtRxmNtWeoJoc6mALBNPw = subInt(evnum0, 1);
		nimln(1908, "system.nim");
		res_4x6E9aozdZBDkmdCLxZt9bjQ = ((NI) 0);
		{
			nimln(1909, "system.nim");
			while (1) {
				int fd0;
				Event_nI40bZzTyYVrl763dZ9aHDg_Set evset0;
				Selectorkey_gE60aCfYXV1Nf1VTfPbepw selectorkey0;
				Selectorkey_gE60aCfYXV1Nf1VTfPbepw* LOC30;
				TY_nEEz1gjcivYloysklmeNTg LOC35;
				NI T_ln5vuDpFyDrAqQbYD2g52Q_12;
				nimln(1908, "system.nim");
				if (!(res_4x6E9aozdZBDkmdCLxZt9bjQ <= ((NI) (HEX3Atmp_VZtRxmNtWeoJoc6mALBNPw)))) goto LA15;
				nimln(1910, "system.nim");
				i_G2aNgotvyNgCmEeJt7MaUg = ((int)chckRange(res_4x6E9aozdZBDkmdCLxZt9bjQ, ((int) (-2147483647 -1)), ((int) 2147483647)));
				nimln(166, "selectors.nim");
				if ((NU)(i_G2aNgotvyNgCmEeJt7MaUg) > (NU)(63)) raiseIndexError();
				fd0 = (*s0).events[(i_G2aNgotvyNgCmEeJt7MaUg)- 0].data.fd;
				nimln(168, "selectors.nim");
				evset0 = 0;
				nimln(169, "selectors.nim");
				{
					NIM_BOOL LOC18;
					LOC18 = (NIM_BOOL)0;
					nimln(347, "system.nim");
					nimln(169, "selectors.nim");
					if ((NU)(i_G2aNgotvyNgCmEeJt7MaUg) > (NU)(63)) raiseIndexError();
					LOC18 = !(((unsigned int)((*s0).events[(i_G2aNgotvyNgCmEeJt7MaUg)- 0].events & ((NI) 8)) == ((NI) 0)));
					if (LOC18) goto LA19;
					nimln(347, "system.nim");
					nimln(169, "selectors.nim");
					if ((NU)(i_G2aNgotvyNgCmEeJt7MaUg) > (NU)(63)) raiseIndexError();
					LOC18 = !(((unsigned int)((*s0).events[(i_G2aNgotvyNgCmEeJt7MaUg)- 0].events & ((NI) 16)) == ((NI) 0)));
					LA19: ;
					if (!LOC18) goto LA20;
					evset0 = (evset0 | 4);
				}
				LA20: ;
				nimln(170, "selectors.nim");
				{
					nimln(347, "system.nim");
					nimln(170, "selectors.nim");
					if ((NU)(i_G2aNgotvyNgCmEeJt7MaUg) > (NU)(63)) raiseIndexError();
					if (!!((((NI) ((NU32)((*s0).events[(i_G2aNgotvyNgCmEeJt7MaUg)- 0].events & ((NI) 1)))) == ((NI) 0)))) goto LA24;
					evset0 = (evset0 | 1);
				}
				LA24: ;
				nimln(171, "selectors.nim");
				{
					nimln(347, "system.nim");
					nimln(171, "selectors.nim");
					if ((NU)(i_G2aNgotvyNgCmEeJt7MaUg) > (NU)(63)) raiseIndexError();
					if (!!(((unsigned int)((*s0).events[(i_G2aNgotvyNgCmEeJt7MaUg)- 0].events & ((NI) 4)) == ((NI) 0)))) goto LA28;
					evset0 = (evset0 | 2);
				}
				LA28: ;
				memset((void*)(&selectorkey0), 0, sizeof(selectorkey0));
				nimln(172, "selectors.nim");
				LOC30 = (Selectorkey_gE60aCfYXV1Nf1VTfPbepw*)0;
				LOC30 = HEX5BHEX5D_Sd5XGNdJD9bEXX0z89aJkm7g((&(*s0).fds), fd0);
				selectorkey0.fd = (*LOC30).fd;
				selectorkey0.events = (*LOC30).events;
				selectorkey0.data = (*LOC30).data;
				nimln(173, "selectors.nim");
				{
					if (!!(!((selectorkey0.fd == ((int) 0))))) goto LA33;
					failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &T_ln5vuDpFyDrAqQbYD2g52Q_11));
				}
				LA33: ;
				nimln(174, "selectors.nim");
				memset((void*)(&LOC35), 0, sizeof(LOC35));
				LOC35.Field0.fd = selectorkey0.fd;
				LOC35.Field0.events = selectorkey0.events;
				LOC35.Field0.data = selectorkey0.data;
				LOC35.Field1 = evset0;
				result0 = (TY_bkMUR8maranmy38dEG39cHA*) incrSeqV2(&(result0)->Sup, sizeof(TY_nEEz1gjcivYloysklmeNTg));
				result0->data[result0->Sup.len].Field0.fd = LOC35.Field0.fd;
				result0->data[result0->Sup.len].Field0.events = LOC35.Field0.events;
				asgnRef((void**) (&result0->data[result0->Sup.len].Field0.data), LOC35.Field0.data);
				result0->data[result0->Sup.len].Field1 = LOC35.Field1;
				++result0->Sup.len;
				nimln(1908, "system.nim");
				T_ln5vuDpFyDrAqQbYD2g52Q_12 = addInt(res_4x6E9aozdZBDkmdCLxZt9bjQ, ((NI) 1));
				res_4x6E9aozdZBDkmdCLxZt9bjQ = (NI)(T_ln5vuDpFyDrAqQbYD2g52Q_12);
			} LA15: ;
		}
	}
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(void, newselector_tcCxAL6x4L39akwZ39aVA6Tg)(Selector_X89cGFWVbzYzXTnuQzGngmA* Result) {
	nimfr("newSelector", "selectors.nim")
	nimln(179, "selectors.nim");
	(*Result).epollfd = epoll_create(((int) 64));
	nimln(180, "selectors.nim");
	{
		NI32 LOC5;
		if (!((*Result).epollfd < ((NI32) 0))) goto LA3;
		nimln(181, "selectors.nim");
		LOC5 = (NI32)0;
		LOC5 = oslasterror_pMOMIZAQaKFp1XoL58mjVg();
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC5, ((NimStringDesc*) &T_ln5vuDpFyDrAqQbYD2g52Q_9));
	}
	LA3: ;
	nimln(185, "selectors.nim");
	inittable_Hx3BnoioZlM0c7U4t1cT0w(((NI) 64), (&(*Result).fds));
	popFrame();
}

N_NIMCALL(NIM_BOOL, contains_xj6cssVSm8j9bytjWGf29cUw_2)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0) {
	NIM_BOOL result0;
	nimfr("contains", "selectors.nim")
{	result0 = (NIM_BOOL)0;
	nimln(189, "selectors.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = haskey_PW8rl8fmQKFFAo5bXDIQTQ((*s0).fds, fd0);
		if (!LOC3) goto LA4;
		nimln(191, "selectors.nim");
		{
			Selectorkey_gE60aCfYXV1Nf1VTfPbepw LOC8;
			nimln(347, "system.nim");
			nimln(191, "selectors.nim");
			memset((void*)(&LOC8), 0, sizeof(LOC8));
			HEX5BHEX5D_QeLiydbSBk8OZJj1o5uN0w((*s0).fds, fd0, (&LOC8));
			if (!!((LOC8.events == 0))) goto LA9;
			nimln(192, "selectors.nim");
			result0 = epollhasfd_xj6cssVSm8j9bytjWGf29cUw(s0, fd0);
		}
		goto LA6;
		LA9: ;
		{
			nimln(194, "selectors.nim");
			result0 = NIM_TRUE;
		}
		LA6: ;
	}
	goto LA1;
	LA4: ;
	{
		nimln(196, "selectors.nim");
		result0 = NIM_FALSE;
		goto BeforeRet;
	}
	LA1: ;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(void, HEX5BHEX5D_cRbUBRdnAVbKu6ptO8AZLQ)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, int fd0, Selectorkey_gE60aCfYXV1Nf1VTfPbepw* Result) {
	nimfr("[]", "selectors.nim")
{	nimln(200, "selectors.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_gE60aCfYXV1Nf1VTfPbepw));
	HEX5BHEX5D_QeLiydbSBk8OZJj1o5uN0w((*s0).fds, fd0, Result);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, contains_Y3zqrOiY8I6fpNd9ahsiVnw)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0, Selectorkey_gE60aCfYXV1Nf1VTfPbepw key0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	Selectorkey_gE60aCfYXV1Nf1VTfPbepw LOC3;
	nimfr("contains", "selectors.nim")
{	result0 = (NIM_BOOL)0;
	nimln(376, "selectors.nim");
	LOC1 = (NIM_BOOL)0;
	LOC1 = contains_xj6cssVSm8j9bytjWGf29cUw_2(s0, key0.fd);
	if (!(LOC1)) goto LA2;
	memset((void*)(&LOC3), 0, sizeof(LOC3));
	HEX5BHEX5D_QeLiydbSBk8OZJj1o5uN0w((*s0).fds, key0.fd, (&LOC3));
	LOC1 = HEX3DHEX3D_fW6ECiKEQQ03nZ1qZlamvA(LOC3, key0);
	LA2: ;
	result0 = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NI, len_6bMoxDMwI4Nef9a1VY5tbmw)(Selector_X89cGFWVbzYzXTnuQzGngmA* s0) {
	NI result0;
	nimfr("len", "selectors.nim")
{	result0 = (NI)0;
	nimln(381, "selectors.nim");
	result0 = len_Q1GsJskrVK5e0DS9cZT9bODg((*s0).fds);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsInit000)(void) {
	nimfr("selectors", "selectors.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsDatInit000)(void) {
static TNimNode* T_ln5vuDpFyDrAqQbYD2g52Q_2[3];
static TNimNode* T_ln5vuDpFyDrAqQbYD2g52Q_3[3];
NI T_ln5vuDpFyDrAqQbYD2g52Q_5;
static char* NIM_CONST T_ln5vuDpFyDrAqQbYD2g52Q_4[3] = {
"EvRead", 
"EvWrite", 
"EvError"};
static TNimNode* T_ln5vuDpFyDrAqQbYD2g52Q_10[2];
static TNimNode* T_ln5vuDpFyDrAqQbYD2g52Q_13[3];
static TNimNode T_ln5vuDpFyDrAqQbYD2g52Q_0[16];
NTI_gE60aCfYXV1Nf1VTfPbepw.size = sizeof(Selectorkey_gE60aCfYXV1Nf1VTfPbepw);
NTI_gE60aCfYXV1Nf1VTfPbepw.kind = 18;
NTI_gE60aCfYXV1Nf1VTfPbepw.base = 0;
T_ln5vuDpFyDrAqQbYD2g52Q_2[0] = &T_ln5vuDpFyDrAqQbYD2g52Q_0[1];
T_ln5vuDpFyDrAqQbYD2g52Q_0[1].kind = 1;
T_ln5vuDpFyDrAqQbYD2g52Q_0[1].offset = offsetof(Selectorkey_gE60aCfYXV1Nf1VTfPbepw, fd);
T_ln5vuDpFyDrAqQbYD2g52Q_0[1].typ = (&NTI_nlCscttRCss70IBTyuBqnA);
T_ln5vuDpFyDrAqQbYD2g52Q_0[1].name = "fd";
T_ln5vuDpFyDrAqQbYD2g52Q_2[1] = &T_ln5vuDpFyDrAqQbYD2g52Q_0[2];
NTI_nI40bZzTyYVrl763dZ9aHDg.size = sizeof(Event_nI40bZzTyYVrl763dZ9aHDg);
NTI_nI40bZzTyYVrl763dZ9aHDg.kind = 14;
NTI_nI40bZzTyYVrl763dZ9aHDg.base = 0;
NTI_nI40bZzTyYVrl763dZ9aHDg.flags = 3;
for (T_ln5vuDpFyDrAqQbYD2g52Q_5 = 0; T_ln5vuDpFyDrAqQbYD2g52Q_5 < 3; T_ln5vuDpFyDrAqQbYD2g52Q_5++) {
T_ln5vuDpFyDrAqQbYD2g52Q_0[T_ln5vuDpFyDrAqQbYD2g52Q_5+3].kind = 1;
T_ln5vuDpFyDrAqQbYD2g52Q_0[T_ln5vuDpFyDrAqQbYD2g52Q_5+3].offset = T_ln5vuDpFyDrAqQbYD2g52Q_5;
T_ln5vuDpFyDrAqQbYD2g52Q_0[T_ln5vuDpFyDrAqQbYD2g52Q_5+3].name = T_ln5vuDpFyDrAqQbYD2g52Q_4[T_ln5vuDpFyDrAqQbYD2g52Q_5];
T_ln5vuDpFyDrAqQbYD2g52Q_3[T_ln5vuDpFyDrAqQbYD2g52Q_5] = &T_ln5vuDpFyDrAqQbYD2g52Q_0[T_ln5vuDpFyDrAqQbYD2g52Q_5+3];
}
T_ln5vuDpFyDrAqQbYD2g52Q_0[6].len = 3; T_ln5vuDpFyDrAqQbYD2g52Q_0[6].kind = 2; T_ln5vuDpFyDrAqQbYD2g52Q_0[6].sons = &T_ln5vuDpFyDrAqQbYD2g52Q_3[0];
NTI_nI40bZzTyYVrl763dZ9aHDg.node = &T_ln5vuDpFyDrAqQbYD2g52Q_0[6];
NTI_YIRsZrDT89buh37M5yeUgng.size = sizeof(Event_nI40bZzTyYVrl763dZ9aHDg_Set);
NTI_YIRsZrDT89buh37M5yeUgng.kind = 19;
NTI_YIRsZrDT89buh37M5yeUgng.base = (&NTI_nI40bZzTyYVrl763dZ9aHDg);
NTI_YIRsZrDT89buh37M5yeUgng.flags = 3;
T_ln5vuDpFyDrAqQbYD2g52Q_0[7].len = 0; T_ln5vuDpFyDrAqQbYD2g52Q_0[7].kind = 0;
NTI_YIRsZrDT89buh37M5yeUgng.node = &T_ln5vuDpFyDrAqQbYD2g52Q_0[7];
T_ln5vuDpFyDrAqQbYD2g52Q_0[2].kind = 1;
T_ln5vuDpFyDrAqQbYD2g52Q_0[2].offset = offsetof(Selectorkey_gE60aCfYXV1Nf1VTfPbepw, events);
T_ln5vuDpFyDrAqQbYD2g52Q_0[2].typ = (&NTI_YIRsZrDT89buh37M5yeUgng);
T_ln5vuDpFyDrAqQbYD2g52Q_0[2].name = "events";
T_ln5vuDpFyDrAqQbYD2g52Q_2[2] = &T_ln5vuDpFyDrAqQbYD2g52Q_0[8];
T_ln5vuDpFyDrAqQbYD2g52Q_0[8].kind = 1;
T_ln5vuDpFyDrAqQbYD2g52Q_0[8].offset = offsetof(Selectorkey_gE60aCfYXV1Nf1VTfPbepw, data);
T_ln5vuDpFyDrAqQbYD2g52Q_0[8].typ = (&NTI_1VeTzqrFu2VJ4a6cGvuoyA);
T_ln5vuDpFyDrAqQbYD2g52Q_0[8].name = "data";
T_ln5vuDpFyDrAqQbYD2g52Q_0[0].len = 3; T_ln5vuDpFyDrAqQbYD2g52Q_0[0].kind = 2; T_ln5vuDpFyDrAqQbYD2g52Q_0[0].sons = &T_ln5vuDpFyDrAqQbYD2g52Q_2[0];
NTI_gE60aCfYXV1Nf1VTfPbepw.node = &T_ln5vuDpFyDrAqQbYD2g52Q_0[0];
NTI_nEEz1gjcivYloysklmeNTg.size = sizeof(TY_nEEz1gjcivYloysklmeNTg);
NTI_nEEz1gjcivYloysklmeNTg.kind = 18;
NTI_nEEz1gjcivYloysklmeNTg.base = 0;
T_ln5vuDpFyDrAqQbYD2g52Q_10[0] = &T_ln5vuDpFyDrAqQbYD2g52Q_0[10];
T_ln5vuDpFyDrAqQbYD2g52Q_0[10].kind = 1;
T_ln5vuDpFyDrAqQbYD2g52Q_0[10].offset = offsetof(TY_nEEz1gjcivYloysklmeNTg, Field0);
T_ln5vuDpFyDrAqQbYD2g52Q_0[10].typ = (&NTI_gE60aCfYXV1Nf1VTfPbepw);
T_ln5vuDpFyDrAqQbYD2g52Q_0[10].name = "Field0";
T_ln5vuDpFyDrAqQbYD2g52Q_10[1] = &T_ln5vuDpFyDrAqQbYD2g52Q_0[11];
T_ln5vuDpFyDrAqQbYD2g52Q_0[11].kind = 1;
T_ln5vuDpFyDrAqQbYD2g52Q_0[11].offset = offsetof(TY_nEEz1gjcivYloysklmeNTg, Field1);
T_ln5vuDpFyDrAqQbYD2g52Q_0[11].typ = (&NTI_YIRsZrDT89buh37M5yeUgng);
T_ln5vuDpFyDrAqQbYD2g52Q_0[11].name = "Field1";
T_ln5vuDpFyDrAqQbYD2g52Q_0[9].len = 2; T_ln5vuDpFyDrAqQbYD2g52Q_0[9].kind = 2; T_ln5vuDpFyDrAqQbYD2g52Q_0[9].sons = &T_ln5vuDpFyDrAqQbYD2g52Q_10[0];
NTI_nEEz1gjcivYloysklmeNTg.node = &T_ln5vuDpFyDrAqQbYD2g52Q_0[9];
NTI_bkMUR8maranmy38dEG39cHA.size = sizeof(TY_bkMUR8maranmy38dEG39cHA*);
NTI_bkMUR8maranmy38dEG39cHA.kind = 24;
NTI_bkMUR8maranmy38dEG39cHA.base = (&NTI_nEEz1gjcivYloysklmeNTg);
NTI_bkMUR8maranmy38dEG39cHA.marker = Marker_TY_bkMUR8maranmy38dEG39cHA;
NTI_X89cGFWVbzYzXTnuQzGngmA.size = sizeof(Selector_X89cGFWVbzYzXTnuQzGngmA);
NTI_X89cGFWVbzYzXTnuQzGngmA.kind = 18;
NTI_X89cGFWVbzYzXTnuQzGngmA.base = 0;
T_ln5vuDpFyDrAqQbYD2g52Q_13[0] = &T_ln5vuDpFyDrAqQbYD2g52Q_0[13];
T_ln5vuDpFyDrAqQbYD2g52Q_0[13].kind = 1;
T_ln5vuDpFyDrAqQbYD2g52Q_0[13].offset = offsetof(Selector_X89cGFWVbzYzXTnuQzGngmA, epollfd);
T_ln5vuDpFyDrAqQbYD2g52Q_0[13].typ = (&NTI_nlCscttRCss70IBTyuBqnA);
T_ln5vuDpFyDrAqQbYD2g52Q_0[13].name = "epollFD";
T_ln5vuDpFyDrAqQbYD2g52Q_13[1] = &T_ln5vuDpFyDrAqQbYD2g52Q_0[14];
NTI_iNLNjoAj1poPzqx9biLwG9bA.size = sizeof(TY_iNLNjoAj1poPzqx9biLwG9bA);
NTI_iNLNjoAj1poPzqx9biLwG9bA.kind = 16;
NTI_iNLNjoAj1poPzqx9biLwG9bA.base = (&NTI_zUGEEklrq4WOkixy0PK9cIw);
NTI_iNLNjoAj1poPzqx9biLwG9bA.flags = 3;
T_ln5vuDpFyDrAqQbYD2g52Q_0[14].kind = 1;
T_ln5vuDpFyDrAqQbYD2g52Q_0[14].offset = offsetof(Selector_X89cGFWVbzYzXTnuQzGngmA, events);
T_ln5vuDpFyDrAqQbYD2g52Q_0[14].typ = (&NTI_iNLNjoAj1poPzqx9biLwG9bA);
T_ln5vuDpFyDrAqQbYD2g52Q_0[14].name = "events";
T_ln5vuDpFyDrAqQbYD2g52Q_13[2] = &T_ln5vuDpFyDrAqQbYD2g52Q_0[15];
T_ln5vuDpFyDrAqQbYD2g52Q_0[15].kind = 1;
T_ln5vuDpFyDrAqQbYD2g52Q_0[15].offset = offsetof(Selector_X89cGFWVbzYzXTnuQzGngmA, fds);
T_ln5vuDpFyDrAqQbYD2g52Q_0[15].typ = (&NTI_bnna5wr180tUeaeDFxJ4xA);
T_ln5vuDpFyDrAqQbYD2g52Q_0[15].name = "fds";
T_ln5vuDpFyDrAqQbYD2g52Q_0[12].len = 3; T_ln5vuDpFyDrAqQbYD2g52Q_0[12].kind = 2; T_ln5vuDpFyDrAqQbYD2g52Q_0[12].sons = &T_ln5vuDpFyDrAqQbYD2g52Q_13[0];
NTI_X89cGFWVbzYzXTnuQzGngmA.node = &T_ln5vuDpFyDrAqQbYD2g52Q_0[12];
}

