/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/opt/nim/lib -o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_streams.o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_streams.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#include <setjmp.h>
#include <string.h>
#include <stdio.h>
#undef linux
typedef struct Ioerror_9czoZw3pzPyrBmb5zTHY1OQ Ioerror_9czoZw3pzPyrBmb5zTHY1OQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Systemerror_Fjf9b9b2IlzRO2tspHxG3tgg Systemerror_Fjf9b9b2IlzRO2tspHxG3tgg;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct Cellseq_Axo1XVm9aaQueTOldv8le5w Cellseq_Axo1XVm9aaQueTOldv8le5w;
typedef struct Gcheap_1TRH1TZMaVZTnLNcIHuNFQ Gcheap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct Gcstack_7fytPA5bBsob6See21YMRA Gcstack_7fytPA5bBsob6See21YMRA;
typedef struct Memregion_x81NhDv59b8ercDZ9bi85jyg Memregion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct Smallchunk_tXn60W2f8h3jgAYdEmy5NQ Smallchunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct Llchunk_XsENErzHIZV9bhvyJx56wGw Llchunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct Bigchunk_Rv9c70Uhp2TytkX7eH78qEg Bigchunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct Intset_EZObFrE3NC9bIb3YMkY9crZA Intset_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct Avlnode_IaqjtwKhxLEpvDS9bct9blEw Avlnode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct Gcstat_0RwLoVBHZPfUAcLczmfQAg Gcstat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct Cellset_jG87P0AI9aZtss9ccTYBIISQ Cellset_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct Pagedesc_fublkgIY4LG3mT51LU2WHg Pagedesc_fublkgIY4LG3mT51LU2WHg;
typedef struct Sharedlist_9cWkTIPQvNw7gFHMOEzMCLw Sharedlist_9cWkTIPQvNw7gFHMOEzMCLw;
typedef struct SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw;
typedef struct Streamobj_RShkcoDOPnoCVhtpN1hDPQ Streamobj_RShkcoDOPnoCVhtpN1hDPQ;
typedef struct TSafePoint TSafePoint;
typedef struct Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ;
typedef struct Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw;
typedef struct Basechunk_Sdq7WpT6qAH858F5ZEdG3w Basechunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct Freecell_u6M5LHprqzkn9axr04yg9bGQ Freecell_u6M5LHprqzkn9axr04yg9bGQ;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Systemerror_Fjf9b9b2IlzRO2tspHxG3tgg  {
  Exception Sup;
};
struct  Ioerror_9czoZw3pzPyrBmb5zTHY1OQ  {
  Systemerror_Fjf9b9b2IlzRO2tspHxG3tgg Sup;
};
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  Cellseq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  Intset_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
struct  Memregion_x81NhDv59b8ercDZ9bi85jyg  {
NI minlargeobj;
NI maxlargeobj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freesmallchunks;
Llchunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* freechunkslist;
Intset_EZObFrE3NC9bIb3YMkY9crZA chunkstarts;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* root;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* last;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* freeavlnodes;
NIM_BOOL locked;
NIM_BOOL blockchunksizeincrease;
NI nextchunksize;
};
struct  Gcstat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
Pagedesc_fublkgIY4LG3mT51LU2WHg* head;
Pagedesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  Sharedlist_9cWkTIPQvNw7gFHMOEzMCLw  {
SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw* head;
SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw* tail;
pthread_mutex_t lock;
};
struct  Gcheap_1TRH1TZMaVZTnLNcIHuNFQ  {
Gcstack_7fytPA5bBsob6See21YMRA* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq_Axo1XVm9aaQueTOldv8le5w zct;
Cellseq_Axo1XVm9aaQueTOldv8le5w decstack;
Cellseq_Axo1XVm9aaQueTOldv8le5w tempstack;
NI recgclock;
Memregion_x81NhDv59b8ercDZ9bi85jyg region;
Gcstat_0RwLoVBHZPfUAcLczmfQAg stat;
Cellset_jG87P0AI9aZtss9ccTYBIISQ marked;
Cellseq_Axo1XVm9aaQueTOldv8le5w additionalroots;
Sharedlist_9cWkTIPQvNw7gFHMOEzMCLw todispose;
};
typedef N_NIMCALL_PTR(void, TY_cnkJEp9bna8U6yi9aVW9cAJ0Q) (Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
typedef N_NIMCALL_PTR(NIM_BOOL, TY_KjFcmLOhf4VQvVcyLJWXZw) (Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
typedef N_NIMCALL_PTR(void, TY_jlOYFw9cHausuCbPoWx2iiA) (Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI pos0);
typedef N_NIMCALL_PTR(NI, TY_Xzm85qBLb9cf9cu8VOfAr8PQ) (Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
typedef N_NIMCALL_PTR(NI, TY_tjaJtoUzLe1BMUbItlcGhQ) (Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, void* buffer0, NI buflen0);
typedef N_NIMCALL_PTR(void, TY_b9bsIuILxTLVZHPvJBW187A) (Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, void* buffer0, NI buflen0);
struct  Streamobj_RShkcoDOPnoCVhtpN1hDPQ  {
  TNimObject Sup;
TY_cnkJEp9bna8U6yi9aVW9cAJ0Q closeimpl;
TY_KjFcmLOhf4VQvVcyLJWXZw atendimpl;
TY_jlOYFw9cHausuCbPoWx2iiA setpositionimpl;
TY_Xzm85qBLb9cf9cu8VOfAr8PQ getpositionimpl;
TY_tjaJtoUzLe1BMUbItlcGhQ readdataimpl;
TY_tjaJtoUzLe1BMUbItlcGhQ peekdataimpl;
TY_b9bsIuILxTLVZHPvJBW187A writedataimpl;
TY_cnkJEp9bna8U6yi9aVW9cAJ0Q flushimpl;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e0, void* ClEnv);
void* ClEnv;
} TY_KeeAOYBd84Ofsw6Y7LizaQ;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
struct  Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ  {
  Streamobj_RShkcoDOPnoCVhtpN1hDPQ Sup;
NimStringDesc* data;
NI pos;
};
struct  Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw  {
  Streamobj_RShkcoDOPnoCVhtpN1hDPQ Sup;
FILE* f;
};
typedef NU8 Fileseekpos_I9aQjuvWxs8BspGbxwsngWw;
typedef NU8 Filemode_fVUBHvW79bXUw1j55Oo9avSQ;
struct  Gcstack_7fytPA5bBsob6See21YMRA  {
Gcstack_7fytPA5bBsob6See21YMRA* prev;
Gcstack_7fytPA5bBsob6See21YMRA* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk_tXn60W2f8h3jgAYdEmy5NQ  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* next;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
Freecell_u6M5LHprqzkn9axr04yg9bGQ* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
Llchunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  Bigchunk_Rv9c70Uhp2TytkX7eH78qEg  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* next;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NI align;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef Avlnode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  Avlnode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc_fublkgIY4LG3mT51LU2WHg  {
Pagedesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef void* TY_Rrw59cMvNu8cDA9cQDh4v2oA[100];
struct  SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw  {
SharedlistnodeHEX3Aobjecttype_82xHhBDm9bpijSPOyEGz0Hw* next;
NI datalen;
TY_Rrw59cMvNu8cDA9cQDh4v2oA d;
};
struct  Freecell_u6M5LHprqzkn9axr04yg9bGQ  {
Freecell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zerofield;
};
N_NIMCALL(Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*, neweio_lOrpXone7dPkEAOURnfgBw)(NimStringDesc* msg0);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src0);
static N_INLINE(void, nimGCunrefNoCycle)(void* p0);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NOINLINE(void, addzct_fCDI7oO1NNVXXURtxSzsRw)(Cellseq_Axo1XVm9aaQueTOldv8le5w* s0, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NIMCALL(void, flush_4ed7IXme7lqtClFI7s2sTQ)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(void, close_4ed7IXme7lqtClFI7s2sTQ_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(void, close_dvxY0goRsVRNjhrDyOruTQ)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, Streamobj_RShkcoDOPnoCVhtpN1hDPQ* unused0);
N_NIMCALL(NIM_BOOL, atend_K8dPRCnFaz50Kq9buF2PeYA)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(NIM_BOOL, atend_zFgHDMODd9chv9aBdkHeghrg)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, Streamobj_RShkcoDOPnoCVhtpN1hDPQ* unused0);
N_NIMCALL(void, setposition_2EvT6qzO8p9cFGMlCGqs59cA)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI pos0);
N_NIMCALL(void, setposition_yNP1lEt8zcgEi6jUnxtwcg)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, Streamobj_RShkcoDOPnoCVhtpN1hDPQ* unused0, NI pos0);
N_NIMCALL(NI, getposition_DgMFF9a1vwKHsTun1epgBpg)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(NI, getposition_evk078wAXikyc9aVM6l3hQw)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, Streamobj_RShkcoDOPnoCVhtpN1hDPQ* unused0);
N_NIMCALL(NI, readdata_Gnwdizh7H5Q9cYivUoGHrVA)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, void* buffer0, NI buflen0);
N_NIMCALL(NimStringDesc*, readall_y6Jvjm2hmT9aQbvX9aMpHkOQ)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(NimStringDesc*, mnewString)(NI len0);
N_NIMCALL(NimStringDesc*, mnewString)(NI len0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s0, NI newlen0);
N_NIMCALL(NI, readdata_8bSHtQEFwp9b1L8oih3mScw)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, Streamobj_RShkcoDOPnoCVhtpN1hDPQ* unused0, void* buffer0, NI buflen0);
N_NIMCALL(NI, peekdata_Gnwdizh7H5Q9cYivUoGHrVA_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, void* buffer0, NI buflen0);
N_NIMCALL(void, writedata_lmaRetW0vPyY5hzlu3Ik7A)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, void* buffer0, NI buflen0);
N_NIMCALL(void, writedata_8AM5VKgHZXMc9a9czX8VHCrA)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, Streamobj_RShkcoDOPnoCVhtpN1hDPQ* unused0, void* buffer0, NI buflen0);
N_NIMCALL(void, write_J8LHFlpeBAP4mtGzmgjURA)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NimStringDesc* x0);
N_NIMCALL(void, writeln_G1TKFmud9akiH9bzSHWMshag)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NimStringDesc** args0, NI args0Len0);
N_NIMCALL(void, writeline_G1TKFmud9akiH9bzSHWMshag_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NimStringDesc** args0, NI args0Len0);
N_NIMCALL(NIM_CHAR, readchar_MXNOkfw9cIUOi4sewWv9cidw)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(NIM_CHAR, peekchar_MXNOkfw9cIUOi4sewWv9cidw_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(void, read_taTzRXMNQVFodmlvWMIBXw)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NIM_BOOL* result0);
N_NIMCALL(void, raiseException)(Exception* e0, NCSTRING ename0);
N_NIMCALL(NIM_BOOL, readbool_K8dPRCnFaz50Kq9buF2PeYA_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(void, peek_taTzRXMNQVFodmlvWMIBXw_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NIM_BOOL* result0);
N_NIMCALL(NIM_BOOL, peekbool_K8dPRCnFaz50Kq9buF2PeYA_3)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(void, read_fhkhQlFdT9a0lycu2tbq9aWw)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI8* result0);
N_NIMCALL(NI8, readint8_mrJsqYz1oHZ9bFjoyHQ9bxow)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(void, peek_fhkhQlFdT9a0lycu2tbq9aWw_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI8* result0);
N_NIMCALL(NI8, peekint8_mrJsqYz1oHZ9bFjoyHQ9bxow_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(void, read_DpDv9aEAJUCZRSLEvfUTMxA)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI16* result0);
N_NIMCALL(NI16, readint16_mQXcgU59cRwInEOpcmhS15A)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(void, peek_DpDv9aEAJUCZRSLEvfUTMxA_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI16* result0);
N_NIMCALL(NI16, peekint16_mQXcgU59cRwInEOpcmhS15A_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(void, read_urn9cp1KLYI56JAdcJy0aHQ)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI32* result0);
N_NIMCALL(NI32, readint32_Ef66ckXu6WtuDvil7Mgusw)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(void, peek_urn9cp1KLYI56JAdcJy0aHQ_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI32* result0);
N_NIMCALL(NI32, peekint32_Ef66ckXu6WtuDvil7Mgusw_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(void, read_zPfixAShsV7sXHsVdMHElw)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI64* result0);
N_NIMCALL(NI64, readint64_qjYTwVzSS2nwc0bZhztOyg)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(void, peek_zPfixAShsV7sXHsVdMHElw_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI64* result0);
N_NIMCALL(NI64, peekint64_qjYTwVzSS2nwc0bZhztOyg_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(void, read_SFi9b2sqpwoQ5JRuB1cGbcQ)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NF32* result0);
N_NIMCALL(NF32, readfloat32_SDR673qSwa2jl9bVOOVMFcQ)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(void, peek_SFi9b2sqpwoQ5JRuB1cGbcQ_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NF32* result0);
N_NIMCALL(NF32, peekfloat32_SDR673qSwa2jl9bVOOVMFcQ_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(void, read_UNLEjVG6ceZkMUzjUIWdWA)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NF* result0);
N_NIMCALL(NF, readfloat64_pBQtux5SAWSTJjoogt6lyA)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(void, peek_UNLEjVG6ceZkMUzjUIWdWA_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NF* result0);
N_NIMCALL(NF, peekfloat64_pBQtux5SAWSTJjoogt6lyA_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(NimStringDesc*, readstr_wgbx1EbYdFgqchF83HMWvQ)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI length0);
N_NIMCALL(NimStringDesc*, peekstr_wgbx1EbYdFgqchF83HMWvQ_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI length0);
N_NIMCALL(NIM_BOOL, readline_y89bfL07uXzOjT5XgI50WmQ)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NimStringDesc** line0);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s0, NIM_CHAR c0);
N_NIMCALL(NIM_BOOL, peekline_y89bfL07uXzOjT5XgI50WmQ_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NimStringDesc** line0);
static N_INLINE(void, pushSafePoint)(TSafePoint* s0);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s0);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(NimStringDesc*, readline_y6Jvjm2hmT9aQbvX9aMpHkOQ_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src0);
N_NIMCALL(NimStringDesc*, peekline_y6Jvjm2hmT9aQbvX9aMpHkOQ_3)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(NI, clamp_RrNgT2340KObgDMnZWSK5A)(NI x0, NI a0, NI b0);
N_NIMCALL(NIM_BOOL, ssatend_acl02gpfK9cCD8utiP6NxdA)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s_6rev1ZuxByWFQf6CowVxgw);
N_NIMCALL(void, chckObj)(TNimType* obj0, TNimType* subclass0);
N_NIMCALL(void, sssetposition_C0SEQJWfadg6oK29b8FuMZg)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s_8uJqD1Gkzs9bI9bzpslP39a6w, NI pos0);
N_NIMCALL(NI, ssgetposition_ht6Fg1Bmvqnb8CP4WayC2A)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s_ZozGEbyW3LBjyAXTtPgjEg);
N_NIMCALL(NI, ssreaddata_7P4Enb2Vt3iOCL5K9cnGqYw)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s_y2kqirqL6p0kJkuwFdE8DQ, void* buffer0, NI buflen0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
static N_INLINE(void, copymem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest0, void* source0, NI size0);
N_NIMCALL(NI, sspeekdata_7P4Enb2Vt3iOCL5K9cnGqYw_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s_QXLskfGc1Jev0gVF9a0jofg, void* buffer0, NI buflen0);
N_NIMCALL(void, sswritedata_mrtMhMXvYVpi5Svw9bWueBw)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s_TBWsPQ4EX2P6UUIoXpDeGQ, void* buffer0, NI buflen0);
N_NIMCALL(void, ssclose_qQbp4Nsuc4ou9bqUUbaqJ6A)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s_0oKy9bw20eQoZnoPxmQTRPQ);
N_NIMCALL(Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ*, newstringstream_0dQ0A0pna0dG9cMxo4TbLKQ)(NimStringDesc* s0);
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
static N_NIMCALL(void, Marker_TY_oa89b9cIODFBktXa1hHFh9c3Q)(void* p, NI op);
N_NIMCALL(void, fsclose_qQbp4Nsuc4ou9bqUUbaqJ6A_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(void, close_BWnr8V7RERYno9bIdPmw8Hw)(FILE* f0);
N_NIMCALL(void, fsflush_qQbp4Nsuc4ou9bqUUbaqJ6A_3)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(void, flushfile_BWnr8V7RERYno9bIdPmw8Hw_2)(FILE* f0);
N_NIMCALL(NIM_BOOL, fsatend_acl02gpfK9cCD8utiP6NxdA_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(NIM_BOOL, endoffile_OpxMRqWNQzmofyVQsNQqVA)(FILE* f0);
N_NIMCALL(void, fssetposition_C0SEQJWfadg6oK29b8FuMZg_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI pos0);
N_NIMCALL(void, setfilepos_YAngY19cHH2nZ9bqhMgAHz8Q)(FILE* f0, NI64 pos0, Fileseekpos_I9aQjuvWxs8BspGbxwsngWw relativeto0);
N_NIMCALL(NI, fsgetposition_ht6Fg1Bmvqnb8CP4WayC2A_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0);
N_NIMCALL(NI64, getfilepos_XePgC9ccBXCgb9bEHXZpnMqA_2)(FILE* f0);
N_NIMCALL(NI, fsreaddata_7P4Enb2Vt3iOCL5K9cnGqYw_3)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, void* buffer0, NI buflen0);
N_NIMCALL(NI, readbuffer_1qjbrvfnPD4PaIieHVDvhw)(FILE* f0, void* buffer0, NI len0);
N_NIMCALL(NI, fspeekdata_7P4Enb2Vt3iOCL5K9cnGqYw_4)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, void* buffer0, NI buflen0);
N_NIMCALL(void, fswritedata_mrtMhMXvYVpi5Svw9bWueBw_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, void* buffer0, NI buflen0);
N_NIMCALL(NI, writebuffer_1qjbrvfnPD4PaIieHVDvhw_2)(FILE* f0, void* buffer0, NI len0);
N_NIMCALL(Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*, newfilestream_j9aOzR9a9bXMSUnTXiGmXXGqQ)(FILE* f0);
static N_NIMCALL(void, Marker_TY_Z018yRjOOerOKfp9aM3JSOg)(void* p, NI op);
N_NIMCALL(Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*, newfilestream_EYjHaJgKBbBv69c9c5DDOTIg)(NimStringDesc* filename0, Filemode_fVUBHvW79bXUw1j55Oo9avSQ mode0);
N_NIMCALL(NIM_BOOL, open_sEp0GH2306oGo9bqBpj5oTQ)(FILE** f0, NimStringDesc* filename0, Filemode_fVUBHvW79bXUw1j55Oo9avSQ mode0, NI bufsize0);
static N_NIMCALL(void, Marker_TY_r3Wc5tOoxP8rz1DvGVTUvw)(void* p, NI op);
extern TNimType NTI_HX2M9cQhE3jaovp9aYJDdslA;
extern TNimType NTI_9czoZw3pzPyrBmb5zTHY1OQ;
extern NIM_THREADVAR TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR Gcheap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern NIM_THREADVAR TSafePoint* exchandler_rqLlY5bs9atDw2OXYqJEn5g;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA;
TNimType NTI_RShkcoDOPnoCVhtpN1hDPQ;
TNimType NTI_cnkJEp9bna8U6yi9aVW9cAJ0Q;
TNimType NTI_KjFcmLOhf4VQvVcyLJWXZw;
TNimType NTI_jlOYFw9cHausuCbPoWx2iiA;
TNimType NTI_Xzm85qBLb9cf9cu8VOfAr8PQ;
TNimType NTI_tjaJtoUzLe1BMUbItlcGhQ;
TNimType NTI_b9bsIuILxTLVZHPvJBW187A;
TNimType NTI_lGsM0FdhfyxyplfYoMsgFQ;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA;
TNimType NTI_oa89b9cIODFBktXa1hHFh9c3Q;
TNimType NTI_qoDM8xYRV40zbhS9acPNT9bw;
extern TNimType NTI_7BHnQsEj49a9c6QtudqWTo1w;
TNimType NTI_Z018yRjOOerOKfp9aM3JSOg;
TNimType NTI_r3Wc5tOoxP8rz1DvGVTUvw;
STRING_LITERAL(T_Ue7tnBcsL67VCiRfvt8q0A_6, "\012", 1);
STRING_LITERAL(T_Ue7tnBcsL67VCiRfvt8q0A_8, "cannot read from stream", 23);
STRING_LITERAL(T_Ue7tnBcsL67VCiRfvt8q0A_10, "", 0);
STRING_LITERAL(T_Ue7tnBcsL67VCiRfvt8q0A_21, "cannot write to stream", 22);

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln(134, "gc.nim");
	result0 = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(220, "gc.nim");
	addzct_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c0);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p0) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(262, "gc.nim");
	c0 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p0);
	nimln(264, "gc.nim");
	{
		(*c0).refcount -= ((NI) 8);
		if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(265, "gc.nim");
		rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system(c0);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*, neweio_lOrpXone7dPkEAOURnfgBw)(NimStringDesc* msg0) {
	Ioerror_9czoZw3pzPyrBmb5zTHY1OQ* result0;
	NimStringDesc* LOC1;
	nimfr("newEIO", "streams.nim")
	result0 = (Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*)0;
	nimln(38, "streams.nim");
	result0 = (Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*) newObj((&NTI_HX2M9cQhE3jaovp9aYJDdslA), sizeof(Ioerror_9czoZw3pzPyrBmb5zTHY1OQ));
	(*result0).Sup.Sup.Sup.m_type = (&NTI_9czoZw3pzPyrBmb5zTHY1OQ);
	nimln(39, "streams.nim");
	LOC1 = (NimStringDesc*)0;
	LOC1 = (*result0).Sup.Sup.message; (*result0).Sup.Sup.message = copyStringRC1(msg0);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	popFrame();
	return result0;
}

N_NIMCALL(void, flush_4ed7IXme7lqtClFI7s2sTQ)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	nimfr("flush", "streams.nim")
	nimln(64, "streams.nim");
	{
		if (!!(((*s0).flushimpl == 0))) goto LA3;
		(*s0).flushimpl(s0);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, close_4ed7IXme7lqtClFI7s2sTQ_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	nimfr("close", "streams.nim")
	nimln(68, "streams.nim");
	{
		if (!!(((*s0).closeimpl == 0))) goto LA3;
		(*s0).closeimpl(s0);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, close_dvxY0goRsVRNjhrDyOruTQ)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, Streamobj_RShkcoDOPnoCVhtpN1hDPQ* unused0) {
	nimfr("close", "streams.nim")
	nimln(72, "streams.nim");
	(*s0).closeimpl(s0);
	popFrame();
}

N_NIMCALL(NIM_BOOL, atend_K8dPRCnFaz50Kq9buF2PeYA)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NIM_BOOL result0;
	nimfr("atEnd", "streams.nim")
	result0 = (NIM_BOOL)0;
	nimln(77, "streams.nim");
	result0 = (*s0).atendimpl(s0);
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, atend_zFgHDMODd9chv9aBdkHeghrg)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, Streamobj_RShkcoDOPnoCVhtpN1hDPQ* unused0) {
	NIM_BOOL result0;
	nimfr("atEnd", "streams.nim")
	result0 = (NIM_BOOL)0;
	nimln(82, "streams.nim");
	result0 = (*s0).atendimpl(s0);
	popFrame();
	return result0;
}

N_NIMCALL(void, setposition_2EvT6qzO8p9cFGMlCGqs59cA)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI pos0) {
	nimfr("setPosition", "streams.nim")
	nimln(86, "streams.nim");
	(*s0).setpositionimpl(s0, pos0);
	popFrame();
}

N_NIMCALL(void, setposition_yNP1lEt8zcgEi6jUnxtwcg)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, Streamobj_RShkcoDOPnoCVhtpN1hDPQ* unused0, NI pos0) {
	nimfr("setPosition", "streams.nim")
	nimln(90, "streams.nim");
	(*s0).setpositionimpl(s0, pos0);
	popFrame();
}

N_NIMCALL(NI, getposition_DgMFF9a1vwKHsTun1epgBpg)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NI result0;
	nimfr("getPosition", "streams.nim")
	result0 = (NI)0;
	nimln(94, "streams.nim");
	result0 = (*s0).getpositionimpl(s0);
	popFrame();
	return result0;
}

N_NIMCALL(NI, getposition_evk078wAXikyc9aVM6l3hQw)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, Streamobj_RShkcoDOPnoCVhtpN1hDPQ* unused0) {
	NI result0;
	nimfr("getPosition", "streams.nim")
	result0 = (NI)0;
	nimln(98, "streams.nim");
	result0 = (*s0).getpositionimpl(s0);
	popFrame();
	return result0;
}

N_NIMCALL(NI, readdata_Gnwdizh7H5Q9cYivUoGHrVA)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, void* buffer0, NI buflen0) {
	NI result0;
	nimfr("readData", "streams.nim")
	result0 = (NI)0;
	nimln(102, "streams.nim");
	result0 = (*s0).readdataimpl(s0, buffer0, buflen0);
	popFrame();
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NimStringDesc*, readall_y6Jvjm2hmT9aQbvX9aMpHkOQ)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NimStringDesc* result0;
	NI r0;
	nimfr("readAll", "streams.nim")
	result0 = (NimStringDesc*)0;
	nimln(107, "streams.nim");
	result0 = mnewString(((NI) 1000));
	nimln(108, "streams.nim");
	r0 = ((NI) 0);
	{
		nimln(109, "streams.nim");
		while (1) {
			NI readbytes0;
			NI T_Ue7tnBcsL67VCiRfvt8q0A_3;
			NI T_Ue7tnBcsL67VCiRfvt8q0A_4;
			nimln(110, "streams.nim");
			if ((NU)(r0) > (NU)(result0->Sup.len)) raiseIndexError();
			readbytes0 = readdata_Gnwdizh7H5Q9cYivUoGHrVA(s0, ((void*) ((&result0->data[r0]))), ((NI) 1000));
			nimln(111, "streams.nim");
			{
				NI T_Ue7tnBcsL67VCiRfvt8q0A_2;
				if (!(readbytes0 < ((NI) 1000))) goto LA5;
				nimln(112, "streams.nim");
				T_Ue7tnBcsL67VCiRfvt8q0A_2 = addInt(r0, readbytes0);
				result0 = setLengthStr(result0, ((NI)chckRange((NI)(T_Ue7tnBcsL67VCiRfvt8q0A_2), ((NI) 0), ((NI) IL64(9223372036854775807)))));
				nimln(113, "streams.nim");
				goto LA1;
			}
			LA5: ;
			nimln(114, "streams.nim");
			T_Ue7tnBcsL67VCiRfvt8q0A_3 = addInt(r0, ((NI) 1000));
			r0 = (NI)(T_Ue7tnBcsL67VCiRfvt8q0A_3);
			nimln(115, "streams.nim");
			T_Ue7tnBcsL67VCiRfvt8q0A_4 = addInt(r0, ((NI) 1000));
			result0 = setLengthStr(result0, ((NI)chckRange((NI)(T_Ue7tnBcsL67VCiRfvt8q0A_4), ((NI) 0), ((NI) IL64(9223372036854775807)))));
		}
	} LA1: ;
	popFrame();
	return result0;
}

N_NIMCALL(NI, readdata_8bSHtQEFwp9b1L8oih3mScw)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, Streamobj_RShkcoDOPnoCVhtpN1hDPQ* unused0, void* buffer0, NI buflen0) {
	NI result0;
	nimfr("readData", "streams.nim")
	result0 = (NI)0;
	nimln(120, "streams.nim");
	result0 = (*s0).readdataimpl(s0, buffer0, buflen0);
	popFrame();
	return result0;
}

N_NIMCALL(NI, peekdata_Gnwdizh7H5Q9cYivUoGHrVA_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, void* buffer0, NI buflen0) {
	NI result0;
	nimfr("peekData", "streams.nim")
	result0 = (NI)0;
	nimln(125, "streams.nim");
	result0 = (*s0).peekdataimpl(s0, buffer0, buflen0);
	popFrame();
	return result0;
}

N_NIMCALL(void, writedata_lmaRetW0vPyY5hzlu3Ik7A)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, void* buffer0, NI buflen0) {
	nimfr("writeData", "streams.nim")
	nimln(130, "streams.nim");
	(*s0).writedataimpl(s0, buffer0, buflen0);
	popFrame();
}

N_NIMCALL(void, writedata_8AM5VKgHZXMc9a9czX8VHCrA)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, Streamobj_RShkcoDOPnoCVhtpN1hDPQ* unused0, void* buffer0, NI buflen0) {
	nimfr("writeData", "streams.nim")
	nimln(136, "streams.nim");
	(*s0).writedataimpl(s0, buffer0, buflen0);
	popFrame();
}

N_NIMCALL(void, write_J8LHFlpeBAP4mtGzmgjURA)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NimStringDesc* x0) {
	nimfr("write", "streams.nim")
	nimln(154, "streams.nim");
	{
		if (!(((NI) 0) < (x0 ? x0->Sup.len : 0))) goto LA3;
		if ((NU)(((NI) 0)) > (NU)(x0->Sup.len)) raiseIndexError();
		writedata_lmaRetW0vPyY5hzlu3Ik7A(s0, ((void*) ((&x0->data[((NI) 0)]))), (x0 ? x0->Sup.len : 0));
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, writeln_G1TKFmud9akiH9bzSHWMshag)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NimStringDesc** args0, NI args0Len0) {
	nimfr("writeLn", "streams.nim")
	{
		NimStringDesc* str_7g3dvWGOTzRDR5AtAbt9big;
		NI i_KYI0ozJJqQf5uNJX7Q8j7g;
		str_7g3dvWGOTzRDR5AtAbt9big = (NimStringDesc*)0;
		nimln(1999, "system.nim");
		i_KYI0ozJJqQf5uNJX7Q8j7g = ((NI) 0);
		{
			nimln(2000, "system.nim");
			while (1) {
				NI T_Ue7tnBcsL67VCiRfvt8q0A_5;
				nimln(1999, "system.nim");
				nimln(158, "streams.nim");
				if (!(i_KYI0ozJJqQf5uNJX7Q8j7g < args0Len0)) goto LA3;
				nimln(2001, "system.nim");
				if ((NU)(i_KYI0ozJJqQf5uNJX7Q8j7g) >= (NU)(args0Len0)) raiseIndexError();
				str_7g3dvWGOTzRDR5AtAbt9big = args0[i_KYI0ozJJqQf5uNJX7Q8j7g];
				nimln(158, "streams.nim");
				write_J8LHFlpeBAP4mtGzmgjURA(s0, str_7g3dvWGOTzRDR5AtAbt9big);
				nimln(1999, "system.nim");
				T_Ue7tnBcsL67VCiRfvt8q0A_5 = addInt(i_KYI0ozJJqQf5uNJX7Q8j7g, ((NI) 1));
				i_KYI0ozJJqQf5uNJX7Q8j7g = (NI)(T_Ue7tnBcsL67VCiRfvt8q0A_5);
			} LA3: ;
		}
	}
	nimln(159, "streams.nim");
	write_J8LHFlpeBAP4mtGzmgjURA(s0, ((NimStringDesc*) &T_Ue7tnBcsL67VCiRfvt8q0A_6));
	popFrame();
}

N_NIMCALL(void, writeline_G1TKFmud9akiH9bzSHWMshag_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NimStringDesc** args0, NI args0Len0) {
	nimfr("writeLine", "streams.nim")
	{
		NimStringDesc* str_jq09bFXSYgJ9brSdx8eDtxig;
		NI i_wkgsem9cDSz9aQXry0v1emzg;
		str_jq09bFXSYgJ9brSdx8eDtxig = (NimStringDesc*)0;
		nimln(1999, "system.nim");
		i_wkgsem9cDSz9aQXry0v1emzg = ((NI) 0);
		{
			nimln(2000, "system.nim");
			while (1) {
				NI T_Ue7tnBcsL67VCiRfvt8q0A_7;
				nimln(1999, "system.nim");
				nimln(164, "streams.nim");
				if (!(i_wkgsem9cDSz9aQXry0v1emzg < args0Len0)) goto LA3;
				nimln(2001, "system.nim");
				if ((NU)(i_wkgsem9cDSz9aQXry0v1emzg) >= (NU)(args0Len0)) raiseIndexError();
				str_jq09bFXSYgJ9brSdx8eDtxig = args0[i_wkgsem9cDSz9aQXry0v1emzg];
				nimln(164, "streams.nim");
				write_J8LHFlpeBAP4mtGzmgjURA(s0, str_jq09bFXSYgJ9brSdx8eDtxig);
				nimln(1999, "system.nim");
				T_Ue7tnBcsL67VCiRfvt8q0A_7 = addInt(i_wkgsem9cDSz9aQXry0v1emzg, ((NI) 1));
				i_wkgsem9cDSz9aQXry0v1emzg = (NI)(T_Ue7tnBcsL67VCiRfvt8q0A_7);
			} LA3: ;
		}
	}
	nimln(165, "streams.nim");
	write_J8LHFlpeBAP4mtGzmgjURA(s0, ((NimStringDesc*) &T_Ue7tnBcsL67VCiRfvt8q0A_6));
	popFrame();
}

N_NIMCALL(NIM_CHAR, readchar_MXNOkfw9cIUOi4sewWv9cidw)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NIM_CHAR result0;
	nimfr("readChar", "streams.nim")
	result0 = (NIM_CHAR)0;
	nimln(180, "streams.nim");
	{
		NI LOC3;
		nimln(347, "system.nim");
		nimln(180, "streams.nim");
		LOC3 = (NI)0;
		LOC3 = readdata_Gnwdizh7H5Q9cYivUoGHrVA(s0, ((void*) ((&result0))), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		result0 = 0;
	}
	LA4: ;
	popFrame();
	return result0;
}

N_NIMCALL(NIM_CHAR, peekchar_MXNOkfw9cIUOi4sewWv9cidw_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NIM_CHAR result0;
	nimfr("peekChar", "streams.nim")
	result0 = (NIM_CHAR)0;
	nimln(185, "streams.nim");
	{
		NI LOC3;
		nimln(347, "system.nim");
		nimln(185, "streams.nim");
		LOC3 = (NI)0;
		LOC3 = peekdata_Gnwdizh7H5Q9cYivUoGHrVA_2(s0, ((void*) ((&result0))), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		result0 = 0;
	}
	LA4: ;
	popFrame();
	return result0;
}

N_NIMCALL(void, read_taTzRXMNQVFodmlvWMIBXw)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NIM_BOOL* result0) {
	nimfr("read", "streams.nim")
	nimln(169, "streams.nim");
	{
		NI LOC3;
		Ioerror_9czoZw3pzPyrBmb5zTHY1OQ* LOC6;
		nimln(347, "system.nim");
		nimln(169, "streams.nim");
		LOC3 = (NI)0;
		LOC3 = readdata_Gnwdizh7H5Q9cYivUoGHrVA(s0, ((void*) (result0)), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		nimln(170, "streams.nim");
		LOC6 = (Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		LOC6 = neweio_lOrpXone7dPkEAOURnfgBw(((NimStringDesc*) &T_Ue7tnBcsL67VCiRfvt8q0A_8));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, readbool_K8dPRCnFaz50Kq9buF2PeYA_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NIM_BOOL result0;
	nimfr("readBool", "streams.nim")
	result0 = (NIM_BOOL)0;
	nimln(189, "streams.nim");
	read_taTzRXMNQVFodmlvWMIBXw(s0, (&result0));
	popFrame();
	return result0;
}

N_NIMCALL(void, peek_taTzRXMNQVFodmlvWMIBXw_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NIM_BOOL* result0) {
	nimfr("peek", "streams.nim")
	nimln(174, "streams.nim");
	{
		NI LOC3;
		Ioerror_9czoZw3pzPyrBmb5zTHY1OQ* LOC6;
		nimln(347, "system.nim");
		nimln(174, "streams.nim");
		LOC3 = (NI)0;
		LOC3 = peekdata_Gnwdizh7H5Q9cYivUoGHrVA_2(s0, ((void*) (result0)), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		nimln(175, "streams.nim");
		LOC6 = (Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		LOC6 = neweio_lOrpXone7dPkEAOURnfgBw(((NimStringDesc*) &T_Ue7tnBcsL67VCiRfvt8q0A_8));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, peekbool_K8dPRCnFaz50Kq9buF2PeYA_3)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NIM_BOOL result0;
	nimfr("peekBool", "streams.nim")
	result0 = (NIM_BOOL)0;
	nimln(193, "streams.nim");
	peek_taTzRXMNQVFodmlvWMIBXw_2(s0, (&result0));
	popFrame();
	return result0;
}

N_NIMCALL(void, read_fhkhQlFdT9a0lycu2tbq9aWw)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI8* result0) {
	nimfr("read", "streams.nim")
	nimln(169, "streams.nim");
	{
		NI LOC3;
		Ioerror_9czoZw3pzPyrBmb5zTHY1OQ* LOC6;
		nimln(347, "system.nim");
		nimln(169, "streams.nim");
		LOC3 = (NI)0;
		LOC3 = readdata_Gnwdizh7H5Q9cYivUoGHrVA(s0, ((void*) (result0)), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		nimln(170, "streams.nim");
		LOC6 = (Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		LOC6 = neweio_lOrpXone7dPkEAOURnfgBw(((NimStringDesc*) &T_Ue7tnBcsL67VCiRfvt8q0A_8));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI8, readint8_mrJsqYz1oHZ9bFjoyHQ9bxow)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NI8 result0;
	nimfr("readInt8", "streams.nim")
	result0 = (NI8)0;
	nimln(197, "streams.nim");
	read_fhkhQlFdT9a0lycu2tbq9aWw(s0, (&result0));
	popFrame();
	return result0;
}

N_NIMCALL(void, peek_fhkhQlFdT9a0lycu2tbq9aWw_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI8* result0) {
	nimfr("peek", "streams.nim")
	nimln(174, "streams.nim");
	{
		NI LOC3;
		Ioerror_9czoZw3pzPyrBmb5zTHY1OQ* LOC6;
		nimln(347, "system.nim");
		nimln(174, "streams.nim");
		LOC3 = (NI)0;
		LOC3 = peekdata_Gnwdizh7H5Q9cYivUoGHrVA_2(s0, ((void*) (result0)), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		nimln(175, "streams.nim");
		LOC6 = (Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		LOC6 = neweio_lOrpXone7dPkEAOURnfgBw(((NimStringDesc*) &T_Ue7tnBcsL67VCiRfvt8q0A_8));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI8, peekint8_mrJsqYz1oHZ9bFjoyHQ9bxow_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NI8 result0;
	nimfr("peekInt8", "streams.nim")
	result0 = (NI8)0;
	nimln(201, "streams.nim");
	peek_fhkhQlFdT9a0lycu2tbq9aWw_2(s0, (&result0));
	popFrame();
	return result0;
}

N_NIMCALL(void, read_DpDv9aEAJUCZRSLEvfUTMxA)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI16* result0) {
	nimfr("read", "streams.nim")
	nimln(169, "streams.nim");
	{
		NI LOC3;
		Ioerror_9czoZw3pzPyrBmb5zTHY1OQ* LOC6;
		nimln(347, "system.nim");
		nimln(169, "streams.nim");
		LOC3 = (NI)0;
		LOC3 = readdata_Gnwdizh7H5Q9cYivUoGHrVA(s0, ((void*) (result0)), ((NI) 2));
		if (!!((LOC3 == ((NI) 2)))) goto LA4;
		nimln(170, "streams.nim");
		LOC6 = (Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		LOC6 = neweio_lOrpXone7dPkEAOURnfgBw(((NimStringDesc*) &T_Ue7tnBcsL67VCiRfvt8q0A_8));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI16, readint16_mQXcgU59cRwInEOpcmhS15A)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NI16 result0;
	nimfr("readInt16", "streams.nim")
	result0 = (NI16)0;
	nimln(205, "streams.nim");
	read_DpDv9aEAJUCZRSLEvfUTMxA(s0, (&result0));
	popFrame();
	return result0;
}

N_NIMCALL(void, peek_DpDv9aEAJUCZRSLEvfUTMxA_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI16* result0) {
	nimfr("peek", "streams.nim")
	nimln(174, "streams.nim");
	{
		NI LOC3;
		Ioerror_9czoZw3pzPyrBmb5zTHY1OQ* LOC6;
		nimln(347, "system.nim");
		nimln(174, "streams.nim");
		LOC3 = (NI)0;
		LOC3 = peekdata_Gnwdizh7H5Q9cYivUoGHrVA_2(s0, ((void*) (result0)), ((NI) 2));
		if (!!((LOC3 == ((NI) 2)))) goto LA4;
		nimln(175, "streams.nim");
		LOC6 = (Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		LOC6 = neweio_lOrpXone7dPkEAOURnfgBw(((NimStringDesc*) &T_Ue7tnBcsL67VCiRfvt8q0A_8));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI16, peekint16_mQXcgU59cRwInEOpcmhS15A_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NI16 result0;
	nimfr("peekInt16", "streams.nim")
	result0 = (NI16)0;
	nimln(209, "streams.nim");
	peek_DpDv9aEAJUCZRSLEvfUTMxA_2(s0, (&result0));
	popFrame();
	return result0;
}

N_NIMCALL(void, read_urn9cp1KLYI56JAdcJy0aHQ)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI32* result0) {
	nimfr("read", "streams.nim")
	nimln(169, "streams.nim");
	{
		NI LOC3;
		Ioerror_9czoZw3pzPyrBmb5zTHY1OQ* LOC6;
		nimln(347, "system.nim");
		nimln(169, "streams.nim");
		LOC3 = (NI)0;
		LOC3 = readdata_Gnwdizh7H5Q9cYivUoGHrVA(s0, ((void*) (result0)), ((NI) 4));
		if (!!((LOC3 == ((NI) 4)))) goto LA4;
		nimln(170, "streams.nim");
		LOC6 = (Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		LOC6 = neweio_lOrpXone7dPkEAOURnfgBw(((NimStringDesc*) &T_Ue7tnBcsL67VCiRfvt8q0A_8));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI32, readint32_Ef66ckXu6WtuDvil7Mgusw)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NI32 result0;
	nimfr("readInt32", "streams.nim")
	result0 = (NI32)0;
	nimln(213, "streams.nim");
	read_urn9cp1KLYI56JAdcJy0aHQ(s0, (&result0));
	popFrame();
	return result0;
}

N_NIMCALL(void, peek_urn9cp1KLYI56JAdcJy0aHQ_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI32* result0) {
	nimfr("peek", "streams.nim")
	nimln(174, "streams.nim");
	{
		NI LOC3;
		Ioerror_9czoZw3pzPyrBmb5zTHY1OQ* LOC6;
		nimln(347, "system.nim");
		nimln(174, "streams.nim");
		LOC3 = (NI)0;
		LOC3 = peekdata_Gnwdizh7H5Q9cYivUoGHrVA_2(s0, ((void*) (result0)), ((NI) 4));
		if (!!((LOC3 == ((NI) 4)))) goto LA4;
		nimln(175, "streams.nim");
		LOC6 = (Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		LOC6 = neweio_lOrpXone7dPkEAOURnfgBw(((NimStringDesc*) &T_Ue7tnBcsL67VCiRfvt8q0A_8));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI32, peekint32_Ef66ckXu6WtuDvil7Mgusw_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NI32 result0;
	nimfr("peekInt32", "streams.nim")
	result0 = (NI32)0;
	nimln(217, "streams.nim");
	peek_urn9cp1KLYI56JAdcJy0aHQ_2(s0, (&result0));
	popFrame();
	return result0;
}

N_NIMCALL(void, read_zPfixAShsV7sXHsVdMHElw)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI64* result0) {
	nimfr("read", "streams.nim")
	nimln(169, "streams.nim");
	{
		NI LOC3;
		Ioerror_9czoZw3pzPyrBmb5zTHY1OQ* LOC6;
		nimln(347, "system.nim");
		nimln(169, "streams.nim");
		LOC3 = (NI)0;
		LOC3 = readdata_Gnwdizh7H5Q9cYivUoGHrVA(s0, ((void*) (result0)), ((NI) 8));
		if (!!((LOC3 == ((NI) 8)))) goto LA4;
		nimln(170, "streams.nim");
		LOC6 = (Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		LOC6 = neweio_lOrpXone7dPkEAOURnfgBw(((NimStringDesc*) &T_Ue7tnBcsL67VCiRfvt8q0A_8));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI64, readint64_qjYTwVzSS2nwc0bZhztOyg)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NI64 result0;
	nimfr("readInt64", "streams.nim")
	result0 = (NI64)0;
	nimln(221, "streams.nim");
	read_zPfixAShsV7sXHsVdMHElw(s0, (&result0));
	popFrame();
	return result0;
}

N_NIMCALL(void, peek_zPfixAShsV7sXHsVdMHElw_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI64* result0) {
	nimfr("peek", "streams.nim")
	nimln(174, "streams.nim");
	{
		NI LOC3;
		Ioerror_9czoZw3pzPyrBmb5zTHY1OQ* LOC6;
		nimln(347, "system.nim");
		nimln(174, "streams.nim");
		LOC3 = (NI)0;
		LOC3 = peekdata_Gnwdizh7H5Q9cYivUoGHrVA_2(s0, ((void*) (result0)), ((NI) 8));
		if (!!((LOC3 == ((NI) 8)))) goto LA4;
		nimln(175, "streams.nim");
		LOC6 = (Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		LOC6 = neweio_lOrpXone7dPkEAOURnfgBw(((NimStringDesc*) &T_Ue7tnBcsL67VCiRfvt8q0A_8));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI64, peekint64_qjYTwVzSS2nwc0bZhztOyg_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NI64 result0;
	nimfr("peekInt64", "streams.nim")
	result0 = (NI64)0;
	nimln(225, "streams.nim");
	peek_zPfixAShsV7sXHsVdMHElw_2(s0, (&result0));
	popFrame();
	return result0;
}

N_NIMCALL(void, read_SFi9b2sqpwoQ5JRuB1cGbcQ)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NF32* result0) {
	nimfr("read", "streams.nim")
	nimln(169, "streams.nim");
	{
		NI LOC3;
		Ioerror_9czoZw3pzPyrBmb5zTHY1OQ* LOC6;
		nimln(347, "system.nim");
		nimln(169, "streams.nim");
		LOC3 = (NI)0;
		LOC3 = readdata_Gnwdizh7H5Q9cYivUoGHrVA(s0, ((void*) (result0)), ((NI) 4));
		if (!!((LOC3 == ((NI) 4)))) goto LA4;
		nimln(170, "streams.nim");
		LOC6 = (Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		LOC6 = neweio_lOrpXone7dPkEAOURnfgBw(((NimStringDesc*) &T_Ue7tnBcsL67VCiRfvt8q0A_8));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF32, readfloat32_SDR673qSwa2jl9bVOOVMFcQ)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NF32 result0;
	nimfr("readFloat32", "streams.nim")
	result0 = (NF32)0;
	nimln(229, "streams.nim");
	read_SFi9b2sqpwoQ5JRuB1cGbcQ(s0, (&result0));
	popFrame();
	return result0;
}

N_NIMCALL(void, peek_SFi9b2sqpwoQ5JRuB1cGbcQ_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NF32* result0) {
	nimfr("peek", "streams.nim")
	nimln(174, "streams.nim");
	{
		NI LOC3;
		Ioerror_9czoZw3pzPyrBmb5zTHY1OQ* LOC6;
		nimln(347, "system.nim");
		nimln(174, "streams.nim");
		LOC3 = (NI)0;
		LOC3 = peekdata_Gnwdizh7H5Q9cYivUoGHrVA_2(s0, ((void*) (result0)), ((NI) 4));
		if (!!((LOC3 == ((NI) 4)))) goto LA4;
		nimln(175, "streams.nim");
		LOC6 = (Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		LOC6 = neweio_lOrpXone7dPkEAOURnfgBw(((NimStringDesc*) &T_Ue7tnBcsL67VCiRfvt8q0A_8));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF32, peekfloat32_SDR673qSwa2jl9bVOOVMFcQ_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NF32 result0;
	nimfr("peekFloat32", "streams.nim")
	result0 = (NF32)0;
	nimln(233, "streams.nim");
	peek_SFi9b2sqpwoQ5JRuB1cGbcQ_2(s0, (&result0));
	popFrame();
	return result0;
}

N_NIMCALL(void, read_UNLEjVG6ceZkMUzjUIWdWA)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NF* result0) {
	nimfr("read", "streams.nim")
	nimln(169, "streams.nim");
	{
		NI LOC3;
		Ioerror_9czoZw3pzPyrBmb5zTHY1OQ* LOC6;
		nimln(347, "system.nim");
		nimln(169, "streams.nim");
		LOC3 = (NI)0;
		LOC3 = readdata_Gnwdizh7H5Q9cYivUoGHrVA(s0, ((void*) (result0)), ((NI) 8));
		if (!!((LOC3 == ((NI) 8)))) goto LA4;
		nimln(170, "streams.nim");
		LOC6 = (Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		LOC6 = neweio_lOrpXone7dPkEAOURnfgBw(((NimStringDesc*) &T_Ue7tnBcsL67VCiRfvt8q0A_8));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF, readfloat64_pBQtux5SAWSTJjoogt6lyA)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NF result0;
	nimfr("readFloat64", "streams.nim")
	result0 = (NF)0;
	nimln(237, "streams.nim");
	read_UNLEjVG6ceZkMUzjUIWdWA(s0, (&result0));
	popFrame();
	return result0;
}

N_NIMCALL(void, peek_UNLEjVG6ceZkMUzjUIWdWA_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NF* result0) {
	nimfr("peek", "streams.nim")
	nimln(174, "streams.nim");
	{
		NI LOC3;
		Ioerror_9czoZw3pzPyrBmb5zTHY1OQ* LOC6;
		nimln(347, "system.nim");
		nimln(174, "streams.nim");
		LOC3 = (NI)0;
		LOC3 = peekdata_Gnwdizh7H5Q9cYivUoGHrVA_2(s0, ((void*) (result0)), ((NI) 8));
		if (!!((LOC3 == ((NI) 8)))) goto LA4;
		nimln(175, "streams.nim");
		LOC6 = (Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		LOC6 = neweio_lOrpXone7dPkEAOURnfgBw(((NimStringDesc*) &T_Ue7tnBcsL67VCiRfvt8q0A_8));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF, peekfloat64_pBQtux5SAWSTJjoogt6lyA_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NF result0;
	nimfr("peekFloat64", "streams.nim")
	result0 = (NF)0;
	nimln(241, "streams.nim");
	peek_UNLEjVG6ceZkMUzjUIWdWA_2(s0, (&result0));
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, readstr_wgbx1EbYdFgqchF83HMWvQ)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI length0) {
	NimStringDesc* result0;
	NI L0;
	nimfr("readStr", "streams.nim")
	result0 = (NimStringDesc*)0;
	nimln(246, "streams.nim");
	result0 = mnewString(((NI)chckRange(length0, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(247, "streams.nim");
	if ((NU)(((NI) 0)) > (NU)(result0->Sup.len)) raiseIndexError();
	L0 = readdata_Gnwdizh7H5Q9cYivUoGHrVA(s0, ((void*) ((&result0->data[((NI) 0)]))), length0);
	nimln(248, "streams.nim");
	{
		nimln(347, "system.nim");
		nimln(248, "streams.nim");
		if (!!((L0 == length0))) goto LA3;
		result0 = setLengthStr(result0, ((NI)chckRange(L0, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA3: ;
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, peekstr_wgbx1EbYdFgqchF83HMWvQ_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI length0) {
	NimStringDesc* result0;
	NI L0;
	nimfr("peekStr", "streams.nim")
	result0 = (NimStringDesc*)0;
	nimln(253, "streams.nim");
	result0 = mnewString(((NI)chckRange(length0, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(254, "streams.nim");
	if ((NU)(((NI) 0)) > (NU)(result0->Sup.len)) raiseIndexError();
	L0 = peekdata_Gnwdizh7H5Q9cYivUoGHrVA_2(s0, ((void*) ((&result0->data[((NI) 0)]))), length0);
	nimln(255, "streams.nim");
	{
		nimln(347, "system.nim");
		nimln(255, "streams.nim");
		if (!!((L0 == length0))) goto LA3;
		result0 = setLengthStr(result0, ((NI)chckRange(L0, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA3: ;
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, readline_y89bfL07uXzOjT5XgI50WmQ)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NimStringDesc** line0) {
	NIM_BOOL result0;
	nimfr("readLine", "streams.nim")
{	result0 = (NIM_BOOL)0;
	nimln(264, "streams.nim");
	(*line0) = setLengthStr((*line0), ((NI) 0));
	{
		nimln(265, "streams.nim");
		while (1) {
			NIM_CHAR c0;
			nimln(266, "streams.nim");
			c0 = readchar_MXNOkfw9cIUOi4sewWv9cidw(s0);
			nimln(267, "streams.nim");
			{
				if (!((NU8)(c0) == (NU8)(13))) goto LA5;
				nimln(268, "streams.nim");
				c0 = readchar_MXNOkfw9cIUOi4sewWv9cidw(s0);
				nimln(269, "streams.nim");
				goto LA1;
			}
			goto LA3;
			LA5: ;
			{
				nimln(270, "streams.nim");
				if (!((NU8)(c0) == (NU8)(10))) goto LA8;
				goto LA1;
			}
			goto LA3;
			LA8: ;
			{
				nimln(271, "streams.nim");
				if (!((NU8)(c0) == (NU8)(0))) goto LA11;
				nimln(272, "streams.nim");
				{
					if (!(((NI) 0) < ((*line0) ? (*line0)->Sup.len : 0))) goto LA15;
					goto LA1;
				}
				goto LA13;
				LA15: ;
				{
					nimln(273, "streams.nim");
					result0 = NIM_FALSE;
					goto BeforeRet;
				}
				LA13: ;
			}
			goto LA3;
			LA11: ;
			LA3: ;
			nimln(274, "streams.nim");
			(*line0) = addChar((*line0), c0);
		}
	} LA1: ;
	nimln(275, "streams.nim");
	result0 = NIM_TRUE;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s0) {
	(*s0).hasRaiseAction = NIM_FALSE;
	(*s0).prev = exchandler_rqLlY5bs9atDw2OXYqJEn5g;
	exchandler_rqLlY5bs9atDw2OXYqJEn5g = s0;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_rqLlY5bs9atDw2OXYqJEn5g = (*exchandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s0) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
}

N_NIMCALL(NIM_BOOL, peekline_y89bfL07uXzOjT5XgI50WmQ_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NimStringDesc** line0) {
	NIM_BOOL volatile result0;
	NI pos0;
	TSafePoint T_Ue7tnBcsL67VCiRfvt8q0A_9;
	nimfr("peekLine", "streams.nim")
	result0 = (NIM_BOOL)0;
	nimln(284, "streams.nim");
	pos0 = getposition_DgMFF9a1vwKHsTun1epgBpg(s0);
	nimln(285, "streams.nim");
	pushSafePoint(&T_Ue7tnBcsL67VCiRfvt8q0A_9);
	T_Ue7tnBcsL67VCiRfvt8q0A_9.status = setjmp(T_Ue7tnBcsL67VCiRfvt8q0A_9.context);
	if (T_Ue7tnBcsL67VCiRfvt8q0A_9.status == 0) {
		nimln(286, "streams.nim");
		result0 = readline_y89bfL07uXzOjT5XgI50WmQ(s0, line0);
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
	}
	{
		nimln(285, "streams.nim");
		setposition_2EvT6qzO8p9cFGMlCGqs59cA(s0, pos0);
	}
	if (T_Ue7tnBcsL67VCiRfvt8q0A_9.status != 0) reraiseException();
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, readline_y6Jvjm2hmT9aQbvX9aMpHkOQ_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NimStringDesc* result0;
	nimfr("readLine", "streams.nim")
	result0 = (NimStringDesc*)0;
	nimln(291, "streams.nim");
	result0 = copyString(((NimStringDesc*) &T_Ue7tnBcsL67VCiRfvt8q0A_10));
	{
		nimln(292, "streams.nim");
		while (1) {
			NIM_CHAR c0;
			nimln(293, "streams.nim");
			c0 = readchar_MXNOkfw9cIUOi4sewWv9cidw(s0);
			nimln(294, "streams.nim");
			{
				if (!((NU8)(c0) == (NU8)(13))) goto LA5;
				nimln(295, "streams.nim");
				c0 = readchar_MXNOkfw9cIUOi4sewWv9cidw(s0);
				nimln(296, "streams.nim");
				goto LA1;
			}
			LA5: ;
			nimln(297, "streams.nim");
			{
				NIM_BOOL LOC9;
				LOC9 = (NIM_BOOL)0;
				LOC9 = ((NU8)(c0) == (NU8)(10));
				if (LOC9) goto LA10;
				LOC9 = ((NU8)(c0) == (NU8)(0));
				LA10: ;
				if (!LOC9) goto LA11;
				nimln(298, "streams.nim");
				goto LA1;
			}
			goto LA7;
			LA11: ;
			{
				nimln(300, "streams.nim");
				result0 = addChar(result0, c0);
			}
			LA7: ;
		}
	} LA1: ;
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, peekline_y6Jvjm2hmT9aQbvX9aMpHkOQ_3)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NimStringDesc* volatile result0;
	NI pos0;
	TSafePoint T_Ue7tnBcsL67VCiRfvt8q0A_11;
	nimfr("peekLine", "streams.nim")
	result0 = (NimStringDesc*)0;
	nimln(305, "streams.nim");
	pos0 = getposition_DgMFF9a1vwKHsTun1epgBpg(s0);
	nimln(306, "streams.nim");
	pushSafePoint(&T_Ue7tnBcsL67VCiRfvt8q0A_11);
	T_Ue7tnBcsL67VCiRfvt8q0A_11.status = setjmp(T_Ue7tnBcsL67VCiRfvt8q0A_11.context);
	if (T_Ue7tnBcsL67VCiRfvt8q0A_11.status == 0) {
		nimln(307, "streams.nim");
		result0 = readline_y6Jvjm2hmT9aQbvX9aMpHkOQ_2(s0);
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
	}
	{
		nimln(306, "streams.nim");
		setposition_2EvT6qzO8p9cFGMlCGqs59cA(s0, pos0);
	}
	if (T_Ue7tnBcsL67VCiRfvt8q0A_11.status != 0) reraiseException();
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, ssatend_acl02gpfK9cCD8utiP6NxdA)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s_6rev1ZuxByWFQf6CowVxgw) {
	NIM_BOOL result0;
	Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ* s0;
	nimfr("ssAtEnd", "streams.nim")
{	result0 = (NIM_BOOL)0;
	nimln(320, "streams.nim");
	if (s_6rev1ZuxByWFQf6CowVxgw) chckObj((*s_6rev1ZuxByWFQf6CowVxgw).Sup.m_type, (&NTI_lGsM0FdhfyxyplfYoMsgFQ));
	s0 = ((Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ*) (s_6rev1ZuxByWFQf6CowVxgw));
	nimln(321, "streams.nim");
	result0 = (((*s0).data ? (*s0).data->Sup.len : 0) <= (*s0).pos);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(void, sssetposition_C0SEQJWfadg6oK29b8FuMZg)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s_8uJqD1Gkzs9bI9bzpslP39a6w, NI pos0) {
	Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ* s0;
	nimfr("ssSetPosition", "streams.nim")
	nimln(324, "streams.nim");
	if (s_8uJqD1Gkzs9bI9bzpslP39a6w) chckObj((*s_8uJqD1Gkzs9bI9bzpslP39a6w).Sup.m_type, (&NTI_lGsM0FdhfyxyplfYoMsgFQ));
	s0 = ((Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ*) (s_8uJqD1Gkzs9bI9bzpslP39a6w));
	nimln(325, "streams.nim");
	(*s0).pos = clamp_RrNgT2340KObgDMnZWSK5A(pos0, ((NI) 0), ((*s0).data ? (*s0).data->Sup.len : 0));
	popFrame();
}

N_NIMCALL(NI, ssgetposition_ht6Fg1Bmvqnb8CP4WayC2A)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s_ZozGEbyW3LBjyAXTtPgjEg) {
	NI result0;
	Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ* s0;
	nimfr("ssGetPosition", "streams.nim")
{	result0 = (NI)0;
	nimln(328, "streams.nim");
	if (s_ZozGEbyW3LBjyAXTtPgjEg) chckObj((*s_ZozGEbyW3LBjyAXTtPgjEg).Sup.m_type, (&NTI_lGsM0FdhfyxyplfYoMsgFQ));
	s0 = ((Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ*) (s_ZozGEbyW3LBjyAXTtPgjEg));
	nimln(329, "streams.nim");
	result0 = (*s0).pos;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, copymem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest0, void* source0, NI size0) {
	void* LOC1;
	LOC1 = (void*)0;
	LOC1 = memcpy(dest0, source0, ((size_t) (size0)));
}

N_NIMCALL(NI, ssreaddata_7P4Enb2Vt3iOCL5K9cnGqYw)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s_y2kqirqL6p0kJkuwFdE8DQ, void* buffer0, NI buflen0) {
	NI result0;
	Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ* s0;
	NI T_Ue7tnBcsL67VCiRfvt8q0A_14;
	nimfr("ssReadData", "streams.nim")
	result0 = (NI)0;
	nimln(332, "streams.nim");
	if (s_y2kqirqL6p0kJkuwFdE8DQ) chckObj((*s_y2kqirqL6p0kJkuwFdE8DQ).Sup.m_type, (&NTI_lGsM0FdhfyxyplfYoMsgFQ));
	s0 = ((Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ*) (s_y2kqirqL6p0kJkuwFdE8DQ));
	nimln(333, "streams.nim");
	T_Ue7tnBcsL67VCiRfvt8q0A_14 = subInt(((*s0).data ? (*s0).data->Sup.len : 0), (*s0).pos);
	result0 = ((buflen0 <= (NI)(T_Ue7tnBcsL67VCiRfvt8q0A_14)) ? buflen0 : (NI)(T_Ue7tnBcsL67VCiRfvt8q0A_14));
	nimln(334, "streams.nim");
	{
		NI T_Ue7tnBcsL67VCiRfvt8q0A_15;
		if (!(((NI) 0) < result0)) goto LA3;
		nimln(335, "streams.nim");
		if ((NU)((*s0).pos) > (NU)((*s0).data->Sup.len)) raiseIndexError();
		copymem_E1xtACub5WcDa3vbrIXbwgsystem(buffer0, ((void*) ((&(*s0).data->data[(*s0).pos]))), ((NI)chckRange(result0, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln(336, "streams.nim");
		T_Ue7tnBcsL67VCiRfvt8q0A_15 = addInt((*s0).pos, result0);
		(*s0).pos = (NI)(T_Ue7tnBcsL67VCiRfvt8q0A_15);
	}
	LA3: ;
	popFrame();
	return result0;
}

N_NIMCALL(NI, sspeekdata_7P4Enb2Vt3iOCL5K9cnGqYw_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s_QXLskfGc1Jev0gVF9a0jofg, void* buffer0, NI buflen0) {
	NI result0;
	Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ* s0;
	NI T_Ue7tnBcsL67VCiRfvt8q0A_16;
	nimfr("ssPeekData", "streams.nim")
	result0 = (NI)0;
	nimln(339, "streams.nim");
	if (s_QXLskfGc1Jev0gVF9a0jofg) chckObj((*s_QXLskfGc1Jev0gVF9a0jofg).Sup.m_type, (&NTI_lGsM0FdhfyxyplfYoMsgFQ));
	s0 = ((Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ*) (s_QXLskfGc1Jev0gVF9a0jofg));
	nimln(340, "streams.nim");
	T_Ue7tnBcsL67VCiRfvt8q0A_16 = subInt(((*s0).data ? (*s0).data->Sup.len : 0), (*s0).pos);
	result0 = ((buflen0 <= (NI)(T_Ue7tnBcsL67VCiRfvt8q0A_16)) ? buflen0 : (NI)(T_Ue7tnBcsL67VCiRfvt8q0A_16));
	nimln(341, "streams.nim");
	{
		if (!(((NI) 0) < result0)) goto LA3;
		nimln(342, "streams.nim");
		if ((NU)((*s0).pos) > (NU)((*s0).data->Sup.len)) raiseIndexError();
		copymem_E1xtACub5WcDa3vbrIXbwgsystem(buffer0, ((void*) ((&(*s0).data->data[(*s0).pos]))), ((NI)chckRange(result0, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA3: ;
	popFrame();
	return result0;
}

N_NIMCALL(void, sswritedata_mrtMhMXvYVpi5Svw9bWueBw)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s_TBWsPQ4EX2P6UUIoXpDeGQ, void* buffer0, NI buflen0) {
	Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ* s0;
	NI T_Ue7tnBcsL67VCiRfvt8q0A_19;
	nimfr("ssWriteData", "streams.nim")
{	nimln(345, "streams.nim");
	if (s_TBWsPQ4EX2P6UUIoXpDeGQ) chckObj((*s_TBWsPQ4EX2P6UUIoXpDeGQ).Sup.m_type, (&NTI_lGsM0FdhfyxyplfYoMsgFQ));
	s0 = ((Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ*) (s_TBWsPQ4EX2P6UUIoXpDeGQ));
	nimln(346, "streams.nim");
	{
		if (!(buflen0 <= ((NI) 0))) goto LA3;
		nimln(347, "streams.nim");
		goto BeforeRet;
	}
	LA3: ;
	nimln(348, "streams.nim");
	{
		NI T_Ue7tnBcsL67VCiRfvt8q0A_17;
		NI T_Ue7tnBcsL67VCiRfvt8q0A_18;
		T_Ue7tnBcsL67VCiRfvt8q0A_17 = addInt((*s0).pos, buflen0);
		if (!(((*s0).data ? (*s0).data->Sup.len : 0) < (NI)(T_Ue7tnBcsL67VCiRfvt8q0A_17))) goto LA7;
		nimln(349, "streams.nim");
		T_Ue7tnBcsL67VCiRfvt8q0A_18 = addInt((*s0).pos, buflen0);
		(*s0).data = setLengthStr((*s0).data, ((NI)chckRange((NI)(T_Ue7tnBcsL67VCiRfvt8q0A_18), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA7: ;
	nimln(350, "streams.nim");
	if ((NU)((*s0).pos) > (NU)((*s0).data->Sup.len)) raiseIndexError();
	copymem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*s0).data->data[(*s0).pos]))), buffer0, ((NI)chckRange(buflen0, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(351, "streams.nim");
	T_Ue7tnBcsL67VCiRfvt8q0A_19 = addInt((*s0).pos, buflen0);
	(*s0).pos = (NI)(T_Ue7tnBcsL67VCiRfvt8q0A_19);
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, ssclose_qQbp4Nsuc4ou9bqUUbaqJ6A)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s_0oKy9bw20eQoZnoPxmQTRPQ) {
	Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ* s0;
	NimStringDesc* LOC1;
	nimfr("ssClose", "streams.nim")
	nimln(354, "streams.nim");
	if (s_0oKy9bw20eQoZnoPxmQTRPQ) chckObj((*s_0oKy9bw20eQoZnoPxmQTRPQ).Sup.m_type, (&NTI_lGsM0FdhfyxyplfYoMsgFQ));
	s0 = ((Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ*) (s_0oKy9bw20eQoZnoPxmQTRPQ));
	nimln(355, "streams.nim");
	LOC1 = (NimStringDesc*)0;
	LOC1 = (*s0).data; (*s0).data = copyStringRC1(NIM_NIL);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	popFrame();
}
static N_NIMCALL(void, Marker_TY_oa89b9cIODFBktXa1hHFh9c3Q)(void* p, NI op) {
	Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ* a;
	a = (Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ*)p;
	nimGCvisit((void*)(*a).data, op);
}

N_NIMCALL(Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ*, newstringstream_0dQ0A0pna0dG9cMxo4TbLKQ)(NimStringDesc* s0) {
	Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ* result0;
	NimStringDesc* LOC1;
	nimfr("newStringStream", "streams.nim")
	result0 = (Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ*)0;
	nimln(359, "streams.nim");
	result0 = (Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ*) newObj((&NTI_oa89b9cIODFBktXa1hHFh9c3Q), sizeof(Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ));
	(*result0).Sup.Sup.m_type = (&NTI_lGsM0FdhfyxyplfYoMsgFQ);
	nimln(360, "streams.nim");
	LOC1 = (NimStringDesc*)0;
	LOC1 = (*result0).data; (*result0).data = copyStringRC1(s0);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(361, "streams.nim");
	(*result0).pos = ((NI) 0);
	nimln(362, "streams.nim");
	(*result0).Sup.closeimpl = ssclose_qQbp4Nsuc4ou9bqUUbaqJ6A;
	nimln(363, "streams.nim");
	(*result0).Sup.atendimpl = ssatend_acl02gpfK9cCD8utiP6NxdA;
	nimln(364, "streams.nim");
	(*result0).Sup.setpositionimpl = sssetposition_C0SEQJWfadg6oK29b8FuMZg;
	nimln(365, "streams.nim");
	(*result0).Sup.getpositionimpl = ssgetposition_ht6Fg1Bmvqnb8CP4WayC2A;
	nimln(366, "streams.nim");
	(*result0).Sup.readdataimpl = ssreaddata_7P4Enb2Vt3iOCL5K9cnGqYw;
	nimln(367, "streams.nim");
	(*result0).Sup.peekdataimpl = sspeekdata_7P4Enb2Vt3iOCL5K9cnGqYw_2;
	nimln(368, "streams.nim");
	(*result0).Sup.writedataimpl = sswritedata_mrtMhMXvYVpi5Svw9bWueBw;
	popFrame();
	return result0;
}

N_NIMCALL(void, fsclose_qQbp4Nsuc4ou9bqUUbaqJ6A_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	nimfr("fsClose", "streams.nim")
	nimln(377, "streams.nim");
	{
		nimln(347, "system.nim");
		nimln(377, "streams.nim");
		if (s0) chckObj((*s0).Sup.m_type, (&NTI_qoDM8xYRV40zbhS9acPNT9bw));
		if (!!(((*((Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*) (s0))).f == NIM_NIL))) goto LA3;
		nimln(378, "streams.nim");
		if (s0) chckObj((*s0).Sup.m_type, (&NTI_qoDM8xYRV40zbhS9acPNT9bw));
		close_BWnr8V7RERYno9bIdPmw8Hw((*((Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*) (s0))).f);
		nimln(379, "streams.nim");
		if (s0) chckObj((*s0).Sup.m_type, (&NTI_qoDM8xYRV40zbhS9acPNT9bw));
		(*((Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*) (s0))).f = NIM_NIL;
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, fsflush_qQbp4Nsuc4ou9bqUUbaqJ6A_3)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	nimfr("fsFlush", "streams.nim")
	nimln(380, "streams.nim");
	if (s0) chckObj((*s0).Sup.m_type, (&NTI_qoDM8xYRV40zbhS9acPNT9bw));
	flushfile_BWnr8V7RERYno9bIdPmw8Hw_2((*((Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*) (s0))).f);
	popFrame();
}

N_NIMCALL(NIM_BOOL, fsatend_acl02gpfK9cCD8utiP6NxdA_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NIM_BOOL result0;
	nimfr("fsAtEnd", "streams.nim")
{	result0 = (NIM_BOOL)0;
	nimln(381, "streams.nim");
	if (s0) chckObj((*s0).Sup.m_type, (&NTI_qoDM8xYRV40zbhS9acPNT9bw));
	result0 = endoffile_OpxMRqWNQzmofyVQsNQqVA((*((Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*) (s0))).f);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(void, fssetposition_C0SEQJWfadg6oK29b8FuMZg_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, NI pos0) {
	nimfr("fsSetPosition", "streams.nim")
	nimln(382, "streams.nim");
	if (s0) chckObj((*s0).Sup.m_type, (&NTI_qoDM8xYRV40zbhS9acPNT9bw));
	setfilepos_YAngY19cHH2nZ9bqhMgAHz8Q((*((Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*) (s0))).f, ((NI64) (pos0)), ((Fileseekpos_I9aQjuvWxs8BspGbxwsngWw) 0));
	popFrame();
}

N_NIMCALL(NI, fsgetposition_ht6Fg1Bmvqnb8CP4WayC2A_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0) {
	NI result0;
	NI64 LOC1;
	nimfr("fsGetPosition", "streams.nim")
{	result0 = (NI)0;
	nimln(383, "streams.nim");
	if (s0) chckObj((*s0).Sup.m_type, (&NTI_qoDM8xYRV40zbhS9acPNT9bw));
	LOC1 = (NI64)0;
	LOC1 = getfilepos_XePgC9ccBXCgb9bEHXZpnMqA_2((*((Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*) (s0))).f);
	result0 = ((NI) (LOC1));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NI, fsreaddata_7P4Enb2Vt3iOCL5K9cnGqYw_3)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, void* buffer0, NI buflen0) {
	NI result0;
	nimfr("fsReadData", "streams.nim")
	result0 = (NI)0;
	nimln(386, "streams.nim");
	if (s0) chckObj((*s0).Sup.m_type, (&NTI_qoDM8xYRV40zbhS9acPNT9bw));
	result0 = readbuffer_1qjbrvfnPD4PaIieHVDvhw((*((Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*) (s0))).f, buffer0, ((NI)chckRange(buflen0, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result0;
}

N_NIMCALL(NI, fspeekdata_7P4Enb2Vt3iOCL5K9cnGqYw_4)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, void* buffer0, NI buflen0) {
	NI volatile result0;
	NI pos0;
	TSafePoint T_Ue7tnBcsL67VCiRfvt8q0A_20;
	nimfr("fsPeekData", "streams.nim")
	result0 = (NI)0;
	nimln(389, "streams.nim");
	pos0 = fsgetposition_ht6Fg1Bmvqnb8CP4WayC2A_2(s0);
	nimln(390, "streams.nim");
	pushSafePoint(&T_Ue7tnBcsL67VCiRfvt8q0A_20);
	T_Ue7tnBcsL67VCiRfvt8q0A_20.status = setjmp(T_Ue7tnBcsL67VCiRfvt8q0A_20.context);
	if (T_Ue7tnBcsL67VCiRfvt8q0A_20.status == 0) {
		nimln(391, "streams.nim");
		if (s0) chckObj((*s0).Sup.m_type, (&NTI_qoDM8xYRV40zbhS9acPNT9bw));
		result0 = readbuffer_1qjbrvfnPD4PaIieHVDvhw((*((Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*) (s0))).f, buffer0, ((NI)chckRange(buflen0, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
	}
	{
		nimln(390, "streams.nim");
		fssetposition_C0SEQJWfadg6oK29b8FuMZg_2(s0, pos0);
	}
	if (T_Ue7tnBcsL67VCiRfvt8q0A_20.status != 0) reraiseException();
	popFrame();
	return result0;
}

N_NIMCALL(void, fswritedata_mrtMhMXvYVpi5Svw9bWueBw_2)(Streamobj_RShkcoDOPnoCVhtpN1hDPQ* s0, void* buffer0, NI buflen0) {
	nimfr("fsWriteData", "streams.nim")
	nimln(394, "streams.nim");
	{
		NI LOC3;
		Ioerror_9czoZw3pzPyrBmb5zTHY1OQ* LOC6;
		nimln(347, "system.nim");
		nimln(394, "streams.nim");
		if (s0) chckObj((*s0).Sup.m_type, (&NTI_qoDM8xYRV40zbhS9acPNT9bw));
		LOC3 = (NI)0;
		LOC3 = writebuffer_1qjbrvfnPD4PaIieHVDvhw_2((*((Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*) (s0))).f, buffer0, ((NI)chckRange(buflen0, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		if (!!((LOC3 == buflen0))) goto LA4;
		nimln(395, "streams.nim");
		LOC6 = (Ioerror_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		LOC6 = neweio_lOrpXone7dPkEAOURnfgBw(((NimStringDesc*) &T_Ue7tnBcsL67VCiRfvt8q0A_21));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}
static N_NIMCALL(void, Marker_TY_Z018yRjOOerOKfp9aM3JSOg)(void* p, NI op) {
	Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw* a;
	a = (Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*)p;
}

N_NIMCALL(Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*, newfilestream_j9aOzR9a9bXMSUnTXiGmXXGqQ)(FILE* f0) {
	Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw* result0;
	nimfr("newFileStream", "streams.nim")
	result0 = (Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*)0;
	nimln(399, "streams.nim");
	result0 = (Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*) newObj((&NTI_Z018yRjOOerOKfp9aM3JSOg), sizeof(Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw));
	(*result0).Sup.Sup.m_type = (&NTI_qoDM8xYRV40zbhS9acPNT9bw);
	nimln(400, "streams.nim");
	(*result0).f = f0;
	nimln(401, "streams.nim");
	(*result0).Sup.closeimpl = fsclose_qQbp4Nsuc4ou9bqUUbaqJ6A_2;
	nimln(402, "streams.nim");
	(*result0).Sup.atendimpl = fsatend_acl02gpfK9cCD8utiP6NxdA_2;
	nimln(403, "streams.nim");
	(*result0).Sup.setpositionimpl = fssetposition_C0SEQJWfadg6oK29b8FuMZg_2;
	nimln(404, "streams.nim");
	(*result0).Sup.getpositionimpl = fsgetposition_ht6Fg1Bmvqnb8CP4WayC2A_2;
	nimln(405, "streams.nim");
	(*result0).Sup.readdataimpl = fsreaddata_7P4Enb2Vt3iOCL5K9cnGqYw_3;
	nimln(406, "streams.nim");
	(*result0).Sup.peekdataimpl = fspeekdata_7P4Enb2Vt3iOCL5K9cnGqYw_4;
	nimln(407, "streams.nim");
	(*result0).Sup.writedataimpl = fswritedata_mrtMhMXvYVpi5Svw9bWueBw_2;
	nimln(408, "streams.nim");
	(*result0).Sup.flushimpl = fsflush_qQbp4Nsuc4ou9bqUUbaqJ6A_3;
	popFrame();
	return result0;
}

N_NIMCALL(Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*, newfilestream_EYjHaJgKBbBv69c9c5DDOTIg)(NimStringDesc* filename0, Filemode_fVUBHvW79bXUw1j55Oo9avSQ mode0) {
	Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw* result0;
	FILE* f0;
	nimfr("newFileStream", "streams.nim")
	result0 = (Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*)0;
	f0 = (FILE*)0;
	nimln(415, "streams.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = open_sEp0GH2306oGo9bqBpj5oTQ(&f0, filename0, mode0, ((NI) -1));
		if (!LOC3) goto LA4;
		result0 = newfilestream_j9aOzR9a9bXMSUnTXiGmXXGqQ(f0);
	}
	LA4: ;
	popFrame();
	return result0;
}
static N_NIMCALL(void, Marker_TY_r3Wc5tOoxP8rz1DvGVTUvw)(void* p, NI op) {
	Streamobj_RShkcoDOPnoCVhtpN1hDPQ* a;
	a = (Streamobj_RShkcoDOPnoCVhtpN1hDPQ*)p;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void) {
	nimfr("streams", "streams.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void) {
static TNimNode* T_Ue7tnBcsL67VCiRfvt8q0A_12[8];
static TNimNode* T_Ue7tnBcsL67VCiRfvt8q0A_13[2];
static TNimNode T_Ue7tnBcsL67VCiRfvt8q0A_0[13];
NTI_RShkcoDOPnoCVhtpN1hDPQ.size = sizeof(Streamobj_RShkcoDOPnoCVhtpN1hDPQ);
NTI_RShkcoDOPnoCVhtpN1hDPQ.kind = 17;
NTI_RShkcoDOPnoCVhtpN1hDPQ.base = (&NTI_13RNkKqUOX1TtorOUlKtqA);
NTI_RShkcoDOPnoCVhtpN1hDPQ.flags = 1;
T_Ue7tnBcsL67VCiRfvt8q0A_12[0] = &T_Ue7tnBcsL67VCiRfvt8q0A_0[1];
NTI_cnkJEp9bna8U6yi9aVW9cAJ0Q.size = sizeof(TY_cnkJEp9bna8U6yi9aVW9cAJ0Q);
NTI_cnkJEp9bna8U6yi9aVW9cAJ0Q.kind = 25;
NTI_cnkJEp9bna8U6yi9aVW9cAJ0Q.base = 0;
NTI_cnkJEp9bna8U6yi9aVW9cAJ0Q.flags = 3;
T_Ue7tnBcsL67VCiRfvt8q0A_0[1].kind = 1;
T_Ue7tnBcsL67VCiRfvt8q0A_0[1].offset = offsetof(Streamobj_RShkcoDOPnoCVhtpN1hDPQ, closeimpl);
T_Ue7tnBcsL67VCiRfvt8q0A_0[1].typ = (&NTI_cnkJEp9bna8U6yi9aVW9cAJ0Q);
T_Ue7tnBcsL67VCiRfvt8q0A_0[1].name = "closeImpl";
T_Ue7tnBcsL67VCiRfvt8q0A_12[1] = &T_Ue7tnBcsL67VCiRfvt8q0A_0[2];
NTI_KjFcmLOhf4VQvVcyLJWXZw.size = sizeof(TY_KjFcmLOhf4VQvVcyLJWXZw);
NTI_KjFcmLOhf4VQvVcyLJWXZw.kind = 25;
NTI_KjFcmLOhf4VQvVcyLJWXZw.base = 0;
NTI_KjFcmLOhf4VQvVcyLJWXZw.flags = 3;
T_Ue7tnBcsL67VCiRfvt8q0A_0[2].kind = 1;
T_Ue7tnBcsL67VCiRfvt8q0A_0[2].offset = offsetof(Streamobj_RShkcoDOPnoCVhtpN1hDPQ, atendimpl);
T_Ue7tnBcsL67VCiRfvt8q0A_0[2].typ = (&NTI_KjFcmLOhf4VQvVcyLJWXZw);
T_Ue7tnBcsL67VCiRfvt8q0A_0[2].name = "atEndImpl";
T_Ue7tnBcsL67VCiRfvt8q0A_12[2] = &T_Ue7tnBcsL67VCiRfvt8q0A_0[3];
NTI_jlOYFw9cHausuCbPoWx2iiA.size = sizeof(TY_jlOYFw9cHausuCbPoWx2iiA);
NTI_jlOYFw9cHausuCbPoWx2iiA.kind = 25;
NTI_jlOYFw9cHausuCbPoWx2iiA.base = 0;
NTI_jlOYFw9cHausuCbPoWx2iiA.flags = 3;
T_Ue7tnBcsL67VCiRfvt8q0A_0[3].kind = 1;
T_Ue7tnBcsL67VCiRfvt8q0A_0[3].offset = offsetof(Streamobj_RShkcoDOPnoCVhtpN1hDPQ, setpositionimpl);
T_Ue7tnBcsL67VCiRfvt8q0A_0[3].typ = (&NTI_jlOYFw9cHausuCbPoWx2iiA);
T_Ue7tnBcsL67VCiRfvt8q0A_0[3].name = "setPositionImpl";
T_Ue7tnBcsL67VCiRfvt8q0A_12[3] = &T_Ue7tnBcsL67VCiRfvt8q0A_0[4];
NTI_Xzm85qBLb9cf9cu8VOfAr8PQ.size = sizeof(TY_Xzm85qBLb9cf9cu8VOfAr8PQ);
NTI_Xzm85qBLb9cf9cu8VOfAr8PQ.kind = 25;
NTI_Xzm85qBLb9cf9cu8VOfAr8PQ.base = 0;
NTI_Xzm85qBLb9cf9cu8VOfAr8PQ.flags = 3;
T_Ue7tnBcsL67VCiRfvt8q0A_0[4].kind = 1;
T_Ue7tnBcsL67VCiRfvt8q0A_0[4].offset = offsetof(Streamobj_RShkcoDOPnoCVhtpN1hDPQ, getpositionimpl);
T_Ue7tnBcsL67VCiRfvt8q0A_0[4].typ = (&NTI_Xzm85qBLb9cf9cu8VOfAr8PQ);
T_Ue7tnBcsL67VCiRfvt8q0A_0[4].name = "getPositionImpl";
T_Ue7tnBcsL67VCiRfvt8q0A_12[4] = &T_Ue7tnBcsL67VCiRfvt8q0A_0[5];
NTI_tjaJtoUzLe1BMUbItlcGhQ.size = sizeof(TY_tjaJtoUzLe1BMUbItlcGhQ);
NTI_tjaJtoUzLe1BMUbItlcGhQ.kind = 25;
NTI_tjaJtoUzLe1BMUbItlcGhQ.base = 0;
NTI_tjaJtoUzLe1BMUbItlcGhQ.flags = 3;
T_Ue7tnBcsL67VCiRfvt8q0A_0[5].kind = 1;
T_Ue7tnBcsL67VCiRfvt8q0A_0[5].offset = offsetof(Streamobj_RShkcoDOPnoCVhtpN1hDPQ, readdataimpl);
T_Ue7tnBcsL67VCiRfvt8q0A_0[5].typ = (&NTI_tjaJtoUzLe1BMUbItlcGhQ);
T_Ue7tnBcsL67VCiRfvt8q0A_0[5].name = "readDataImpl";
T_Ue7tnBcsL67VCiRfvt8q0A_12[5] = &T_Ue7tnBcsL67VCiRfvt8q0A_0[6];
T_Ue7tnBcsL67VCiRfvt8q0A_0[6].kind = 1;
T_Ue7tnBcsL67VCiRfvt8q0A_0[6].offset = offsetof(Streamobj_RShkcoDOPnoCVhtpN1hDPQ, peekdataimpl);
T_Ue7tnBcsL67VCiRfvt8q0A_0[6].typ = (&NTI_tjaJtoUzLe1BMUbItlcGhQ);
T_Ue7tnBcsL67VCiRfvt8q0A_0[6].name = "peekDataImpl";
T_Ue7tnBcsL67VCiRfvt8q0A_12[6] = &T_Ue7tnBcsL67VCiRfvt8q0A_0[7];
NTI_b9bsIuILxTLVZHPvJBW187A.size = sizeof(TY_b9bsIuILxTLVZHPvJBW187A);
NTI_b9bsIuILxTLVZHPvJBW187A.kind = 25;
NTI_b9bsIuILxTLVZHPvJBW187A.base = 0;
NTI_b9bsIuILxTLVZHPvJBW187A.flags = 3;
T_Ue7tnBcsL67VCiRfvt8q0A_0[7].kind = 1;
T_Ue7tnBcsL67VCiRfvt8q0A_0[7].offset = offsetof(Streamobj_RShkcoDOPnoCVhtpN1hDPQ, writedataimpl);
T_Ue7tnBcsL67VCiRfvt8q0A_0[7].typ = (&NTI_b9bsIuILxTLVZHPvJBW187A);
T_Ue7tnBcsL67VCiRfvt8q0A_0[7].name = "writeDataImpl";
T_Ue7tnBcsL67VCiRfvt8q0A_12[7] = &T_Ue7tnBcsL67VCiRfvt8q0A_0[8];
T_Ue7tnBcsL67VCiRfvt8q0A_0[8].kind = 1;
T_Ue7tnBcsL67VCiRfvt8q0A_0[8].offset = offsetof(Streamobj_RShkcoDOPnoCVhtpN1hDPQ, flushimpl);
T_Ue7tnBcsL67VCiRfvt8q0A_0[8].typ = (&NTI_cnkJEp9bna8U6yi9aVW9cAJ0Q);
T_Ue7tnBcsL67VCiRfvt8q0A_0[8].name = "flushImpl";
T_Ue7tnBcsL67VCiRfvt8q0A_0[0].len = 8; T_Ue7tnBcsL67VCiRfvt8q0A_0[0].kind = 2; T_Ue7tnBcsL67VCiRfvt8q0A_0[0].sons = &T_Ue7tnBcsL67VCiRfvt8q0A_12[0];
NTI_RShkcoDOPnoCVhtpN1hDPQ.node = &T_Ue7tnBcsL67VCiRfvt8q0A_0[0];
NTI_lGsM0FdhfyxyplfYoMsgFQ.size = sizeof(Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ);
NTI_lGsM0FdhfyxyplfYoMsgFQ.kind = 17;
NTI_lGsM0FdhfyxyplfYoMsgFQ.base = (&NTI_RShkcoDOPnoCVhtpN1hDPQ);
T_Ue7tnBcsL67VCiRfvt8q0A_13[0] = &T_Ue7tnBcsL67VCiRfvt8q0A_0[10];
T_Ue7tnBcsL67VCiRfvt8q0A_0[10].kind = 1;
T_Ue7tnBcsL67VCiRfvt8q0A_0[10].offset = offsetof(Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ, data);
T_Ue7tnBcsL67VCiRfvt8q0A_0[10].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg);
T_Ue7tnBcsL67VCiRfvt8q0A_0[10].name = "data";
T_Ue7tnBcsL67VCiRfvt8q0A_13[1] = &T_Ue7tnBcsL67VCiRfvt8q0A_0[11];
T_Ue7tnBcsL67VCiRfvt8q0A_0[11].kind = 1;
T_Ue7tnBcsL67VCiRfvt8q0A_0[11].offset = offsetof(Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ, pos);
T_Ue7tnBcsL67VCiRfvt8q0A_0[11].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA);
T_Ue7tnBcsL67VCiRfvt8q0A_0[11].name = "pos";
T_Ue7tnBcsL67VCiRfvt8q0A_0[9].len = 2; T_Ue7tnBcsL67VCiRfvt8q0A_0[9].kind = 2; T_Ue7tnBcsL67VCiRfvt8q0A_0[9].sons = &T_Ue7tnBcsL67VCiRfvt8q0A_13[0];
NTI_lGsM0FdhfyxyplfYoMsgFQ.node = &T_Ue7tnBcsL67VCiRfvt8q0A_0[9];
NTI_oa89b9cIODFBktXa1hHFh9c3Q.size = sizeof(Stringstreamobj_lGsM0FdhfyxyplfYoMsgFQ*);
NTI_oa89b9cIODFBktXa1hHFh9c3Q.kind = 22;
NTI_oa89b9cIODFBktXa1hHFh9c3Q.base = (&NTI_lGsM0FdhfyxyplfYoMsgFQ);
NTI_oa89b9cIODFBktXa1hHFh9c3Q.marker = Marker_TY_oa89b9cIODFBktXa1hHFh9c3Q;
NTI_qoDM8xYRV40zbhS9acPNT9bw.size = sizeof(Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw);
NTI_qoDM8xYRV40zbhS9acPNT9bw.kind = 17;
NTI_qoDM8xYRV40zbhS9acPNT9bw.base = (&NTI_RShkcoDOPnoCVhtpN1hDPQ);
NTI_qoDM8xYRV40zbhS9acPNT9bw.flags = 1;
T_Ue7tnBcsL67VCiRfvt8q0A_0[12].kind = 1;
T_Ue7tnBcsL67VCiRfvt8q0A_0[12].offset = offsetof(Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw, f);
T_Ue7tnBcsL67VCiRfvt8q0A_0[12].typ = (&NTI_7BHnQsEj49a9c6QtudqWTo1w);
T_Ue7tnBcsL67VCiRfvt8q0A_0[12].name = "f";
NTI_qoDM8xYRV40zbhS9acPNT9bw.node = &T_Ue7tnBcsL67VCiRfvt8q0A_0[12];
NTI_Z018yRjOOerOKfp9aM3JSOg.size = sizeof(Filestreamobj_qoDM8xYRV40zbhS9acPNT9bw*);
NTI_Z018yRjOOerOKfp9aM3JSOg.kind = 22;
NTI_Z018yRjOOerOKfp9aM3JSOg.base = (&NTI_qoDM8xYRV40zbhS9acPNT9bw);
NTI_Z018yRjOOerOKfp9aM3JSOg.marker = Marker_TY_Z018yRjOOerOKfp9aM3JSOg;
NTI_r3Wc5tOoxP8rz1DvGVTUvw.size = sizeof(Streamobj_RShkcoDOPnoCVhtpN1hDPQ*);
NTI_r3Wc5tOoxP8rz1DvGVTUvw.kind = 22;
NTI_r3Wc5tOoxP8rz1DvGVTUvw.base = (&NTI_RShkcoDOPnoCVhtpN1hDPQ);
NTI_r3Wc5tOoxP8rz1DvGVTUvw.marker = Marker_TY_r3Wc5tOoxP8rz1DvGVTUvw;
}

