/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/opt/nim/lib -o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_sets.o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_sets.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef linux
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, isempty_UshbaKGVTNLaJdFZ6zcwswsets)(NI hcode0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, isfilled_UshbaKGVTNLaJdFZ6zcwsw_2sets)(NI hcode0);
static N_INLINE(NIM_BOOL, mustrehash_flzFqVXoQqeNJHN4qDyOhwsets)(NI length0, NI counter0);
N_NIMCALL(void, failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg0);
N_NIMCALL(NI, mulInt)(NI a0, NI b0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, rightsize_9aQ9aswOyc6W7eMnLOsk3W7Asets)(NI count0);
N_NIMCALL(NI, nextpoweroftwo_gcitR3TEXHJ3GR9bmwIvtRA)(NI x0);
static N_INLINE(NI, divInt)(NI a0, NI b0);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
static N_INLINE(NI, nexttry_iM1OyigHU0QXXBzsM5QjYAsets)(NI h0, NI maxhash0);
extern NIM_THREADVAR TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(T_0JXiWyhP5OCO8jWMA6sb1w_2, "\012  counter < length ", 20);

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NIM_BOOL, isempty_UshbaKGVTNLaJdFZ6zcwswsets)(NI hcode0) {
	NIM_BOOL result0;
	nimfr("isEmpty", "sets.nim")
	result0 = (NIM_BOOL)0;
	nimln(47, "sets.nim");
	result0 = (hcode0 == ((NI) 0));
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, isfilled_UshbaKGVTNLaJdFZ6zcwsw_2sets)(NI hcode0) {
	NIM_BOOL result0;
	nimfr("isFilled", "sets.nim")
	result0 = (NIM_BOOL)0;
	nimln(50, "sets.nim");
	nimln(347, "system.nim");
	nimln(50, "sets.nim");
	result0 = !((hcode0 == ((NI) 0)));
	popFrame();
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NIM_BOOL, mustrehash_flzFqVXoQqeNJHN4qDyOhwsets)(NI length0, NI counter0) {
	NIM_BOOL result0;
	NIM_BOOL LOC5;
	NI T_0JXiWyhP5OCO8jWMA6sb1w_3;
	NI T_0JXiWyhP5OCO8jWMA6sb1w_4;
	NI T_0JXiWyhP5OCO8jWMA6sb1w_5;
	nimfr("mustRehash", "sets.nim")
	result0 = (NIM_BOOL)0;
	nimln(114, "sets.nim");
	{
		if (!!((counter0 < length0))) goto LA3;
		failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &T_0JXiWyhP5OCO8jWMA6sb1w_2));
	}
	LA3: ;
	nimln(115, "sets.nim");
	LOC5 = (NIM_BOOL)0;
	T_0JXiWyhP5OCO8jWMA6sb1w_3 = mulInt(length0, ((NI) 2));
	T_0JXiWyhP5OCO8jWMA6sb1w_4 = mulInt(counter0, ((NI) 3));
	LOC5 = ((NI)(T_0JXiWyhP5OCO8jWMA6sb1w_3) < (NI)(T_0JXiWyhP5OCO8jWMA6sb1w_4));
	if (LOC5) goto LA6;
	T_0JXiWyhP5OCO8jWMA6sb1w_5 = subInt(length0, counter0);
	LOC5 = ((NI)(T_0JXiWyhP5OCO8jWMA6sb1w_5) < ((NI) 4));
	LA6: ;
	result0 = LOC5;
	popFrame();
	return result0;
}

static N_INLINE(NI, divInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		if (!(b0 == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (NIM_BOOL)0;
		LOC7 = (a0 == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b0 == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result0 = (NI)(a0 / b0);
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, rightsize_9aQ9aswOyc6W7eMnLOsk3W7Asets)(NI count0) {
	NI result0;
	NI T_0JXiWyhP5OCO8jWMA6sb1w_6;
	NI T_0JXiWyhP5OCO8jWMA6sb1w_7;
	NI T_0JXiWyhP5OCO8jWMA6sb1w_8;
	nimfr("rightSize", "sets.nim")
	result0 = (NI)0;
	nimln(124, "sets.nim");
	T_0JXiWyhP5OCO8jWMA6sb1w_6 = mulInt(((NI) (count0)), ((NI) 3));
	T_0JXiWyhP5OCO8jWMA6sb1w_7 = divInt(((NI) ((NI)(T_0JXiWyhP5OCO8jWMA6sb1w_6))), ((NI) 2));
	T_0JXiWyhP5OCO8jWMA6sb1w_8 = addInt(((NI) ((NI)(T_0JXiWyhP5OCO8jWMA6sb1w_7))), ((NI) 4));
	result0 = nextpoweroftwo_gcitR3TEXHJ3GR9bmwIvtRA(((NI) ((NI)(T_0JXiWyhP5OCO8jWMA6sb1w_8))));
	popFrame();
	return result0;
}

static N_INLINE(NI, nexttry_iM1OyigHU0QXXBzsM5QjYAsets)(NI h0, NI maxhash0) {
	NI result0;
	NI T_0JXiWyhP5OCO8jWMA6sb1w_9;
	nimfr("nextTry", "sets.nim")
	result0 = (NI)0;
	nimln(127, "sets.nim");
	T_0JXiWyhP5OCO8jWMA6sb1w_9 = addInt(h0, ((NI) 1));
	result0 = (NI)((NI)(T_0JXiWyhP5OCO8jWMA6sb1w_9) & maxhash0);
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit000)(void) {
	nimfr("sets", "sets.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit000)(void) {
}

