/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/opt/nim/lib -o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_epoll.o /home/me/Desktop/Code/Nim/Spinny/nimcache/stdlib_epoll.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/epoll.h>
#undef linux
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
TNimType NTI_zUGEEklrq4WOkixy0PK9cIw;
extern TNimType NTI_JrFyJbYm9b5I4hJ9cWDqvfYA;
TNimType NTI_2zPOjfx9bqs1CxrYPul9cXNw;
extern TNimType NTI_nlCscttRCss70IBTyuBqnA;
extern NIM_THREADVAR TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_epollInit000)(void) {
	nimfr("epoll", "epoll.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_epollDatInit000)(void) {
static TNimNode* T_pL9c1OKQinI5mjHLhmJ4TsA_2[2];
static TNimNode T_pL9c1OKQinI5mjHLhmJ4TsA_0[4];
NTI_zUGEEklrq4WOkixy0PK9cIw.size = sizeof(struct epoll_event);
NTI_zUGEEklrq4WOkixy0PK9cIw.kind = 18;
NTI_zUGEEklrq4WOkixy0PK9cIw.base = 0;
NTI_zUGEEklrq4WOkixy0PK9cIw.flags = 3;
T_pL9c1OKQinI5mjHLhmJ4TsA_2[0] = &T_pL9c1OKQinI5mjHLhmJ4TsA_0[1];
T_pL9c1OKQinI5mjHLhmJ4TsA_0[1].kind = 1;
T_pL9c1OKQinI5mjHLhmJ4TsA_0[1].offset = offsetof(struct epoll_event, events);
T_pL9c1OKQinI5mjHLhmJ4TsA_0[1].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA);
T_pL9c1OKQinI5mjHLhmJ4TsA_0[1].name = "events";
T_pL9c1OKQinI5mjHLhmJ4TsA_2[1] = &T_pL9c1OKQinI5mjHLhmJ4TsA_0[2];
NTI_2zPOjfx9bqs1CxrYPul9cXNw.size = sizeof(union epoll_data);
NTI_2zPOjfx9bqs1CxrYPul9cXNw.kind = 18;
NTI_2zPOjfx9bqs1CxrYPul9cXNw.base = 0;
NTI_2zPOjfx9bqs1CxrYPul9cXNw.flags = 3;
T_pL9c1OKQinI5mjHLhmJ4TsA_0[3].kind = 1;
T_pL9c1OKQinI5mjHLhmJ4TsA_0[3].offset = offsetof(union epoll_data, fd);
T_pL9c1OKQinI5mjHLhmJ4TsA_0[3].typ = (&NTI_nlCscttRCss70IBTyuBqnA);
T_pL9c1OKQinI5mjHLhmJ4TsA_0[3].name = "fd";
NTI_2zPOjfx9bqs1CxrYPul9cXNw.node = &T_pL9c1OKQinI5mjHLhmJ4TsA_0[3];
T_pL9c1OKQinI5mjHLhmJ4TsA_0[2].kind = 1;
T_pL9c1OKQinI5mjHLhmJ4TsA_0[2].offset = offsetof(struct epoll_event, data);
T_pL9c1OKQinI5mjHLhmJ4TsA_0[2].typ = (&NTI_2zPOjfx9bqs1CxrYPul9cXNw);
T_pL9c1OKQinI5mjHLhmJ4TsA_0[2].name = "data";
T_pL9c1OKQinI5mjHLhmJ4TsA_0[0].len = 2; T_pL9c1OKQinI5mjHLhmJ4TsA_0[0].kind = 2; T_pL9c1OKQinI5mjHLhmJ4TsA_0[0].sons = &T_pL9c1OKQinI5mjHLhmJ4TsA_2[0];
NTI_zUGEEklrq4WOkixy0PK9cIw.node = &T_pL9c1OKQinI5mjHLhmJ4TsA_0[0];
}

